### ISSUE TITLE
Sourceforge name not respected

### ISSUE THREAD

**Issue by scop** [fedora-infra/anitya#100]
I have sourceforge name set to modplug-xmms for libmodplug (which is correct), but Anitya tries to fetch stuff from http://sourceforge.net/projects/libmodplug/rss (should be http://sourceforge.net/projects/modplug-xmms/rss)

https://release-monitoring.org/project/5669/edit

**Comment by pypingou** [comment]
It's the other way around, the name of the project on SF is modplug-xmms and libmodplug is what to search for in the rss feed.

**Comment by scop** [comment]
Hm, so how should this be configured? The project name is libmodplug (ditto its tarball name), the SF project it is under is modplug-xmms. Can the SF backend be used for this case at all without lying about the project name at all? With cnucnu this was not a problem.

**Comment by pypingou** [comment]
The project is modplug-xmms, it just releases several sub-project including libmodplug.

**Comment by scop** [comment]
Ok, if you want to have it that way. But I need monitoring for the modplugtools and libmodplug "subprojects", they have different version numbering schemes. How do I configure them in Anitya?

**Comment by pypingou** [comment]
I do not *want* to have it this way, I'm just trying to explain the way I designed it. Yes it might not be perfect, yes it can be improved and yes you are coming across as pretty harsh, for a reason I'm not sure to understand.

As for how to set it up, as it's like I said in the first comment, set modplug-xmms as project name and libmodplug as sourceforge name.
If the constraint on unique name+homepage bits you, then we are back on the issue https://github.com/fedora-infra/anitya/issues/80 and we'll have to come up with something for this (not sure what for the moment).

**Comment by scop** [comment]
I don't mean to be harsh, but from your very short comments it was impossible for me to know what is working as designed, and what is a bug, and what is the way I should configure stuff, so I have to keep guessing and asking for more information.

Before I go and make a mess (the possibilities to delete things seem to be limited at the moment so I'd rather ask), could you please confirm how do I now configure *two* subprojects for modplug-xmms: libmodplug and modplugtools. Do I configure two different projects by the modplug-xmms name in Anitya and set sourceforge name for one of them to libmodplug and modplugtools for the other?

**Comment by pypingou** [comment]
I think you are in the same situation as #80, 1 project releasing multiples sources and that seems not to work as I thought and there is likely a bug or something broken in the design.
I'll look closer into this as I thought I did encounter this situation when writing anitya.

Let me get back to you with the proper setup or a fix :-)

**Comment by pypingou** [comment]
Ok I tried to summarize a little the situation and problem here: http://blog.pingoured.fr/index.php?post/2015/02/25/About-SourceForge-and-anitya

**Comment by scop** [comment]
#80 is indeed the same thing, better to continue discussion there.
