### ISSUE TITLE
Enable regex on the retrieved version string (in the below example: /-/./

### ISSUE THREAD

**Issue by heitbaum** [fedora-infra/anitya#1001]
As you can see in this example ICU uses - and _ and . In their file names. And the release tag actually has -

but the versions of the release is actually a .

so 68-2 should be displayed as 68.2

http://site.icu-project.org/
https://github.com/unicode-org/icu/releases
https://release-monitoring.org/project/16134/

another example would be LIBNL 
https://github.com/thom311/libnl/releases

**Comment by Zlopez** [comment]
This looks like another project with special tagging. There is already a [RFE](https://github.com/fedora-infra/anitya/issues/765) created that should solve this issue. Please add this project to the above mentioned issue, I prioritise issues that are requested by multiple people.
