### ISSUE TITLE
Sort order of new release out of order due to a tagging error in the source data

### ISSUE THREAD

**Issue by heitbaum** [fedora-infra/anitya#1002]
Is it possible to block anomalous releases / remap them? In this case we would want to change 2.6.0 to 0.2.6.0 or fail the release from being imported? Perhaps other options would be to go for the newer release not the Larger number.

https://release-monitoring.org/project/141517/

**Comment by Zlopez** [comment]
Right now, there is no option to work with the anomalous releases. I need to think of something.

**Comment by Zlopez** [comment]
This is now solved by version filter.

**Comment by heitbaum** [comment]
> This is now solved by version filter.

I just tried with https://release-monitoring.org/project/5092/ - not sure if it is working as planned

**Comment by Zlopez** [comment]
You can't remove versions by setting up filter, this is just filtering versions received from upstream. Only admin has permission to remove versions from project.

**Comment by Zlopez** [comment]
If you want to remove versions that were already added to Anitya, please flag the project.
