### ISSUE TITLE
Always show "Test Check" and "Full Check" buttons for logged in users

### ISSUE THREAD

**Issue by benzea** [fedora-infra/anitya#1006]
After editing a project, two buttons appear to test or run a check. These are somewhat useful in general, and it would make sense to simply always show the buttons for logged in users.

**Comment by Zlopez** [comment]
In the Anitya 1.0, which will be out soon, I added `Test check` button to edit page, so you can test the changes before submitting. See https://github.com/fedora-infra/anitya/issues/491
The buttons on the project page were meant primarily for admins.
