### ISSUE TITLE
Allow checking anytime one wants to

### ISSUE THREAD

**Issue by scop** [fedora-infra/anitya#101]
I just edited the config for the reptyr project. Anitya does not offer me a button to use for checking what my changes accomplished, so I guess I'll have to wait max 12 hours to see what happened... I think the button for doing this that is visible immediately after creating a project (for doing the initial check) should be always available.

**Comment by ralphbean** [comment]
I think this is done in git but hasn't yet been deployed.

**Comment by ralphbean** [comment]
See #84 and #91.
