### ISSUE TITLE
Fix the stackage backend regex

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#1010]
It looks like the www.stackage.org changed the page layout and it's adding `@rev:X` to the version string we are trying to much with regex in stackage backend.

The solution should be simple, just update the regex to:
```
<span class=\"version\"><a href=\"https://www.stackage.org/lts-[\d.]*/package/adjunctions\">([\d.]*).*</a></span>
```

**Comment by unni2002** [comment]
Hey I would like to contribute to this project . I am a new to open source and want to learn about how to get started .Can someone help me please

**Comment by Zlopez** [comment]
@unni2002 Hi, if you want to help with this issue, it's just about changing the regex for validation in [stackage.py](https://github.com/fedora-infra/anitya/blob/master/anitya/lib/backends/stackage.py).

I recommend to read https://anitya.readthedocs.io/en/latest/contributing.html to know how to test things and what to do when submitting PR.

Thanks for the interest in Anitya.

**Comment by unni2002** [comment]
Hey @Zlopez actually I know Python and basics of Django , can you please help me and tell me what all skills are needed in addition . Sorry to say that , I am not able to understand more about the project that's why

Thanks 
Unni Krishnan

**Comment by Zlopez** [comment]
The Anitya is using [Flask](https://palletsprojects.com/p/flask/) as a web framework and [SQLalchemy](https://www.sqlalchemy.org/) as database framework. Otherwise you should be fine with plain Python.

**Comment by unni2002** [comment]
Hey @Zlopez I am not able to setup the project in my machine as I am having windows but the instructions are for fedora systems . What should I do ??

**Comment by Zlopez** [comment]
I don't use the Windows myself so I can't help you with that. I recommend to use [WLS](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or setup VM machine or you can setup the [python environment](https://anitya.readthedocs.io/en/latest/contributing.html#python-virtualenv) using the tools available on Windows.
