### ISSUE TITLE
RFE: PyPI (PEP 440) versioning scheme

### ISSUE THREAD

**Issue by encukou** [fedora-infra/anitya#1015]
Anitya currently supports [RPM, calver and semver schemes](https://github.com/fedora-infra/anitya/tree/7d9745acb8a9448a25e190ab661ca28026c0066d/anitya/lib/versions).
Python packages (as available on on PyPI and installed by `pip`) use the [PEP 440](https://www.python.org/dev/peps/pep-0440/) versioning scheme, which is unfortunately slightly different in the details ([pre-releases, in particular](https://www.python.org/dev/peps/pep-0440/#semantic-versioning)).

The specification is implemented in the Python module [`packaging.version`](https://packaging.pypa.io/en/latest/version.html) (but could be reimplemented if necessary).

Would it be worth it to add this to anitya?
Is there anything to watch out for if I want to write the PR (apart from general stuff in the Development Guide)?

Last but not least, thank you for Anitya! `the-new-hotness` saves us (Red Hat Python-maint team) a lot of time for Fedora maintenance – we use it so much that this bit of missing functionality is starting to be annoying :)

**Comment by Zlopez** [comment]
I didn't know the PyPI has they own versioning scheme. Could be nice to have it in Anitya.

If you want to create a PR for it, just follow the development guide. In this case you need to add a new class to `anitya.lib.versions` and it should work as expected.
