### ISSUE TITLE
RFE: strip common github tag prefixes

### ISSUE THREAD

**Issue by scop** [fedora-infra/anitya#102]
It'd be good to strip common prefixes used in github tags that are not part of the version string. At least a leading "v" could be removed, ditto "$project-".

**Comment by pypingou** [comment]
The v prefix does not matter in ordering the releases and tbh, I'd rather have the consumer of anitya teach the upstream project how to properly tag/version their projects :)

**Comment by scop** [comment]
The v etc prefixes start to matter if/when those versions are compared against versions of packages let's say in rawhide. I suppose anitya does that - or is it the-new-hotness? There's nothing wrong with the mentioned tag prefixes so the time spent trying to teach this to someone would be more productive somewhere else.

**Comment by pypingou** [comment]
The-new-hotness is the one comparing the version with what is in Fedora.
