### ISSUE TITLE
Missing release reminder bug for WebKitGTK 2.30.5

### ISSUE THREAD

**Issue by mcatanzaro** [fedora-infra/anitya#1022]
Hi, WebKitGTK 2.30.5 was released last Thursday, but I never received a reminder bug on Red Hat Bugzilla.

[The release is visible on release-monitoring.org](https://release-monitoring.org/project/5355/), so I wonder if something is wrong with the Bugzilla integration? This is the first time I'm aware of that it has failed to report a bug for a new upstream version.

**Comment by Zlopez** [comment]
Hi, right now the-new-hotness, which is filling the bugs in Bugzilla, only reports the versions that are higher than the one already in Fedora. I already did the changes in Anitya to be able to report multiple new versions and not only the highest, but in the-new-hotness I still need to implement https://github.com/fedora-infra/the-new-hotness/issues/230
