### ISSUE TITLE
GitHub backend: suitesparse shows non-existent tag

### ISSUE THREAD

**Issue by Alexander-Wilms** [fedora-infra/anitya#1023]
https://release-monitoring.org/project/4908/ shows a version 6.0.0, however, there is no such tag: https://github.com/DrTimothyAldenDavis/SuiteSparse/tags

**Comment by Zlopez** [comment]
Hi, you are right, the version is not there, so the tag was probably there in past and just got deleted. In either case, I deleted the version and now the latest is `5.8.1`.

**Comment by Alexander-Wilms** [comment]
Thanks
