### ISSUE TITLE
add stable_version as output in json.output

### ISSUE THREAD

**Issue by cheese1** [fedora-infra/anitya#1033]
currently we have per project:

  {
    "id": 13934,
    "name": "ampache",
   ...
 "version": "5.0.0-pre-release",
    "versions": [
      "5.0.0-pre-release",
      "4.3.0",
      "4.0.0-pre-release",
      "3.5.1"
    ],
    "stable_versions": [
      "4.3.0",
      "3.5.1"
    ],
...
  }

would be great to have the latest stable_version as:
...
 "version": "5.0.0-pre-release",
 "stable_version": "4.3.0",
...

this would not break anyones scripts, as the meaning of version stays the same AND we get the possibility to filter for the latest stable version.

thanks

**Comment by cheese1** [comment]
analogue to the addition of stable_versions #753 but now just for the latest version

**Comment by Zlopez** [comment]
This sounds like a great idea. Thanks for the suggestion.
