### ISSUE TITLE
Semantic version order is broken

### ISSUE THREAD

**Issue by zyga** [fedora-infra/anitya#1034]
My project has, among others, two releases, 0.4.2 and 0.5. Using semantic check 0.4.2 is picked as latest, using rpm check 0.5 is picked as latest. This is incorrect.

For reference, the project is https://release-monitoring.org/project/168392/

**Comment by Zlopez** [comment]
It's correct, look at the [semantic versioning definition](https://semver.org/). Version `0.5` is malformed according to the semantic versioning scheme.

**Comment by zyga** [comment]
I must say I never considered 0.5 to be different from 0.5.0. Still usability is highly broken. Instead of picking 0.4.2 it should have said that semver ordering cannot be established.

**Comment by Zlopez** [comment]
I'm sorting those versions at the end of the list, so you can see it on first glance that this is not the semantic version.
