### ISSUE TITLE
Wrong stable releases reported for Chromium

### ISSUE THREAD

**Issue by andrunko** [fedora-infra/anitya#1036]
We have an anitya integration with flatpak-external-data-checker and today we got a couple merge requests for a new chromium version (see https://github.com/flathub/org.chromium.Chromium/pull/74).

Looking at it the problem seems that although the checker is configured to look for stable versions only, release-monitoring is actually reporting a dev (canary) branch of chromium as stable:
- https://release-monitoring.org/api/v2/versions/?project_id=13344

Looking at the "official" (I think) chromium release monitoring service (https://omahaproxy.appspot.com/all.json?os=linux;channel=stable), the latest reported stable version is still on `89.0.4389.72` which is correct.

Not sure how this is configured and where release-monitoring gets the info from, but we should probably update it to use the omahaproxy service above or at least find another way to filter for stable releases only.

**Comment by romulasry** [comment]
I borked it, sorry. I wanted it to have newer versions set to pre-release. 

Could you reset it? https://release-monitoring.org/project/13344/

I renamed it to chromium-stable so I don't unknowingly Bork it again.

**Comment by Zlopez** [comment]
@romulasry I fixed the regex for the page, but I'm not sure if any downstream that is watching this project will want only stable versions.

If not, we can just add pre-release filters for the versions that are not considered stable, which if I'm looking at the versioning of Chrome will be easy to do.

**Comment by Zlopez** [comment]
@andrunko For your question about stable releases. Only recognition of the stable and unstable versions the Anitya does is by checking it with set versioning scheme and using pre-release filter. It doesn't have any other way to actually differentiate the stable versions from unstable.

For example, if you have set Semantic versioning on Anitya, the versions X.X.X will be all considered stable, but version X.X.X.rc1 will be considered pre-release.

**Comment by andrunko** [comment]
Thanks both - you may want to consider re-adding dev/beta releases to the list, but not something we (as in Chromium+flatpak-external-data-checker integration) need atm.
