### ISSUE TITLE
Versions do not go in the right order

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1042]
See: https://release-monitoring.org/project/176088/

**Comment by Zlopez** [comment]
This is correct, `5.0` isn't the same as `5.0.0`. 

I tried to update the version filter to skip the 5.0.0-alpha.1, but the filter didn't work, so I need to check what is going on.

**Comment by Zlopez** [comment]
I deleted the `5.0.0-alpha.1` and added `alpha.1` to version filter. So it now shows the correct version as latest. Let's hope they don't change the versioning system again.
