### ISSUE TITLE
How do I set only odd numbers as prereleases without manually doing each one?

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1043]
https://release-monitoring.org/project/13599/

**Comment by Zlopez** [comment]
You need to set the pre-release filter to correct values and keep in mind that it marks everything that contains the string as pre-release. 

To set only odd numbers as pre-release, set the pre-release filter to this: `1.;3.;5.;7.;9.;`. This will filter out anything like `1.2.7`, `3.5.9`. But be aware that this will also remove anything like `2.3.7`, so you need to be careful.

**Comment by romulasry** [comment]
Yeah that won't quite work.

**Comment by Zlopez** [comment]
For now, I don't have anything else.

**Comment by Zlopez** [comment]
This was implemented in #1708
