### ISSUE TITLE
Why do we even have a drupal* backend?

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1044]
Isn't drush and composer enough?

**Comment by Zlopez** [comment]
Could you collaborate a bit more on this? I'm not aware of any drush or composer backend in Anitya

**Comment by romulasry** [comment]
No, you just use those tools to get the latest Drupal modules, not manually.

**Comment by Zlopez** [comment]
Could you share the links to those tools, so I can look at them?

**Comment by romulasry** [comment]
https://www.drush.org/latest/
https://getcomposer.org/

**Comment by Zlopez** [comment]
This looks like refactoring of drupal backend to work with these utilities.

**Comment by romulasry** [comment]
composer will work in getting all php, drupal, modules and themes, etc. So that is all you need it seems.

**Comment by Zlopez** [comment]
I looked at the composer a little closer and I don't see any way to integrate this in Anitya. It's actually a package manager on it's own.

**Comment by Zlopez** [comment]
The same goes for the drush, this tool doesn't have any python library I can use in Anitya.
