### ISSUE TITLE
Missing Bugzilla notification for wpebackend-fdo 1.9.1

### ISSUE THREAD

**Issue by mcatanzaro** [fedora-infra/anitya#1048]
[release-monitoring.org knows about wpebackend-fdo 1.9.1.](https://release-monitoring.org/project/17547/) [But it never reported a bug on Red Hat Bugzilla.](https://bugzilla.redhat.com/buglist.cgi?bug_status=__closed__&bug_status=__open__&component=wpebackend-fdo&list_id=11734066&product=Fedora&query_format=advanced) Alas!

**Comment by Zlopez** [comment]
I remember there was some issue with bugzilla (temporary unavailable) at that time. So it's possible this one was lost in the mess. I removed the version and retrieved it again, hopefully this time it will be reported.

**Comment by Zlopez** [comment]
The new version is now reported https://bugzilla.redhat.com/show_bug.cgi?id=1936507

**Comment by mcatanzaro** [comment]
Thanks
