### ISSUE TITLE
Invalid URL for valid homepage

### ISSUE THREAD

**Issue by mikelolasagasti** [fedora-infra/anitya#1049]
Trying to setup `Homepage` for [`pg_top`](https://release-monitoring.org/project/3556/) `https://pg_top.gitlab.io/` gives `Invalid URL.`

**Comment by Zlopez** [comment]
The `Homepage` field is using standard [HTML input type url](https://www.w3schools.com/tags/att_input_type_url.asp). It looks like the this is not recognized as valid URL. 

But according to [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) this is a valid URI. To me this looks like issue in HTML5 input type validation.

**Comment by Zlopez** [comment]
I tested this on https://stg.release-monitoring.org/ and this is no longer an issue. Closing.
