### ISSUE TITLE
Remove old versions?

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1055]
https://release-monitoring.org/project/8309/

362 | 2019-05-22 19:09 |  
-- | -- | --
361 | Date information unavailable |  
360 | Date information unavailable |  
343 | 2019-01-16 14:01 |  
342 | 2019-01-16 14:01 |  
341 | 2019-01-16 14:01 |  
340 | 2019-01-16 14:01 |  
331 | 2019-01-16 14:01 |  
330 | 2019-01-16 14:01 |  
322 | 2019-01-16 14:01 |

**Comment by Zlopez** [comment]
Deleted
