### ISSUE TITLE
gnu project backend uses ftp.gnu.org not alpha.gnu.org

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1058]
It should use alpha, that is newer. https://release-monitoring.org/project/1258/

**Comment by Zlopez** [comment]
The GNU backend is using ftp.gnu.org, you can change it to custom, if you want.

**Comment by romulasry** [comment]
No, I am suggesting it use alpha by default so it can get newer packages faster.

**Comment by Zlopez** [comment]
Looking at the https://alpha.gnu.org/pub/gnu/grub/ it seems that this page is missing the stable releases, so I rather go with the ftp.gnu.org.
