### ISSUE TITLE
Linking to distro package

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#1064]
I see that `adcli` has a link to Fedora distribution:
- https://release-monitoring.org/project/21/

![image](https://user-images.githubusercontent.com/199095/111442121-b3298000-8710-11eb-9313-4b40cae9cde3.png)

how to add such link to other distributions?

**Comment by Zlopez** [comment]
This was added by this [PR](https://github.com/fedora-infra/anitya/pull/1053) created by @abitrolly, feel free to look how you can do it for other distribution.

**Comment by glensc** [comment]
Oh, such wow hack, no problem adding another one:
- https://github.com/fedora-infra/anitya/pull/1065

But I think the distro mapping should come from config rather hardcoded conditions to template.
Also, that template is huge, I'm sure the templating engine used supports "include" other templates to make templates smaller and more specific function.

I'll leave those concerns to maintainers.

**Comment by Zlopez** [comment]
We could make it configurable, but it's not really a priority right now.

That template is that huge till the time I started maintaining that project, there wasn't really that much changed, but splitting it to multiple sub-templates sounds like a good way to make it better maintainable.

**Comment by Zlopez** [comment]
I added #1067 and #1066 to track these enhancements.

**Comment by Zlopez** [comment]
I will close this one in favor of #1066
