### ISSUE TITLE
Create configuration for distro links

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#1066]
# Description
With introduction of #1053 Anitya has the ability to link package mapping in Anitya to distribution. It would be beneficial to have the link configurable.

## Requirements
* Add new configuration value to map distro to link
* Update project template to read the links from config (this would probably need some property on distro object in models.py)

## How this will make Anitya better
This will make it easier to change the mapping to distributions without changing the code itself.

**Comment by glensc** [comment]
> This will make it easier to change the mapping to distributions without changing the code itself.

but it would still be committed to this repo, right?

**Comment by Zlopez** [comment]
Yes, but it wouldn't need a deployment of new version in release-monitoring.org, because if there will be any change in config on this repo, it's just for the defaults.

**Comment by abitrolly** [comment]
https://github.com/fedora-infra/anitya/issues/557#issuecomment-398645694 lists the steps to make it right, but after 2.5 years I still can not find the time to make ir, so I went with hardcoding the link into the template.

**Comment by Zlopez** [comment]
The same on my side, it's hard to fine time when so much more needs your attention.

**Comment by glensc** [comment]
Well, I would not make it that complex, updating the model, etc.

Just config. use if key present:

```py
DISTRO_PACKAGE_URL = [
  'PLD-Linux': 'http://github.com/pld-linux/%s',
  ...
]
```

```py
url = DISTRO_PACKAGE_URL[distribution] ?: null
```

As with putting to model, who can edit distributions? anybody? wouldn't want someone hijack the distro url and route all traffic to their site? having it in config. it can't be changed by users but only admin making the deploys.

**Comment by Zlopez** [comment]
In template you don't have access to config, so it needs to be provided by something else, either you can give it to it as parameter to the render method or you can add some property to model and just call this property on the page. I would prefer the second option.

This couldn't be edited by editing distributions (which could be edited only by admins with user rights anyway), it will only be set in configuration file, which could be only updated by fedora-infra people.

**Comment by abitrolly** [comment]
Or maybe reuse https://github.com/repology/repology-updater/tree/master/repos.d somehow.
