### ISSUE TITLE
casing in googlecode urls

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/anitya#107]
I added https://release-monitoring.org/project/5737/ for BioNetGen, but the check fails because the url has lowercase bionetgen:
bad: https://code.google.com/p/BioNetGen/downloads/list?sort=releasedate
good: https://code.google.com/p/bionetgen/downloads/list?sort=releasedate

Upstream camelcases the tarball names, so the camelcased name seems to be the right one to use. It would be really nice if I could use the standard googlecode pattern, but allow the name to be lowercase.

**Comment by pypingou** [comment]
So this is an easyfix in the google backend

**Comment by cicku** [comment]
Just a friendly note, Google Code will be shutdown in 2016.

**Comment by pypingou** [comment]
Hi Christopher, thanks for the heads up, do you have a link for this?


-------- Message d'origine --------
De : Christopher Meng <notifications@github.com> 
Date :13/03/2015  05:52  (GMT+01:00) 
À : fedora-infra/anitya <anitya@noreply.github.com> 
Cc : Pierre-Yves Chibon <pingou@pingoured.fr> 
Objet : Re: [anitya] casing in googlecode urls (#107) 

Just a friendly note, Google Code will be shutdown in 2016.

**Comment by cicku** [comment]
http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html

devel list has already advised.

Anyway, about this issue, is it ok to just use lower() to handle the case like bionetgen?

**Comment by pypingou** [comment]
@cicku good idea yes

**Comment by Aayush-Kasurde** [comment]
I would like fix this issue, Can anyone please help to fix it ?

**Comment by Aayush-Kasurde** [comment]
Please see my PR - https://github.com/fedora-infra/anitya/pull/113 and provide comments.

**Comment by pypingou** [comment]
This has been fixed by #114
