### ISSUE TITLE
Recurisvely nested sourceforge pages don't work

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1071]
See: https://release-monitoring.org/project/1463/
https://sourceforge.net/projects/jmol/files/Jmol/Version%2014.31/Jmol%2014.31.34/

**Comment by Zlopez** [comment]
Not sure what exactly happened, but the version_check_url works correctly and the last version was retrieved 10 days ago. So if the sourceforge changed something, it must happened recently. Will look at this.

**Comment by romulasry** [comment]
I updated it to the sourceforge backend, that is what caused it. It is a bug though.

**Comment by Zlopez** [comment]
Found the issue, the package doesn't match the regex, because they have `-full`, `-binary` etc. postfix.

For this case we have custom backend, so I edited the project and it now works.
