### ISSUE TITLE
Puting a space inbetween package names doesn't work right

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1072]
https://release-monitoring.org/project/17628/
This is what it got: https://src.fedoraproject.org/rpms/aom%20libaom

**Comment by Zlopez** [comment]
I actually have doubts that some package in Fedora have space in their name, it would break many things.

There is only aom package in Fedora:
* (aom) https://src.fedoraproject.org/rpms/aom

I fixed the mapping for you
