### ISSUE TITLE
Login with Fedora account fails

### ISSUE THREAD

**Issue by Alexander-Wilms** [fedora-infra/anitya#1074]
I used to be able to log in on release-monitoring.org with my Fedora account. However, I now get this error message:

`Error: There was an error during authentication 'Authentication failed: No matching endpoint found after discovering http://<my_email@address>.com.id.fedoraproject.org/', please check the provided url.`

The actual message contains my email address.

Logging into ask.fedoraproject.org works, though.

**Comment by Zlopez** [comment]
Hi, there is now a change of Fedora authentication system. Try to ask in #fedora-aaa channel on IRC. This is not something on the Anitya side.

**Comment by Zlopez** [comment]
I tried to log in to pagure.io and then tried to log in to Anitya and it works for me.

**Comment by smooge** [comment]
We willl need to know what the FAS user account was to diagnose.

**Comment by Zlopez** [comment]
Response from #fedora-aaa from `nirik`:
```
you should not be using email address there.
that should be username
username.id.fedoraproject.org
```
