### ISSUE TITLE
Coulld you use a script to delete all 'package name' ending in -delete

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1075]
Thanks.

**Comment by Zlopez** [comment]
Do you have a list of packages? I have [scripts](https://github.com/Zlopez/anitya_scripts) that can be used for this, but there is currently no way to find projects by partial package_name.

**Comment by romulasry** [comment]
No, they alll end  in -delete though.

**Comment by Zlopez** [comment]
Is there any way to filter them, like same distro, all projects flagged? It will be much easier to find them.

**Comment by romulasry** [comment]
Not that I remember.

**Comment by Zlopez** [comment]
This will probably take some time to prepare script to actually find the mappings and delete them.

**Comment by Zlopez** [comment]
I tried to work on this today, but currently I'm blocked by this issue https://github.com/fedora-infra/anitya/issues/1081

**Comment by Zlopez** [comment]
I was finally able to finish this one. Bellow is the list of deletion urls for packages:
```
https://release-monitoring.org/project/141/delete/Fedora/autoconf268-delete
https://release-monitoring.org/project/8758/delete/Fedora/awscli-delete
https://release-monitoring.org/project/18830/delete/Fedora/delete-bind-delete
https://release-monitoring.org/project/7014/delete/Fedora/opencryptoki-DELETE
https://release-monitoring.org/project/5250/delete/Arch%20Linux/xorg-delete
https://release-monitoring.org/project/13270/delete/Fedora/xorriso-DELETE
```
