### ISSUE TITLE
Update on PUSH notification?

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1077]
Good idea? Instead of just hourly

Would be nice to have in the future for faster updates.

Here is an example on github: https://medium.com/techulus/how-to-get-push-notifications-from-github-2379491dcb47
gitlab: ?

**Comment by Zlopez** [comment]
This is not usable for Anitya, this needs a Push notifications enabled on GitHub project side. We don't want to bother upstream maintainers.

It would be usable if we could just listen to notifications that are sent automatically.

**Comment by romulasry** [comment]
@Zlopez 
**Introducing new push notifications, scheduling, releases and more on GitHub Mobile**
https://github.blog/2021-03-30-new-push-notifications-scheduling-releases-github-mobile/

I know this is probably not it, but at least it is interesting. Who should I contact about this upstream, do you have a link?

**Comment by Zlopez** [comment]
I'm not sure if we could leverage this on Anitya, it seems to be related to mobile notifications.

**Comment by romulasry** [comment]
@Zlopez
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/QQKP3E4E6ZATOS6HI3SIWJFE2DP2BCAB/

"Add a push update mechanism for https://release-monitoring.org/"

**Comment by Zlopez** [comment]
You can actually leverage Packit for this, it could now watch for release-monitoring messages and create update from it. See https://the-new-hotness.readthedocs.io/en/stable/user-guide.html#opening-pull-requests-in-dist-git
