### ISSUE TITLE
Could you delete all versions then force refresh

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1078]
https://release-monitoring.org/project/8621/
Thanks.

**Comment by Zlopez** [comment]
The versions looks correct, why do you want to delete them?

**Comment by romulasry** [comment]
To get the new Pre-release status.

**Comment by Zlopez** [comment]
There isn't any version that is considered pre-release by RPM versioning. Also there is no need to refresh the versions, pre-release check is applied without it.

**Comment by romulasry** [comment]
There are some, see: https://github.com/wesnoth/wesnoth/releases/tag/1.15.11 Pre-release

**Comment by Zlopez** [comment]
The RPM versioning can't recognize 1.15.11 as a pre-release, if you want it to be recognized as pre-release just edit the project and add a new pre-release filter.
