### ISSUE TITLE
multiple projects with the same name

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/anitya#108]
There is https://github.com/google/closure-compiler and http://npmjs.org/package/closure-compiler. The latter is a wrapper for the former. Fedora packages are called closure-compiler and nodejs-closure-compiler. Both should be added, but when I changed https://release-monitoring.org/project/2209/ to have the name nodejs-closure-compiler, the download url does not work anymore. The problem is similar to #107 — a custom name has to be used in the download url.

**Comment by pypingou** [comment]
The project should not be named nodejs-* that's something that is Fedora specific.

It is not a problem to have two projects with the same name as long as the homepage are differents which in the example you give is the case, so it's all good :)

**Comment by keszybz** [comment]
OK, so I added https://release-monitoring.org/project/5738/. How do I tell anitya that I want to use "compiler" as the tarball name, not closure compiler?

**Comment by pypingou** [comment]
Hm, I had not seen this situation before.

Question, why not using the github backend instead of the google code one?
The github backend will rely on the tags set on the repo, regardless of the name of the tarball.

**Comment by keszybz** [comment]
Github works.

**Comment by ralphbean** [comment]
Oh, if github works... we can close this right?  Please correct me if I'm wrong.

**Comment by keszybz** [comment]
Sure, it works in this case. I think this is bound to come up again though.
