### ISSUE TITLE
https://github.com/enkore/j4-dmenu-desktop is not setting the right latest version

### ISSUE THREAD

**Issue by ibotty** [fedora-infra/anitya#1080]
https://release-monitoring.org/project/187036/

It might well be a configuration mistake, but I don't know how to configure it correctly.

**Comment by Zlopez** [comment]
I just changed the version scheme to RPM and it works correctly.

None of the versions on the project was a correct semantic version, this is why the versions were sorted randomly.

**Comment by ibotty** [comment]
Oh, thank you.  I am pretty sure I set version scheme to RPM at one point but a "Test Check" did yield the same order.  Whatever, great it worked. Thank you again.

**Comment by Zlopez** [comment]
Looking at the code the "Test check" `New versions` field doesn't care about order, the other fields `All versions`, `Latest version` should be in correct order.
