### ISSUE TITLE
Add filter for 'even/odd' projects

### ISSUE THREAD

**Issue by nirik** [fedora-infra/anitya#1088]
The Xfce project uses a 'even' is stable, 'odd' is development for the next version. Like the linux kernel used to do. 

So, for example, 
Thunar-4.16.6 is a stable version (because the 16 there is even and it's part of the 4.16 release.)
Thunar-4.17.1 is a unstable development version (because the 17 is odd and it's part of the development up to the 4.18 release).

It would be nice if anitya had a filter for this.

**Comment by romulasry** [comment]
Yes, it would be nice if you could do %even or %odd as a marx/filter.

**Comment by Justinzobel** [comment]
It would be great to see this documented somewhere and linked next to the filter box! :)

**Comment by Zlopez** [comment]
It's actually documented here https://anitya.readthedocs.io/en/stable/user-guide.html#pre-release-filter
