### ISSUE TITLE
RFE: monitor two releases 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/anitya#1092]
for example opencv https://github.com/opencv/opencv/releases , I'd like monitor releases of 4.x.x and release of 3.x.x

**Comment by Zlopez** [comment]
Anitya actually sends Fedora message for every new release that is found upstream and with `*.project.version.update.v2` topic it even sends multiple new versions in one Fedora message, when they are found in one check.

Could you elaborate more, what you want to achieve here?

**Comment by sergiomb2** [comment]
In some projects,  It may happen in rawhide have beta versions and in released Fedoras only the stable versions. For example I have smb4k , https://release-monitoring.org/project/6221/ , and if a new stable branch, lets say 3.0.8 is release, I'd like have a notification .

Another case was opencv when we start with version 4.x.x on rawhide , some branches still had version 3.x.x and for example when version 3.4.11 was released I'd like had a notification.

**Comment by Zlopez** [comment]
This look more like a RFE for [the-new-hotness](https://github.com/fedora-infra/the-new-hotness), this is the app that is actually notifying the packagers by creating a bugzilla ticket.

We can probably add new notification option to dist-git like `Monitoring (every version)` which will say to hotness to create tickets even if the version isn't newer than the one in rawhide.

Could you create a new ticket for [the-new-hotness](https://github.com/fedora-infra/the-new-hotness/issues)?

**Comment by Zlopez** [comment]
This was already implemented in the-new-hotness, please see https://github.com/fedora-infra/the-new-hotness/issues/230
