### ISSUE TITLE
Regex handler for GitHub projects

### ISSUE THREAD

**Issue by heitbaum** [fedora-infra/anitya#1104]
Could we please enable the regex handler for GitHub projects too?
icu 68-2 should be displayed as 68.2
https://release-monitoring.org/project/16134/

other examples are:
- https://release-monitoring.org/project/1831/
- https://release-monitoring.org/project/1684/
- https://release-monitoring.org/project/381/
- https://release-monitoring.org/project/2081/

**Comment by Zlopez** [comment]
Hi, this is why custom backend exists, just switch backend to custom and as version URL use github tags url and specify your own regex.

The difference between them is that GitHub backend is using GraphQL API and the custom backend just downloads the HTML page and parse it in regex.

But I want to add some kind of version formatter to all backend in the future. See https://github.com/fedora-infra/anitya/issues/765
