### ISSUE TITLE
Project courier-mta mapped to sysconftool Fedora package

### ISSUE THREAD

**Issue by rathann** [fedora-infra/anitya#111]
Project courier-mta was mapped to sysconftool Fedora package and submitted wrong bug reports about new versions being available (see https://bugzilla.redhat.com/show_bug.cgi?id=1196437). I added a new project for sysconftool specifically before noticing that there's no courier-mta package in Fedora and there's no option to delete mapping.

**Comment by pypingou** [comment]
I'm confused, could you give the link to the project/mapping that needs to be deleted? (admins can do it)

**Comment by pypingou** [comment]
ping ?

**Comment by pypingou** [comment]
As far as I can see:

There is a sysconftool in pkgdb : https://admin.fedoraproject.org/pkgdb/package/sysconftool/ mapped in anitya https://release-monitoring.org/project/5763/

I cannot find a courier-mta package in pkgdb : https://admin.fedoraproject.org/pkgdb/packages/courier-mta*/ not in anitya https://release-monitoring.org/projects/search/?pattern=courier-mta*

However, there is a courier project in anitya: https://release-monitoring.org/project/4927/ that was mapped as corresponding to the ``courier`` package in Fedora (while this package does not exist).
So I dropped this mapping.

I hope this is what you had in mind.

Thanks

**Comment by rathann** [comment]
Yes, this is what I meant. Thank you.
