### ISSUE TITLE
Error: There was an error during authentication 'Authentication process canceled', please check the provided url.

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1111]
https://release-monitoring.org/complete/fedora/?janrain_nonce=2021-05-26T20%3A21%3A46ZJkXEvn&openid.mode=cancel&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0

**Comment by nirik** [comment]
There was a auth system outage for about an hour there. It's fixed now, can you please retry?

**Comment by romulasry** [comment]
Works now.
