### ISSUE TITLE
Cannot delete incorrect distribution mapping

### ISSUE THREAD

**Issue by davide125** [fedora-infra/anitya#1115]
https://release-monitoring.org/project/19376/ has a mapping to `golang-github-facebookincubator-ntp` for Fedora, which is incorrect, as it's a completely different package. This leads to bugs like https://bugzilla.redhat.com/show_bug.cgi?id=1963613 . I couldn't find a way to delete this mapping the UI, could you please assist? Thanks!

**Comment by Zlopez** [comment]
Hi, we don't allow users to delete things. This could only be done by admins and we have the `flag` button on top of each project to address this kind of issues.

Anyway, thanks for the report, I deleted the mapping for you.
