### ISSUE TITLE
Wrong version detected for rubygem-fog-xml

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#112]
fog-xml has version 0.1.1 released upstream [1], but R-M detected version 0.0.1.alpha. Not sure where the confusion comes from. May be the ".alpha" is troublesome?

[1] https://rubygems.org/gems/fog-xml
[2] https://release-monitoring.org/project/5785/

**Comment by pypingou** [comment]
Ah found it, the problem is that the backend is github not rubygems and apparently upstream does not push new releases/tags to github.

I've updated the backend and it seems to work now :)

**Comment by voxik** [comment]
How that can be github backend? It should be rubygems backend?

**Comment by pypingou** [comment]
I guess the fact that the URL was github might have confused the script

**Comment by voxik** [comment]
Could you please check it out? Thx.

**Comment by pypingou** [comment]
https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/anitya.py#L261-L264 confirms it

@ralphbean maybe something for us to look into
