### ISSUE TITLE
Migrate from social_auth to something else

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#1139]
The [social_auth-flask](https://github.com/python-social-auth/social-app-flask) is unmaintained for some time, we should look for the alternative that is ideally packaged in Fedora.

**Comment by Zlopez** [comment]
According to #1145 this is now blocking the authentication process even in vagrant dev env. I'm giving this issue a high priority and we should solve it as soon as possible.

**Comment by LenkaSeg** [comment]
What about Authlib as a replacement

https://github.com/lepture/authlib

https://python.libhunt.com/authlib-alternatives

It's
- with openid
- packaged in Fedora: https://src.fedoraproject.org/rpms/python-authlib

**Comment by LenkaSeg** [comment]
Related PR #1220
