### ISSUE TITLE
Too much spam

### ISSUE THREAD

**Issue by yarons** [fedora-infra/anitya#1142]
There's way too much spam on the list.

Numerous examples:
https://release-monitoring.org/project/223157/
https://release-monitoring.org/project/223356/
https://release-monitoring.org/project/223363/
https://release-monitoring.org/project/223360/
https://release-monitoring.org/project/223355/
https://release-monitoring.org/project/223361/
https://release-monitoring.org/project/223364/
https://release-monitoring.org/project/223358/
https://release-monitoring.org/project/223354/
https://release-monitoring.org/project/223359/
https://release-monitoring.org/project/223350/
https://release-monitoring.org/project/223363/
etc.

I've reported some of them but there are just too many.

Is there a way to bulk report or tighten the moderation?

Thanks.

**Comment by Zlopez** [comment]
These will be deleted automatically after reaching 1000 failed checks. No need to worry about them. Originally I had this set to 100 failures, but there was some issue that accidentally removed even the correct entries. This should be fixed now, so I can lower the threshold to delete these more quickly.

The candidates for deletion by this cleaning script must reach the failure threshold and must be without any mapping to distributions.

**Comment by yarons** [comment]
So there's no point to flag this?

**Comment by Zlopez** [comment]
You can flag them, but they will be deleted anyway.

I will lower the threshold, so this occurs more often.

**Comment by Zlopez** [comment]
https://pagure.io/fedora-infra/ansible/pull-request/719

**Comment by Zlopez** [comment]
The change is now applied on release-motnioring.org

These projects should be gone much faster.
