### ISSUE TITLE
Change "Github" to "GitHub"

### ISSUE THREAD

**Issue by richardfearn** [fedora-infra/anitya#115]
Very minor issue. But the correct capitalisation is "GitHub".

**Comment by Aayush-Kasurde** [comment]
Could you please elaborate on this capitalization of word "Github" ?

**Comment by richardfearn** [comment]
Sure. Take the project page for clide, for example:

https://release-monitoring.org/project/6044/

The backend is listed as "Github". That should be "GitHub".

I see that the `GithubBackend` class in `anitya/lib/backends/github.py` has a `name` of `'Github'`, which I guess is where the text in the web interface comes from. But I imagine that name is used in the data stored in the database, so it's probably not as simple as changing the `name`.

**Comment by pypingou** [comment]
It actually is that simple ;-)
https://github.com/fedora-infra/anitya/blob/master/anitya/lib/plugins.py#L54

**Comment by Aayush-Kasurde** [comment]
I am confused. changing name from in "Github" to "GitHub" in `anitya/lib/backends/github.py` will to desired change, isn't it?

**Comment by richardfearn** [comment]
According to Pierre, that's all that's needed...

**Comment by ralphbean** [comment]
Closing this since we're saying #116 is the fix.
