### ISSUE TITLE
Make dependabot less noisy

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/anitya#1163]
Is it possible to tune it to create PRs only when there is security issue or something important to fix? Or ask explicitly to get dependencies update before release? Or make one PR for all deps updates?

**Comment by Zlopez** [comment]
I don't mind having multiple PRs for every dependency. But yes it has some settings you can tweak, I can look into it.

**Comment by Zlopez** [comment]
Looking at the https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore it looks like only option to make it less noisy is to limit the number of opened PRs at once.

**Comment by abitrolly** [comment]
Or check for updates less frequently https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#scheduleinterval

Also found this top voted proposal - https://github.com/dependabot/dependabot-core/issues/1190 - and the comment from two weeks ago saying that GitHub won't have time for it. I don't know, maybe it is some excuse for killing competitors and throwing them some clients.

**Comment by Zlopez** [comment]
The interval is currently set to `weekly`, so it's not that often.

**Comment by abitrolly** [comment]
But there are 16 letters or something every week, needless to say it pollutes search results in PRs.

**Comment by Zlopez** [comment]
This week should be exception, because most of the updates is related to mypy, which was added recently.

**Comment by Zlopez** [comment]
But I understand the pollution of search results :-/

**Comment by abitrolly** [comment]
I would also prefer this mails to be on Thursday. Where cleaning inbox from non-actionable items is my usual activity.

**Comment by Zlopez** [comment]
@abitrolly Is this still bothering you? The number of PRs opened is much smaller than it was at that time.

**Comment by abitrolly** [comment]
@Zlopez I've unsubscribed from all notifications to readjust my priorities towards more money making activities (doesn't help though). So there is no reason to keep it lingering anymore.
