### ISSUE TITLE
mypy check fails with Alembic 1.7.3

### ISSUE THREAD

**Issue by oturpe** [fedora-infra/anitya#1183]
This issue was discovered by the ci run of #1182.
Mypy check fails with the following error:

> anitya/db/migrations/env.py:21: error: Argument 1 to "fileConfig" has incompatible type "Optional[str]"; expected "Union[Union[str, bytes, PathLike[str], PathLike[bytes]], IO[str], RawConfigParser]"

Forcing Alembic version to be 1.7.1 in `requirements.txt` fixes the issue.

**Comment by Zlopez** [comment]
I thought I already fixed this one in https://github.com/fedora-infra/anitya/pull/1178, but it seems like there is something new. I will look at it today.
