### ISSUE TITLE
 nfs-utils: invalid new version 2.5.5 reported

### ISSUE THREAD

**Issue by pevik** [fedora-infra/anitya#1189]
[nfs-utils](https://release-monitoring.org/project/02081/) reports 2.5.5 as the latest version, but this version is not in [tags](http://git.linux-nfs.org/?p=steved/nfs-utils.git;a=tags), which are listed as source. Latest existing release is nfs-utils-2-5-5-rc2 (properly detected).

**Comment by Zlopez** [comment]
At the first glance, this looks like a bad regex to me. I played with it a little and now it works as it should.

**Comment by pevik** [comment]
NOTE: it got broken again for `nfs-utils-2-5-5-rc3`, regexp needs to be fixed again.

**Comment by Zlopez** [comment]
@pevik I'm not sure what are you talking about, the 2.5.5.rc3 is the latest on [nfs-utils project page](https://release-monitoring.org/project/2081/)

**Comment by pevik** [comment]
@Zlopez maybe we use the API wrong way, because it mail us also RC versions. Is there a way just to send final versions?

**Comment by Zlopez** [comment]
Not right now, there is a ticket for it on the-new-hotness https://github.com/fedora-infra/the-new-hotness/issues/320, but it didn't get to work on it yet.
Right now on Anitya you can add filter for versions that contain `rc`, this will skip all the versions containing `rc` in them, or change the regex to just match final versions.
