### ISSUE TITLE
address the decay of the test suite

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/anitya#120]
every time I go to fix an anitya bug, I try to run the tests and they are broken.  not because anitya is broken, but because the tests rely on querying actual upstreams about what versions are available... and those upstreams are always releasing new versions.

I went to try and write what would have been a five minute patch, but I've been fixing the test suite for 40 minutes now :(

----

So, we could do any number of things to fix this.  One of them is mocking.  We could mock ``requests.get()`` so that it returns a fake object with a lookup of all the pages we scrape **today** and we keep copies of all those pages in files in some test data directory.  The tests will then get a *real* copy of a web page that really existed, but it will be frozen in time and will never change.

**Comment by pypingou** [comment]
You can also just skip the backend test suite using ``BUILD_ID=1 runtests.sh``

**Comment by Aayush-Kasurde** [comment]
@ralphbean Can I help you in this ?

**Comment by ralphbean** [comment]
> Can I help you in this ?

Sure could.  Feel free to try your hand at it!

**Comment by pypingou** [comment]
\ó/
