### ISSUE TITLE
GrandOrgue: all releases are being marked as pre-releases

### ISSUE THREAD

**Issue by lbssousa** [fedora-infra/anitya#1217]
I've created a project in release-monitoring.org for GrandOrgue:

https://release-monitoring.org/project/235120/

GrandOrgue upstream versioning scheme is the following: all versions appended by `-0` are pre-releases (example: `3.4.1-0`), while all versions appended by `-1` are production-ready releases (example: `3.4.1-1`).

I'm trying to add these info in fileds `Version filter` and/or `Pre-release filter`, but release-monitoring.org is marking all new releases as pre-releases.

Is there something I'm doing wrong here?

**Comment by Zlopez** [comment]
Fixed, the issue was in using semantic versioning scheme. I changed it to RPM and now every production-ready release is not pre-release.
