### ISSUE TITLE
extreme tux racer doesn't show latest version

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1229]
0.8.1:
https://release-monitoring.org/project/774/

**Comment by Zlopez** [comment]
Looking at the project, I'm actually surprised that this worked in past at all, the regex used for matching versions will never match this.

The released file is named `etr-x.x.x` and the regex is looking for `<project_name>-x.x.x` (in our case `extremetuxracer-x.x.x`).

I fixed the project by switching it to custom backend and there was already some regex filled in, which worked fine.
