### ISSUE TITLE
rpmautospec breaks Fedora patch creation / scratch builds

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/anitya#1231]
When release-monitoring.org / anitya sees a new version for a Fedora package that uses rpmautospec (%autorelease, %autochangelog) and has "Monitoring + Scratch builds" turned on, the patch creation and scratch build are broken:

```
Skipping the scratch build because an SRPM could not be built: ['git', 'commit', '-a', '-m', 'Update to 2.6.0 (#2026174)'] returned 1: b'On branch rawhide\nYour branch is up to date with \'origin/rawhide\'.\n\nUntracked files:\n  (use "git add <file>..." to include in what will be committed)\n\tSRPMS/\n\nnothing added to commit but untracked files present (use "git add" to track)\n'
```

This looks like the new version is not correctly set in the .spec file (otherwise there would be actual changes?)

Example bug: https://bugzilla.redhat.com/show_bug.cgi?id=2026174

**Comment by Zlopez** [comment]
Thanks for reporting moved this issue to the-new-hotness where it belongs.

https://github.com/fedora-infra/the-new-hotness/issues/368
