### ISSUE TITLE
Bitbucket page isn't working

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1239]
https://release-monitoring.org/project/1714/

Unable to retrieve the latest version from upstream!
ERROR: Error when checking for new version: VRTnetworkequipment: no upstream version found. - https://bitbucket.org/vrtsystems/odf-extension-vrt-network-equipment/downloads?tab=tags -  class="name">([^<]*[^tip])</td

**Comment by Zlopez** [comment]
It seems that this project doesn't have any tags on BitBucket, so there is nothing to retrieve. In this case the ERROR is correct. If you know about place where this project versions could be retrieved, feel free to edit the project. :-)
