### ISSUE TITLE
Did Not Connect: Potential Security Issue

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1260]
Firefox detected an issue and did not continue to release-monitoring.org. The website is either misconfigured or your computer clock is set to the wrong time.

It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely.

What can you do about it?

release-monitoring.org has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

**Comment by nirik** [comment]
This is fixed.
