### ISSUE TITLE
Intermediate versions are skipped while update checking

### ISSUE THREAD

**Issue by dfateyev** [fedora-infra/anitya#1273]
The issue that some upstream intermediate versions are now skipped from new versions reporting — when a newer version presents in the version list (e.g. a pre-release one which can look "newer" than stable ones.)

Briefly discussed it with @Zlopez, seems we need remove deprecated limitations on intermediate version reporting.

**Comment by Zlopez** [comment]
The code in question could be found here https://github.com/fedora-infra/anitya/blob/master/anitya/lib/utilities.py#L143

After this change Anitya will send a fedora message every time it finds any new version (versions) not only latest one according to current sort method.
