### ISSUE TITLE
Folder backend returns wrong version

### ISSUE THREAD

**Issue by dfateyev** [fedora-infra/anitya#1286]
The folder backend can retrieve non-version elements,  for example `".."` — when it's provided in the folder listing.
It's needed to exclude it from the version list.

![image](https://user-images.githubusercontent.com/727201/151956228-1327da9f-b908-4429-a999-320724dafa20.png)

**Comment by Zlopez** [comment]
Looking at it more closely, this is probably introduced by https://github.com/fedora-infra/anitya/pull/1061, which was created to not filter out unstable versions on folder backend. I will either adjust the regex again or just remove `..` from retrieved versions.
