### ISSUE TITLE
Remove bad version of rlwrap

### ISSUE THREAD

**Issue by michel-slm** [fedora-infra/anitya#1287]
rlwrap's release monitoring does not currently work since upstream accidentally tagged a git commit (7c1e432) which appears newer than every actual version (0.4?.*).

Can that be manually purged? I've added a version filter for a-f so hopefully anything that doesn't look like an actual version won't show up again. Thanks!

https://release-monitoring.org/project/4199/

**Comment by Zlopez** [comment]
The version was deleted from the project

**Comment by michel-slm** [comment]
> The version was deleted from the project

thank you!
