### ISSUE TITLE
version parsing

### ISSUE THREAD

**Issue by rderooy** [fedora-infra/anitya#1291]
Sorry if this has been answered before, I could not find a similar issue.

In some cases the upstream project decides to be creative and instead of using periods for the different parts of the version, they use a dash (-) or underscore (_) in the filename, git-tag or git-release.

For instance for openMSX https://release-monitoring.org/project/2555/

Anitya thinks the latest version is 0.11.0, because it is pointing to the unmaintained sourceforge URL as the project has transitioned to GitHub. So I tried to edit it to correct this.

But they use git tags and git releases with underscores in the version. e.g., https://github.com/openMSX/openMSX/releases

So when I let Anitya parse the version, it returns versions like "17_0" instead of 17.0. Is there any way to use something like a regex to do substitution?

**Comment by rderooy** [comment]
Used custom instead of github and that solved the issue for openMSX.

I found some similar issues that have been open for years.

**Comment by z3ntu** [comment]
I see for openMSX currently the version fetching doesn't work, I'd need something quite similar for desmume (should use github, not sourceforge but github has weird tags)

(This is also similar to https://github.com/fedora-infra/anitya/issues/1104)

**Comment by Zlopez** [comment]
I fixed the regex, it seems that Github is now generating links to sources by using some strange technique, because the links are not visible in page source, thus custom backend can't retrieve them using default regex

**Comment by travier** [comment]
We have a similar issue with https://release-monitoring.org/project/1684/. I haven't been able to fix it yet. CC @Justinzobel

**Comment by rderooy** [comment]
The openmsx version check indeed no longer works either. Not sure what broke. The last reported version is 18.0, while 19.1 is the current release.

**Comment by z3ntu** [comment]
FTR for desmume I've now switched to "custom" backend using a regex on the github releases page. Definitely not great, the attached assets would have been a better idea but github is loading those with js so unusable for the check with anitya. Oh well.

https://release-monitoring.org/project/12138/

**Comment by travier** [comment]
For libnl (https://release-monitoring.org/project/1684/), I've switched to the custom backend, using the JSON API url to get the releases (https://api.github.com/repos/thom311/libnl/releases) and a regex to match the tags: `libnl([\d]*)\_([\d]*)_([\d]*)`. I had to remove the "invalid" versions for this to work.

**Comment by rderooy** [comment]
I have updated the parsing for openmsx, such that it again is able to get the current versions. Unfortunately, I'm pretty sure getting the src package automatically will not work anyway, due to the naming convention used. e.g. `RELEASE_19_1.tar.gz`
