### ISSUE TITLE
Need to purge old versions for libdwarf

### ISSUE THREAD

**Issue by michel-slm** [fedora-infra/anitya#1307]
libdwarf recently adopted semantic versioning, which necessitates using epoch in Fedora.

I've updated the regex in https://release-monitoring.org/project/1597/ to only match the new versions, but the old YYYYMMDD versions need to be purged for upstream release monitoring to work, because all the new versions are showing as older than the old ones.

**Comment by Zlopez** [comment]
I deleted all the versions on the project and did a clean check for new versions. It should be OK now.
