### ISSUE TITLE
github backend version check fails: version_url empty

### ISSUE THREAD

**Issue by piotr1212** [fedora-infra/anitya#131]
version check fails for projects with github backend, see carbon-c-relay for example:
https://release-monitoring.org/project/6115/
When I do a version check, the url https://github.com//tags is checked instead of https://github.com/grobian/carbon-c-relay/tags

In github.py it seems that the variable "version_url" is used to build the url. This variable is never set, there is no no box where this could be filled in.

**Comment by pypingou** [comment]
So #134 fixes this, I'll try to cut a new release of anitya tonight when I get home.
