### ISSUE TITLE
search returns result twice

### ISSUE THREAD

**Issue by piotr1212** [fedora-infra/anitya#132]
When I search any project on release-monitoring.org it returns two identical results, see
https://release-monitoring.org/projects/search/?pattern=nodejs-onetime
or 
https://release-monitoring.org/projects/search/?pattern=carbon-c-relay
it should return only one result in both cases

**Comment by pypingou** [comment]
This was fixed in https://github.com/fedora-infra/anitya/pull/127 but has not been deployed yet

**Comment by pypingou** [comment]
This was fixed in https://github.com/fedora-infra/anitya/pull/127 but has not been deployed yet
