### ISSUE TITLE
projects->all: pager starts at wrong position for pages > 2

### ISSUE THREAD

**Issue by piotr1212** [fedora-infra/anitya#133]
When browsing projects on projects->all the pager start at a wrong position.

go to:
https://release-monitoring.org/projects/?page=3
and notice that it starts with andresriancho/w3af
When on https://release-monitoring.org/projects/?page=2 project andresriancho/w3af is somewhere in the middle of the page. I would expect that page=3 would start with App-DuckDuckGo.

For some reason page=2 starts at the correct position. problem occurs with pages above 2.

**Comment by pypingou** [comment]
Fix in the pull-request mentioned above, thanks for finding it, it was a nice bug :)
