### ISSUE TITLE
Are the versions returned by the API sorted?

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#1352]
Trying to obtain the versions via API, e.g. `$ curl -s https://release-monitoring.org/api/v2/versions/?project_id=4223` the versions appears to be sorted. Nevertheless, the API documentation does not say anything about sorting, so is the sorting given? Can my script rely on the sort order?

**Comment by Zlopez** [comment]
Yes, you can count on that, it's calling [this property](https://github.com/fedora-infra/anitya/blob/ec20b8fe3627aaf9070aae5ef3b2314d7e680383/anitya/db/models.py#L287=) of the `Project` database model. Take in consideration that the sorting is done based on the versioning scheme set on the project.

**Comment by voxik** [comment]
Would it be possible to clarify the documentation? Or somehow relate the DB API with the HTTP API?

**Comment by Zlopez** [comment]
I can add this information to docstring describing the API endpoint, which should also update this in the documentation.
