### ISSUE TITLE
No issue is filed for librime-1.7.3 for Fedora

### ISSUE THREAD

**Issue by cheese** [fedora-infra/anitya#1363]
Any thing wrong with checking of the current version in Fedora?

**Comment by Zlopez** [comment]
The version 1.7.3 was retrieved on `2021-08-05 23:05`, so it's possible that there was some issue with the-new-hotness at that time.

I did removed the version, did a new check and the bug is correctly created https://bugzilla.redhat.com/show_bug.cgi?id=2095236
