### ISSUE TITLE
Better source of information for PEAR, PECL, ...

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/anitya#137]
=> https://  (channel_name)  /rest/r/  (package name)   /allreleases.xml

Ex: https://pecl.php.net/rest/r/pecl_http/allreleases.xml

Works for
* pear.php.net
* pecl.php.net
* pear.horde.org
* etc... (all PEAR channels)

**Comment by ralphbean** [comment]
Nice!  Gnome projects have a similar thing (it's called the ``cache.json`` file).
