### ISSUE TITLE
cancel mapping on imagemagick~6 becuase I did a new mapping 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/anitya#1384]
please cancel test mapping (it was fedora) on https://release-monitoring.org/project/16253/ 
because I did a new mapping on https://release-monitoring.org/project/258035/ 
thank you

**Comment by Zlopez** [comment]
Done

**Comment by sergiomb2** [comment]
why  https://release-monitoring.org/project/258035/ was deleted ? or is disappeared ?

**Comment by Zlopez** [comment]
It was flagged as a duplicate, it usually means that admin will merge mappings from these two projects and deletes the newer one.
