### ISSUE TITLE
Add BitBucket backend

### ISSUE THREAD

**Issue by nocnokneo** [fedora-infra/anitya#141]
Example of a BitBucket releases/download page:
https://bitbucket.org/verateam/vera

**Comment by pypingou** [comment]
Thanks for the idea

It should be rather easy to do by taking the github backend as an example:
https://github.com/fedora-infra/anitya/blob/master/anitya/lib/backends/github.py
and then build the download page using the project name:
https://bitbucket.org/verateam/<project name>/downloads
ie: https://bitbucket.org/verateam/vera/downloads

I think the default regex should work just fine.

Is this something you would be interested in doing?

**Comment by nocnokneo** [comment]
It's something I'd be interested in but, realistically, I just don't have the time.
