### ISSUE TITLE
Need to reset nwipe version history

### ISSUE THREAD

**Issue by michel-slm** [fedora-infra/anitya#1411]
nwipe's github repo had two incorrect tags: .026 and .033 that have since been removed, but they show up in Anitya as the newest versions

https://release-monitoring.org/project/7711/
https://bugzilla.redhat.com/show_bug.cgi?id=2105640

Please help reset this so the maintainers actually get notified when the next release (presumably 0.35) is cut, thanks!

**Comment by Zlopez** [comment]
I removed them. They only could be retrieved again, if somebody added them to tags on the project. This could be solved by rather watching for releases instead of tags. It is not a default option, because not every project has releases and the name of the release is not always just version.
