### ISSUE TITLE
BZ bot caught in a loop

### ISSUE THREAD

**Issue by FaramosCZ** [fedora-infra/anitya#1419]
Hi,
Take a look at this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2090416

Single new upstream release. But the BZ bot 'upstream release monitoring' submits the same patch again and again, trying new scratch builds again and again ... spamming people in CC in the process.

I would expect the bot to try once and give up instead.

**Comment by Zlopez** [comment]
Migrated to the-new-hotness https://github.com/fedora-infra/the-new-hotness/issues/494
