### ISSUE TITLE
Broken link on project edit page

### ISSUE THREAD

**Issue by nocnokneo** [fedora-infra/anitya#142]
On `https://release-monitoring.org/project/<projectid>/edit` when using a `custom` backend, there is a typo:

`More information in the about#test-you-regex`

Should be:

`More information in the about#test-your-regex`

But can I suggest just putting the link as a [Learn more](about#test-your-regex) link right next to the **Regex** field label?

**Comment by pypingou** [comment]
Thanks for the report, I fixed the link but I can't quite fix the location as the place is determined for all backends and this link is specified in the custom backend itself.

The idea being that we reduce the backend-specific code in the template and code and use instead mechanism to offer the possibility to backends to add additional information. So the first item is fixed the second one can't really be I think.
