### ISSUE TITLE
Regexp for prerelease filters

### ISSUE THREAD

**Issue by brawer** [fedora-infra/anitya#1433]
Would it be possible to support regular expressions for detecting prereleases?

I was trying to set up release monitoring for https://github.com/google/s2geometry/tags but wasn’t able to configure prerelease detection to filter tags like [v0.10.0-2022.02.23.00](https://github.com/google/s2geometry/releases/tag/v0.10.0-2022.02.23.00).

**Comment by Zlopez** [comment]
Could you share the link to the project on release-monitoring?

Otherwise it should be easy, just add `-2` to pre-release filter field.

**Comment by brawer** [comment]
Thank you! Adding `-2` to the pre-release filter seems to have worked, see [project page on release-monitoring](https://release-monitoring.org/project/276354/).

**Comment by Zlopez** [comment]
In case of pre-release filter Anitya is looking for a matching string in version that is retrieved from upstream. Same is true for version filter.

I'm glad the issue is now solved.

**Comment by razzeee** [comment]
This would still be helpful, as I would like to filter for uneven minor versions for e.g.
