### ISSUE TITLE
Requesting deletion of mistyped variants of MonkeyType

### ISSUE THREAD

**Issue by michel-slm** [fedora-infra/anitya#1443]
These projects are incorrect and don't point to valid upstreams:

- [MMonkeyType](https://release-monitoring.org/project/279077/)
- [MonkeyTypee](https://release-monitoring.org/project/279066/)
- [monkeytypes](https://release-monitoring.org/project/278021/)

**Comment by Zlopez** [comment]
I deleted all of them, unfortunately it's hard to filter those automatically. These are created based on the new projects in PyPi and once the PyPi project will be deleted, these will be as well, but there are plenty of project like those in PyPi and I don't think this will be solved soon on PyPi side.
