### ISSUE TITLE
Refactor Backend.get_version

### ISSUE THREAD

**Issue by erolkskn** [fedora-infra/anitya#1453]
Hi maintainers,

As a possible refactor suggestion i have something in my mind. While i was developing new backends for anitya over the last two months, i noticed that almost every backend has the exact same `get_version` implementation. Exact number is out of the 31 backends 23 of them has the same implementation for `get_version` method. It's like this:

```python
@classmethod
    def get_version(cls, project):
        """Method called to retrieve the latest version of the projects
        provided, project that relies on the backend of this plugin.

        :arg Project project: a :class:`anitya.db.models.Project` object whose backend
            corresponds to the current plugin.
        :return: the latest version found upstream
        :return type: str
        :raise AnityaPluginException: a
            :class:`anitya.lib.exceptions.AnityaPluginException` exception
            when the version cannot be retrieved correctly

        """
        return cls.get_ordered_versions(project)[-1]
```

Why don't we move that implementation to `BaseBackend` class and remove duplication from 23 backends ? That would make source code 1150 lines lesser and avoid duplication.

I would love to hear your opinions about this.

**Comment by Zlopez** [comment]
I'm +1 on this, removing the duplicate code is always better.
