### ISSUE TITLE
sourceforge backend not working !

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/anitya#146]
Hi , seems that sf.net is not working at all , I can't configure 
https://release-monitoring.org/project/6221/
regexp is wrong 
also can't configure xine-ui from xine project 
https://release-monitoring.org/project/5561/

in edit mode with Sourceforge backend doesn't allow we edit regexp entry which is not correct the correct one could be 
http://sourceforge.net/projects/smb4k/(?:[-_]?(?:minsrc|src|source|files)).*?\.(?:tar|t[bglx]z|tbz2|zip)

**Comment by pypingou** [comment]
If you have your own regex, you can use the custom backend :)

**Comment by sergiomb2** [comment]
not really , I try it also doesn't worked . but was other issue because when I tried the button check new version, anyta doesn't assume the new confs edited ... , may be this is the bug . 
Because, If we check now the same project https://release-monitoring.org/project/6221/ , it says  detect last version correctly , some thing happened .

**Comment by pypingou** [comment]
https://release-monitoring.org/project/5561/ is this better for you?

**Comment by sergiomb2** [comment]
yes , xine-ui-0.99.9.tar.xz is the lasted version :)

**Comment by sergiomb2** [comment]
xine-lib and xine-plugin also have been updated correctly , I think 
https://release-monitoring.org/project/5543/
https://release-monitoring.org/project/5566/
we also have gxine 
https://release-monitoring.org/project/5558/

But Project name have same name , I tried edit https://release-monitoring.org/project/5566/edit and modified the name for xine-plugin and begins to look rss with  /projects/xine-plugin when should be /projects/xine I try revert back the project name to xine but now says : already exist a project with that name (no wonder ) .

https://release-monitoring.org/project/5543/edit we got 
Project name: xine 
Sourceforge name: xine-lib 
shouldn't be the opposite , sf name is xine , project name is xine-lib and in this case we are looking for new releases of xine-lib

**Comment by pypingou** [comment]
> shouldn't be the opposite , sf name is xine , project name is xine-lib and in this case we are looking for new releases of xine-lib 

This is what the pull-request linked to above is doing :)

**Comment by sergiomb2** [comment]
when it fixed on production (release-monitoring.org) ?

**Comment by pypingou** [comment]
This is now live btw :)

**Comment by sergiomb2** [comment]
Seems that is working : 
https://release-monitoring.org/projects/search/?pattern=xine*

Thanks
