### ISSUE TITLE
expose "additional" support for setting project properties only available in `POST /api/v2/versions/` in `POST /api/v2/projects/`

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/anitya#1463]
It looks like it is currently impossible to create a project *and* set, for example, a `pre_release_filter` with one POST request, since this argument is not accepted when *creating* a project, only very counter-intuitively by *editing* it by sending a POST request to the `api/v2/versions/` endpoint.

The following properties are missing from the `POST /api/v2/projects/` endpoint:

- `version_scheme`
- `version_pattern`
- `pre_release_filter`
- `version_filter`
- `releases_only`

I don't know why these are missing from the "create a new project" endpoint, since they are present in both the Web UI for creating a new project, *and* in the "edit an existing project" functionality that's hidden behind the `api/v2/versions/` endpoint.

I'd like to create projects via the API, but I need to set `version_scheme="Semantic"` and `version_filter="alpha;beta;rc;pre"` when creating them, otherwise I might need release-monitoring.org administrator help to clean up some versions that are recognised incorrectly, and it looks like I can only do that with the Web UI right now.

---

Side note: I dug through the source code of those endpoints already to figure this out, and it looks like adding these settings to the `POST /api/v2/projects/` endpoint should be as simple as adding the new fields to the accepted arguments and to the `utilities.create_project()` call, which is the same in both endpoints. If you want, I can submit a PR for this. :)

**Comment by Zlopez** [comment]
The reason for those properties missing from `POST /api/v2/projects/` endpoint is simple. These were introduced after the endpoint was created and it was never updated.
The `api/v2/versions/` was created much later, and this is why it contains these changes.

You are right adding those should be simple enough, just allowing new optional fields to the endpoint.
