### ISSUE TITLE
Can't create projects via API

### ISSUE THREAD

**Issue by cheese1** [fedora-infra/anitya#1464]
i try to create new projects via api but this does not seem to work.

i tried:
```
 curl --request POST --header "Content-Type: application/json" --header "Authorization: token XYZ" --data '{
    "backend": "custom",
    "homepage": "https://www.horde.org",
    "name": "Horde_Argv",
    "ecosystem": "https://www.horde.org",
    "version_url": "https://pear.horde.org/rest/r/horde_argv/latest.txt" }' https://release-monitoring.org/api/v2/projects/
{"message":{"backend":"Missing data for required field.","homepage":"Missing data for required field.","name":"Missing data for required field."}}
```

i tried with the example from https://release-monitoring.org/static/docs/api.html
which did not work either:
```
curl --request POST --header "Content-Type: application/json" --header "Authorization: token XYZ" --data '{"backend": "custom", "homepage": "https://example.com/test", "name": "test_project", "version_prefix": "release-"}' https://release-monitoring.org/api/v2/projects/
{"message":{"backend":"Missing data for required field.","homepage":"Missing data for required field.","name":"Missing data for required field."}}
```
besides: is there any test-anitya, where i should/could test? i dont want to disturb production-systems.

**Comment by Zlopez** [comment]
The test anitya instance is here https://stg.release-monitoring.org, you can do anything you want on it.

Regarding the issue with the project creation, I need to check the endpoint code more closely. I don't see anything wrong in the code at first glance or with the request you are sending. It looks like a valid JSON to me, but the endpoint doesn't recognize the required fields.
