### ISSUE TITLE
[RFE] add new distro/repo RussianFedora

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-infra/anitya#148]
As Admin and packager in RF we want to get notifications about new releases. We provide chromium, Skype and much more pkgs. We are going to provide ffmpeg, MPV and gstreamer* which now in rpmfusion, but they uses outdated infra and doesn't support not released Fedora versions. So we have broken ffmpeg and gstreamer* and outdated MPV.

I'd want to have notifications about new releases to avoid this issues.

We have koji and redmine in our infra.

**Comment by ralphbean** [comment]
I think you can do this yourself in the web interface.  Just try mapping a package with RussianFedora as the distro and see if it lets you do so.

**Comment by pypingou** [comment]
That is true, to add a distro just map a package to it.

As admin we can rename and delete distro if needed though.

**Comment by ignatenkobrain** [comment]
I've added mapping, but how I can get notifications about new releases? as bot does for fedora - it's creating bugs in RHBZ.

**Comment by ralphbean** [comment]
Hm.  We probably need to add a new rule to https://github.com/fedora-infra/fmn.rules that will let you filter for all anitya messages related to a ``distro`` that you specify.  With that, you could build a filter for all anitya messages having to do with RussianFedora.

**Comment by pypingou** [comment]
> I've added mapping, but how I can get notifications about new releases? as bot does for fedora - it's creating bugs in RHBZ.

Anitya/release-monitoring.org has its own fedmsg bus that announces new releases. So you could listen to the bus, check if the new release announced concerns RussianFedora and act when it does.
This is essentially what FMN does for sending notifications.
After it depends if you are looking for a email/irc message or a way to build tool around release-monitoring.org
