### ISSUE TITLE
Add a link to the project in bugzilla bugs

### ISSUE THREAD

**Issue by xosevp** [fedora-infra/anitya#149]
Hi.

Could you add a new line with the "anitya URL" to the bugs opened by anitya ?

Something like:
Latest upstream release: x.y.z
Current version/release in rawhide: a.b.c
URL: http://www.url.com/test
anitya: https://release-monitoring.org/project/XXXX/   <<<<------ this.

-thank you-

**Comment by pypingou** [comment]
cc'ing @ralphbean as this is a ticket for fedora-infra/the-new-hotness but it is definitely doable :)

**Comment by ralphbean** [comment]
Yeah, this should be easy to do.  The code change needs to go into https://github.com/fedora-infra/the-new-hotness
