### ISSUE TITLE
Link for RPM Fusion

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1498]
For example:
https://release-monitoring.org/project/241533/

**Comment by romulasry** [comment]
https://admin.rpmfusion.org/pkgdb/packages/

**Comment by Zlopez** [comment]
This needs to be solved on the distribution level in Anitya, there needs to be a new distribution called RPM-Fusion, because this is not a package in Fedora repo itself, and then we can add new link mapping to configuration.

**Comment by romulasry** [comment]
There is rpm fusion here: https://release-monitoring.org/distro/RPM%20Fusion/ that won't work?

**Comment by Zlopez** [comment]
The link needs to be configured first in Anitya configuration https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/release-monitoring/templates/anitya.toml#_72. Till then the link isn't working. I will add it.

**Comment by Zlopez** [comment]
It needed few retries, but the link is now working and it's deployed on production.
