### ISSUE TITLE
Wrong sourceforge version number

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/anitya#150]
I haven't looked into the details, but there was a bug filed downstream for this:  https://bugzilla.redhat.com/show_bug.cgi?id=1219091  From that ticket:

> The upstream release monitoring tool, I don't know exactly, which component that is, does not correctly identify the latest upstream version for one of my packages.  https://release-monitoring.org/project/6239/
> 
> The version 4703 is clearly not available from the project's website, as can be seen from http://sourceforge.net/projects/texstudio/files/texstudio/

Is this related to the recent sourceforge changes that went out?

**Comment by pypingou** [comment]
Replied on the bugzilla ticket.

**Comment by pypingou** [comment]
BZ ticket fixed
