### ISSUE TITLE
hdf5 and stability

### ISSUE THREAD

**Issue by jeremysanders** [fedora-infra/anitya#1518]
Looking at HDF5, it seems odd numbered releases are unstable and experimental:
https://www.hdfgroup.org/2021/12/hdf5-1-13-0-introducing-experimental-releases/

However, anitya returns the latest experimental release. Because of the large changes, other projects such as h5py are incompatible with experimental releases, see https://github.com/h5py/h5py/issues/2129

Is it possible to fix anitya to only return stable releases?

**Comment by Zlopez** [comment]
We don't currently have any way to mark even/odd numbered releases as pre-release. This is already reported in https://github.com/fedora-infra/anitya/issues/1088
