### ISSUE TITLE
Static web files in PyPI package broken

### ISSUE THREAD

**Issue by der-eismann** [fedora-infra/anitya#1529]
When I install anitya via PyPI I get a lot of 404s for the missing bootstrap files:
```
[werkzeug INFO] 10.0.2.100 - - [03/Jan/2023 15:00:00] "GET /static/bootstrap/css/bootstrap.css HTTP/1.1" 404 -
[werkzeug INFO] 10.0.2.100 - - [03/Jan/2023 15:00:00] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 404 -
```

The reason for this is that the folder name for bootstrap is wrong:
```
# ls -la /usr/lib/python3.10/site-packages/anitya/static
total 12
drwxr-xr-x    1 root     root           132 Jan  3 14:59 .
drwxr-xr-x    1 root     root           372 Jan  3 14:59 ..
drwxr-xr-x    1 root     root            20 Jan  3 14:59 bootstrap-3.3.4-fedora
drwxr-xr-x    1 root     root           264 Jan  3 14:59 css
drwxr-xr-x    1 root     root           640 Jan  3 14:59 docs
-rw-r--r--    1 root     root          4683 Jan  3 14:59 google_logo.png
drwxr-xr-x    1 root     root            22 Jan  3 14:59 ico
drwxr-xr-x    1 root     root           136 Jan  3 14:59 img
drwxr-xr-x    1 root     root           156 Jan  3 14:59 js
-rw-r--r--    1 root     root          2970 Jan  3 14:59 yahoo_logo.png
```

When I create a symlink from `bootstrap-3.3.4-fedora` to `bootstrap`, the 404s are gone and the web UI is looking nice again.

**Comment by Zlopez** [comment]
This will be probably fixed when https://github.com/fedora-infra/anitya/pull/1514 will be released. The javascript and CSS dependencies management is now completely changed.

Unfortunately this introduces some manual steps in deployment, but everything is [documented](https://anitya.readthedocs.io/en/master/admin-guide.html#installation).

**Comment by Zlopez** [comment]
With the release of 1.7.0, this issue should be solved.
