### ISSUE TITLE
version filter does not seem to work

### ISSUE THREAD

**Issue by nekopsykose** [fedora-infra/anitya#1537]
example: https://release-monitoring.org/project/16950/

adding anything to version filter, including an exact version (20190519.1), does not filter it from the latest versions

**Comment by nekopsykose** [comment]
this used to work and seems to have stopped sometime recently, and the result is the versions that were being filtered now show up as the latest version for seemingly some monitored packages (hence generating pings downstream that a new version is available, to some previously-filtered-out one)

**Comment by Zlopez** [comment]
The filter never worked that way. It just filters out versions that are found upstream. Everything that is already in Anitya is not removed. Only admin can remove versions.

I removed the versions for you and tested it out that they will not be obtained again. At least until the filter is changed.

**Comment by nekopsykose** [comment]
> Everything that is already in Anitya is not removed. Only admin can remove versions.  

ah, okay, that makes sense then. thanks!
