### ISSUE TITLE
Please hlep fix the Ruby project

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#1539]
It seems that somebody have changed the Ruby project:

https://release-monitoring.org/project/4223/

Last time I fixed the URL, it was pointing to:

https://cache.ruby-lang.org/pub/ruby/index.txt

With some additional RegExp. Now somebody changed it to RubyGems which is completely wrong. So there are two things:

1) It would be nice if there was some kind of history, so I would know when the change happened and especially who did that.
2) Is is possible to retrieve the previous regexp somehwere from the database, update it and make sure there are reported correct versions?

**Comment by voxik** [comment]
>     make sure there are reported correct versions?

I think that once the URL is fixed, all the entries reported after `2023-01-30 08:34`  should be removed.

**Comment by Zlopez** [comment]
The changes are all logged in datagrepper, you can look at them using this [URL](https://apps.fedoraproject.org/datagrepper/v2/search?rows_per_page=1&delta=127800&topic=org.release-monitoring.prod.anitya.project.edit)

**Comment by Zlopez** [comment]
And [here](https://apps.fedoraproject.org/datagrepper/v2/id?id=1ee0b0d5-d75b-414f-a56d-3f6043968178&is_raw=true&size=extra-large) you can see what was changed.

I changed it back and removed the versions.

**Comment by voxik** [comment]
> The changes are all logged in datagrepper, you can look at them using this [URL](https://apps.fedoraproject.org/datagrepper/v2/search?rows_per_page=1&delta=127800&topic=org.release-monitoring.prod.anitya.project.edit)

Oh, nice!


> And [here](https://apps.fedoraproject.org/datagrepper/v2/id?id=1ee0b0d5-d75b-414f-a56d-3f6043968178&is_raw=true&size=extra-large) you can see what was changed.
> 
> I changed it back and removed the versions.


Thx a lot!
