### ISSUE TITLE
Anity does not catch release of LuaDBI at Google code

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/anitya#154]
Anity does not catch releases of LuaDBI at Google code, see: https://release-monitoring.org/project/6299/ - and individual regular expressions are unfortunately not possible without custom backend?

**Comment by pypingou** [comment]
Yes you will have to use a custom regex, but you can use the default one you see in the error message as well as the url and just tweak it ;-)

**Comment by pypingou** [comment]
I fixed it for you :)

**Comment by robert-scheck** [comment]
Thank you!
