### ISSUE TITLE
Refer to history in Anitya UI

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#1541]
As was pointed [here](https://github.com/fedora-infra/anitya/issues/1539#issuecomment-1412001502), there is a way to access project history. But it would be very convenient, if Anitya UI could provide link to that URL, so it would be easier discoverable

**Comment by Zlopez** [comment]
That would be nice to have, but we should at least have it documented somewhere. I think it's now documented only for the hotness.

**Comment by Zlopez** [comment]
Found out there is already issue opened for that #918
