### ISSUE TITLE
appstream-glib is outdated

### ISSUE THREAD

**Issue by JakobDev** [fedora-infra/anitya#1553]
According to [release-monitoring.org](https://release-monitoring.org/project/14018/), the last version of appstream-glib is 0.7.18. But [on the Repo](https://github.com/hughsie/appstream-glib/tags), the newest version is 0.8.2.

**Comment by romulasry** [comment]
Alright, I fixed it: https://release-monitoring.org/project/14018/

**Comment by Zlopez** [comment]
Ok, closing the issue
