### ISSUE TITLE
Fixing broken regex does not remove wrong version numbers

### ISSUE THREAD

**Issue by kkofler** [fedora-infra/anitya#156]
I have just fixed the regex for KDevelop to not mistake the `1999/` in `<html xmlns="http://www.w3.org/1999/xhtml">` for a version number. But instead of removing the false version number, it complains in the log that:
> Something strange occured, we found that this project has released a version "4.7.1" while we had the 
> latest version at "1999"

and the nonsensical version number is still there. There is also no way to delete wrong versions manually.

**Comment by pypingou** [comment]
Admins can remove wrong version I will do this.

(Note: How should anitya know which version retrieved was wrong?)

**Comment by pypingou** [comment]
Done

**Comment by ralphbean** [comment]
perhaps we should add flagging of versions to the feature/flag branch?

**Comment by pypingou** [comment]
@ralphbean yes +1
