### ISSUE TITLE
Latest GnuCash version not detected

### ISSUE THREAD

**Issue by janvlug** [fedora-infra/anitya#1563]
[This page](https://release-monitoring.org/project/1205/) shows that the latest version of GnuCash is 4.901.
However, the latest version according to the [monitored page](https://github.com/Gnucash/gnucash/tags) is 5.0.

**Comment by Zlopez** [comment]
The issue is in the incorrect setup of the project, somebody added `.` to version filter, which filtered out literally every version. I edited the project and fixed it. On top of that I cleared few bogus versions from history and added filter for that.
