### ISSUE TITLE
Xfce core components with odd minor version numbers are not flagged pre-release

### ISSUE THREAD

**Issue by Tamaranch** [fedora-infra/anitya#1564]
Xfce core components are those of the `xfce` group, i.e. those whose version check url contains `/xfce/` (instead of `/apps/`, `/panel-plugins/`, etc.)
For example libxfce4ui: https://release-monitoring.org/project/232000/
4.18.x are stable releases, 4.19.x are dev releases.
4.17.x were correctly flagged pre-release though.

**Comment by Tamaranch** [comment]
Tumbler 4.19.0 was correctly flagged : https://release-monitoring.org/project/5014/

**Comment by Zlopez** [comment]
The Anitya currently doesn't have any way to mark odd/even releases as pre-release (it's hard to detect automatically, which project is doing this). Only way to do that right now is to add the version to pre-release filter, which is what is happening in case of Tumbler.

We already have a ticket opened for even/odd pre-release filter https://github.com/fedora-infra/anitya/issues/1088, so I'm closing this as duplicate.

**Comment by Tamaranch** [comment]
Thanks. I just created a fedora account to fix that myself :)
