### ISSUE TITLE
Invalid regular expression when checking for new versions

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#1569]
Looking at the release-monioring.org logs there are plenty of projects that are failing with `invalid regular expression`.

I checked the [dillo](https://release-monitoring.org/project/438/) project and tested the regex (it's using default) in https://www.debuggex.com/ and it was valid.

I need to investigate this a little more to find what is causing this. My suspicion is that the empty string is used instead of default regex, when the regex is not filled.

**Comment by hiteshbedre** [comment]
@Zlopez do you know where this regex is implemented? and what are its possible sample that should match and not to match?

**Comment by Zlopez** [comment]
The default regex is defined in [config](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/release-monitoring/templates/anitya.toml#_54) inside ansible repository for fedora infra. It just replaces the `%(name)` with the actual name of the project. You can see the final regex on each project, when you edit it.

I need to check how it is used in code, but the best start is the `check_project_release` function in [utilities.py](https://github.com/fedora-infra/anitya/blob/master/anitya/lib/utilities.py#L60).

**Comment by Zlopez** [comment]
I need to look at this as soon as possible, because it's affecting plenty of projects.

**Comment by romulasry** [comment]
Same problem here: https://release-monitoring.org/project/8548/

**Comment by xosevp** [comment]
> I need to look at this as soon as possible, because it's affecting **_plenty_** of projects.

It is happening in **ALL** projects using "Default regex"

**Comment by xosevp** [comment]
It can be tested with "squid": https://release-monitoring.org/project/4880/edit

With **Default regex**:
```
squid(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_\s]+?)(?i)(?:[-_](?:minsrc|src|source|asc|release))?\.(?:tar|t[bglx]z|tbz2|zip)
```
it shows an error:
```
ERROR: "Error when checking for new version: squid: invalid regular expression"
```

Adding `squid-(.*?)\.tar\.gz`   to **"Regex"  box**, it works flawlessly.

**Comment by ppisar** [comment]
The error message comes probable from anitya/lib/backends/__init__.py:get_versions_by_regex_for_text() when list(set(re.findall(regex, text))) raises an exception.

Compiling the regular expression with pcre2test tool passes. However, compiling it with Python 3.11.3's re.findall() raises:

~~~~
  File "/usr/lib64/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 52
~~~~

Character at offset 52 is indeed flag for case insensitivity "(?i)" . Removing that from the expression makes Python happy. Moving it at the beginning "(?i)squid..." too.

**Comment by ppisar** [comment]
This issue was fixed 4 years ago in 1beb74df153f1405600518d803f0e05dd872a635 commit:

~~~~
commit 1beb74df153f1405600518d803f0e05dd872a635
Author: Michal Konečný <mkonecny@redhat.com>
Date:   Thu Oct 4 15:48:13 2018 +0200

    Remove deprecation warnings

diff --git a/anitya/config.py b/anitya/config.py
index 92bacda..470b346 100644
--- a/anitya/config.py
+++ b/anitya/config.py
@@ -93,7 +93,7 @@ DEFAULTS = dict(
     SOCIAL_AUTH_LOGIN_REDIRECT_URL='/',
     SOCIAL_AUTH_LOGIN_ERROR_URL='/login-error/',
     LIBRARIESIO_PLATFORM_WHITELIST=[],
-    DEFAULT_REGEX='%(name)s(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_\s]+?)(?i)(?:[-_]'\
+    DEFAULT_REGEX='(?i)%(name)s(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_\s]+?)(?:[-_]'\
                   '(?:minsrc|src|source|asc|release))?\.(?:tar|t[bglx]z|tbz2|zip)',
     # Token for GitHub API
     GITHUB_ACCESS_TOKEN=None,
~~~~

Doesn't the Fedora instance have an old code, or configuration? Or maybe the default expression was stored into a database when creating the project (e.g. squid) and since then it's always retrieved from there?

**Comment by xosevp** [comment]
> This issue was fixed 4 years ago in [1beb74d](https://github.com/fedora-infra/anitya/commit/1beb74df153f1405600518d803f0e05dd872a635) commit:

weird!
```
> -    DEFAULT_REGEX='%(name)s(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_\s]+?)(?i)(?:[-_]'\
> +    DEFAULT_REGEX='(?i)%(name)s(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_\s]+?)(?:[-_]'\
```
It works, and also removing the leading "(?i)"

> Doesn't the Fedora instance have an old code, or configuration? Or maybe the default expression was stored into a database when creating the project (e.g. squid) and since then it's always retrieved from there?

new projects are created with the wrong regex.

**Comment by ppisar** [comment]
Because old projects fail too and the web page claims it's running the latest version released 2 weeks ago, I conclude the production instance has DEFAULT_REGEX overridden somewhere in a local configuration file.

**Comment by michal-josef-spacek** [comment]
**This issue is critical for me.**

One of the non-sense examples of consequences:
I created a new monitoring item (SNMP_Session, id: 343886), which is affected by this issue. After some days the item was deleted. I am periodically looking into this issue and checking the fix. This means that I know that SNMP_Session item was removed. Without this activity user doesn't know that item was deleted.

**Comment by Zlopez** [comment]
Sorry for the late response, I will start working on this this week.

**Comment by Zlopez** [comment]
This should be fixed now with https://pagure.io/fedora-infra/ansible/pull-request/1437

**Comment by xosevp** [comment]
> Hi, is this fix already deployed? 

Yes, and it's working flawlessly.

>The release monitoring failed to fetch version info for mysql-connector-java today too[1]. The version check url seems correct, and the monitoring worked a year ago.
> 
> [1] https://release-monitoring.org/project/2038/

"Project name" is mysql-connector-**java** , and upstream is mysql-connector-**j**. Fixed!.

**Comment by zmiklank** [comment]
@xosevp Thanks! :)
