### ISSUE TITLE
github: add field to add prefix

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-infra/anitya#158]
some projects uses not plain tags like `0.1.2`. They using:
* `v0.1.2`
* `junit-0.1.2`

I think we can add special field in anitya to have this prefix.

**Comment by pypingou** [comment]
So the ``v`` in ``v0.1.2`` is not a problem as we already taught the-new-hotness to ignore them. For ``junit`` though it is an idea.

**Comment by cicku** [comment]
Examples like junit are horrible, you should advise upstream changing the tag name.

**Comment by ignatenkobrain** [comment]
@cicku I can't tell this to many opensource projects. And I will not.

**Comment by cicku** [comment]
Yeah, then whatever. You could still track version from github api.

**Comment by pypingou** [comment]
And we're back to the reason this ticket was opened in the first place @cicku :)
