### ISSUE TITLE
add stable_version as output in version API

### ISSUE THREAD

**Issue by Lex-2008** [fedora-infra/anitya#1581]
Hi! :wave:

I wonder if it would be ok to show "stable_version" in response to [versions API][v]. I found this PR: #1561 which added it to _projects_ API, so I assume that this should be as easy as just adding one extra line around [this line in `api_v2.py`][h] and fixing the tests.

Can I create a PR for this?

[v]: https://release-monitoring.org/static/docs/api.html#get--api-v2-versions-
[h]: https://github.com/fedora-infra/anitya/blob/master/anitya/api_v2.py#L593

**Comment by Zlopez** [comment]
@Lex-2008 Feel free to create a PR for it, that would be a nice improvement.

**Comment by sopyb** [comment]
I'd like to work on this issue.

**Comment by agaSiddhi** [comment]
Hey @Zlopez , I would like to work on this issue, in case if its still relevant.

**Comment by Zlopez** [comment]
@agaSiddhi Hi, thanks for your interest in Anitya project. I checked the API and it seems that this is already done as part of other work I did in the past. Feel free to look at other issues. But this one could be closed.
