### ISSUE TITLE
allow stripping a suffix from a detected version string

### ISSUE THREAD

**Issue by sharkcz** [fedora-infra/anitya#1584]
I have a project monitored by anitya (https://release-monitoring.org/project/4995/) that uses a Debian version string with the `.orig` suffix in the upstream release version (eg. `1.30.orig`). But the actual version is just `1.30`. There is already a way to strip a prefix, so could it expanded to strip a suffix as well?

**Comment by Zlopez** [comment]
Duplicate of https://github.com/fedora-infra/anitya/issues/259
