### ISSUE TITLE
Document version pattern for calendar versioning

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#1604]
It seems that `version pattern` field documentation is missing in user guide. It would be good to add it, so people know how to fill this field correctly.

**Comment by Zlopez** [comment]
@skywalkersPadawan This is still open and it should be added under version scheme in this document https://github.com/fedora-infra/anitya/blob/master/docs/user-guide.rst#version-scheme

**Comment by robel16** [comment]
Hello, @Zlopez I'm an Outreachy applicant and I want to work on this task if it's still open can you assign me?

**Comment by Zlopez** [comment]
@robel16 There is already a PR open for this issue and I'm working with author to get it polished.
