### ISSUE TITLE
Version detected before it's published?

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/anitya#1609]
I have a strange problem with a project with Gitlab backend: siril.
A couple of days ago Anitya detected a new pre-release of siril, 1.2.0-rc1:
https://release-monitoring.org/project/234784/

yet, there's no sign of that tag in the backend URL:
https://gitlab.com/api/v4/projects/free-astro%2Fsiril/repository/tags
https://gitlab.com/free-astro/siril/-/tags

This is not the first time I experience such odd behavior and I can't understand where those versions are fetched from days before they are really published...

**Comment by Zlopez** [comment]
Anitya just takes information from the GitLab repository and in this case it seems that somebody created the tag and then deleted it from the repository https://gitlab.com/free-astro/siril/activity
