### ISSUE TITLE
octave forge incorrect versions

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/anitya#161]
The following incorrect upstream monitoring bugs were filed or updated for octave forge packages using the main octave release version for the version number:

https://bugzilla.redhat.com/buglist.cgi?quicksearch=%3Aoctave%20upstream%20available

**Comment by pypingou** [comment]
The source of this behavior is: https://release-monitoring.org/project/2529/

Feel free to adjust it :)

**Comment by opoplawski** [comment]
It basically needs to be deleted and replaced by individual projects.  I don't seem to be able to delete it.

**Comment by pypingou** [comment]
Ok we have cleaned this situation so I guess we can close this ticket :)
