### ISSUE TITLE
Sort search by a "clickable" 'name' 'homepage' 'backend' 'latest version'?

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/anitya#1627]
See:
https://release-monitoring.org/projects/search/?pattern=open

So you can sort ascending/descending with the above items?

**Comment by Zlopez** [comment]
That would be a good addition to Anitya.

**Comment by Freedisch** [comment]
I think, we could have a small up-and-down icon for each section to trigger the sort   
![up-and-down-arrow](https://github.com/fedora-infra/anitya/assets/82499435/f7171b08-3180-4a54-840f-3cca4b9ab5a3)

**Comment by Zlopez** [comment]
That is the idea of how this should look, just adding small up-and-down icon for each section.
