### ISSUE TITLE
release-monitoring.org appears to be down

### ISSUE THREAD

**Issue by goproslowyo** [fedora-infra/anitya#1652]
[release-monitoring.org](https://release-monitoring.org/) appears to be offline/down :frowning_face:

**Comment by Zlopez** [comment]
Sorry for this, but the release-monitoring.org experienced DDoS attack yesterday, so we took it down and will try to re-enable it again today.

**Comment by Zlopez** [comment]
release-monitoring.org is now back up

**Comment by goproslowyo** [comment]
@Zlopez is it being DDoS'd again? Seems down. Maybe consider putting it behind CloudFlare?

**Comment by Zlopez** [comment]
I don't know about any DDoS, maybe there was just some work in the datacenter or in our network.

**Comment by goproslowyo** [comment]
No worries, was probably transient -- thanks for running the service!
