### ISSUE TITLE
webgui does not provide functionality to remove projects or mappings

### ISSUE THREAD

**Issue by ingvagabund** [fedora-infra/anitya#166]
Hi,

is there a way to remove project or mappings that I have created? Is there a plan to add such functionality?

Thanks
Jan

**Comment by ingvagabund** [comment]
Here [1], I would like to remove item with rawhide distribution.
[1] https://release-monitoring.org/project/6528/

**Comment by pypingou** [comment]
You can ask here and there is a feature in progress to be able to "flag" a project for such requests

**Comment by pypingou** [comment]
Removed, thanks!

**Comment by ingvagabund** [comment]
Thanks :)

**Comment by pypingou** [comment]
Any time :)
