### ISSUE TITLE
Upstream release monitoring doesn't create bugs when a new version is released

### ISSUE THREAD

**Issue by ljavorsk** [fedora-infra/anitya#1661]
Upstream release monitoring was set up for minizip-ng package [1] almost a year ago, and I just found out that it doesn't report any bugs when a new release is released.

It does know about the release, but it doesn't report it.

[1] https://release-monitoring.org/project/301509/

**Comment by Zlopez** [comment]
There is a fedora mapping missing, in that case release-monitoring doesn't even know that this project is in Fedora. I added the mapping and re-retrieved the latest version. And here is the [bug](https://bugzilla.redhat.com/show_bug.cgi?id=2235710).

**Comment by Zlopez** [comment]
You can see the latest output from release monitoring (the-new-hotness) in https://packages.fedoraproject.org/pkgs/minizip-ng/minizip-ng/ as recent activity.

**Comment by ljavorsk** [comment]
Thank you @Zlopez
