### ISSUE TITLE
Remove distribution mapping

### ISSUE THREAD

**Issue by jamesjer** [fedora-infra/anitya#1662]
I have flagged https://release-monitoring.org/project/63/ multiple times over the last 6 weeks, asking to have the Fedora mapping removed.  The Fedora package now contains what release-monitoring.org calls commons-configuration2, not commons-configuration.  I cannot add the correct mapping because of the existing mapping.  There has been no action.  Is anybody monitoring the flags?

Even better: give us packagers a button to remove a distribution mapping.  We could use this when retiring a package, or switching a package to a new upstream.  We can add arbitrary mappings, and arbitrarily edit existing projects, so I fail to see what is being protected by not giving us such a capability.

**Comment by Zlopez** [comment]
I'm sorry for this, I'm trying to check the flags from time to time. There currently isn't any system to notify admins about new flag being filled in.

I removed the mapping and the project as well, as it doesn't seems to be working correctly and there is already another one that does the same.

**Comment by jamesjer** [comment]
Thank you.  I'm sure you have lots of more important work to do, which is exactly why a button to let me remove mappings myself is such a great idea. :-)  Be well.
