### ISSUE TITLE
Inability to query API for packages mapped to different name.

### ISSUE THREAD

**Issue by Zopolis4** [fedora-infra/anitya#1683]
For example, if I query the API for `acpica`, I get [no result](https://release-monitoring.org/api/v2/projects/?name=acpica).

This is because it is listed under [acpia-tools](https://release-monitoring.org/project/18/).

However, a number of distributions have it mapped to just `acpica`, including `Chromebrew`. 

If I know that `Chromebrew` maps it to `acpica`, would it not make sense to be able to submit this information in my query, and get the desired result?

i.e. something like `https://release-monitoring.org/api/v2/projects/?name=acpica&mapping=Chromebrew` would search every package tracked by Chromebrew for the `acpica` mapping, which would return `acpia-tools`.

**Comment by Zlopez** [comment]
If you want to find it by mapping in specific distribution, you can use `https://release-monitoring.org/api/v2/packages/?name=<package_name>`.
The `api/v2/projects` is more oriented to search by project's atributes.
