### ISSUE TITLE
VLC: release-monitoring.org should check gitlab repo and not github

### ISSUE THREAD

**Issue by MatMaul** [fedora-infra/anitya#1688]
Currently release-monitoring.org is parsing https://github.com/videolan/vlc/tags to find the releases but it seems to not be updated anymore.

https://code.videolan.org/videolan/vlc/-/tags should be used instead.

I am happy to send a PR myself but I can't find easily where are stored the project descriptors for release-monitoring.org.

**Comment by MatMaul** [comment]
Addendum: we may want to switch to parse https://get.videolan.org/vlc/ instead.

I often notice that a tag is created, and then a week or more pass before the actual release is done and available on get.videolan.org. I think this is because all platforms are build and tested after the tag.

**Comment by Zlopez** [comment]
The [vlc project](https://release-monitoring.org/project/6504/) could be edited directly on the release-monitoring.org, you just need to login.

**Comment by Zlopez** [comment]
I fixed it for you and it's now working with `folder` backend.

**Comment by MatMaul** [comment]
Thanks !
