### ISSUE TITLE
Chromium version check URL is no longer valid

### ISSUE THREAD

**Issue by afeddersen** [fedora-infra/anitya#1711]
[The chromium-stable project](https://release-monitoring.org/project/13344/) is using a version check URL (website) that has been turned down. 

non-working version check URL: https://omahaproxy.appspot.com/all.json?os=linux;channel=stable

```
*** Service Permanently Offline ***

OmahaProxy has been turned down.
Please migrate to <https://chromiumdash.appspot.com>.
```

This is the new Chromium site:  https://chromiumdash.appspot.com/releases?platform=Linux

I'll see if I can figure out the correct URL and open a PR or suggest a change in this issue.

**Comment by ajayk** [comment]
I have updated to https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions/all/releases

**Comment by afeddersen** [comment]
Thank you!
