### ISSUE TITLE
Error: There's already an account associated with your email, authenticate with openid

### ISSUE THREAD

**Issue by PureTryOut** [fedora-infra/anitya#1713]
It isn't a bug, but I don't know where else to ask for support either. The error in the title is what I see when I try to login to https://release-monitoring.org using a Launchpad account. I guess I logged into Anitya before with some other OpenID provider, but I have no clue which one that would be and Anitya is clearly not going to tell me.
So now I'm locked out with no way to recover it seems. It would be great if Anitya could tell me what OpenID provider was used to login to that email address, but even better if somebody could tell me directly which provider was used to login to my email :sweat_smile:  I rather not share my email address so publicly here though, it's not private info but it doesn't have to be scraped either, so I'm not sure if I can share it privately through Github or through some other means.

**Comment by Zlopez** [comment]
You can send me the e-mail either on matrix (@Zlopez:matrix.org) (private chats have E2E encryption) or sent me e-mail directly to mkonecny@redhat.com

**Comment by Zlopez** [comment]
Solved with @PureTryOut on Matrix
