### ISSUE TITLE
Authentication using Google no longer works

### ISSUE THREAD

**Issue by gregswift** [fedora-infra/anitya#174]
Process:
* visit release-monitoring.org
* Select Login -> Google
* do any google specific intermediate steps (there arent always steps, but sometimes there are)
* Get error

Error:
```
400. That’s an error.

OpenID auth request contains an unregistered domain: https://release-monitoring.org/

Learn more

That’s all we know.
```

There is a big warning about this on their [OpenID page](https://developers.google.com/google-apps/sso/openid_reference_implementation)

They are consolidating onto [OpenID Connect](https://developers.google.com/identity/protocols/OpenIDConnect)

**Comment by pypingou** [comment]
Thanks this is something we should look into indeed.

I might turn off logging via google in the mean while

**Comment by pypingou** [comment]
Google's OpenID has been disabled, sorry it took so long

**Comment by ralphbean** [comment]
Can we close this issue now?
