### ISSUE TITLE
 Project: yubikey-manager-qt not showing newer tag 1.2.6

### ISSUE THREAD

**Issue by Justinzobel** [fedora-infra/anitya#1757]
https://release-monitoring.org/project/14844/ not showing 1.2.6 that shows on the webpage. Even after test check.

**Comment by Zlopez** [comment]
The reason is that they are not providing `tar.gz` on https://developers.yubico.com/yubikey-manager-qt/Releases/ anymore. So the regex will not find it. I updated the regex to address that.

**Comment by Justinzobel** [comment]
Thanks. Wow I feel stupid on this one :grin:

**Comment by Zlopez** [comment]
No need to feel stupid, it wasn't obvious at first glance.
