### ISSUE TITLE
Missing bugs

### ISSUE THREAD

**Issue by frenzymadness** [fedora-infra/anitya#1761]
Hello.

The package pyhon-jupyter-server-terminals is in Fedora and also in the release monitoring for quite some time. In Fedora, we have version 0.4.2 and it seems that release monitoring detected many new versions as well but never created a bug for them.

See:
* https://release-monitoring.org/project/287756/
* https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=POST&bug_status=MODIFIED&bug_status=ON_DEV&bug_status=ON_QA&bug_status=VERIFIED&bug_status=RELEASE_PENDING&bug_status=__closed__&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cshort_desc%2Cchangeddate%2Cbug_severity&f0=OP&f1=OP&f2=product&f3=component&f4=alias&f5=short_desc&f6=status_whiteboard&f7=CP&f8=CP&j1=OR&list_id=13439070&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&order=id%2C%20&query_format=advanced&v2=python-jupyter-server-terminals&v3=python-jupyter-server-terminals&v4=python-jupyter-server-terminals&v5=python-jupyter-server-terminals&v6=python-jupyter-server-terminals

**Comment by Zlopez** [comment]
The reason it didn't filled in bugs for new releases was the typo in Fedora package mapping. The package this project was mapped to in Fedora was `pyhon-jupyter-server-terminals` and the actual package in Fedora is `python-jupyter-server-terminals`. The missing t was the reason. I retrieved the latest version again and the [bug](https://bugzilla.redhat.com/show_bug.cgi?id=2275255) was filled without issue.

**Comment by frenzymadness** [comment]
Thank you and sorry I didn't spot the typo.

**Comment by Zlopez** [comment]
No need to be sorry it also took me some time before I noticed it as well.
