### ISSUE TITLE
`AUR` v `Arch Linux AUR` distributions.

### ISSUE THREAD

**Issue by Zopolis4** [fedora-infra/anitya#1785]
What is the difference between the `AUR` and `Arch Linux AUR` distribution options? Do they both need to exist?

It seems like `Arch Linux AUR` is the correct one, given that the `AUR` distro option doesn't provide a link.

The `AUR` distro also only has 44 packages, compared to the 292 of `Arch Linux AUR`. 

If they are both the same, perhaps it would make sense to remove `AUR` as it does not provide a link, and only have `Arch Linux AUR` to avoid confusion?

**Comment by Zlopez** [comment]
I assume that somebody didn't noticed that `Arch Linux AUR` exists and created `AUR` as well. Let me check if that is really the case and fix it.

**Comment by Zlopez** [comment]
So I checked it and it really looks like wrongly created distribution. I moved all the packages from `AUR` to `Arch Linux AUR` and deleted the `AUR` distribution.
