### ISSUE TITLE
Flags gives 401 unauthorized

### ISSUE THREAD

**Issue by scop** [fedora-infra/anitya#179]
Clicking "flags" at the top gives me (scop@fedoraproject.org) a "401 unauthorized" error page.

Also, I see "Flag" buttons in project views, but I have no idea what the button would do and don't find any docs about it. Even a tooltip describing what clicking the button does would be helpful.

**Comment by pypingou** [comment]
I agree for the tooltip, it is required and we should not show the ``flags`` link to non-admin.

As for what it does: it is a way to report to ask an admin to perform an action on a project (drop a specific version, fix mapping, delete the project entirely).

**Comment by Akasurde** [comment]
We can close this issue as PR is merged.

**Comment by pypingou** [comment]
It is closed :)
