### ISSUE TITLE
LanguageTool lists two incorrect versions

### ISSUE THREAD

**Issue by Alexander-Wilms** [fedora-infra/anitya#1790]
Can you please remove `6.3-branch` and `2023q3` from https://release-monitoring.org/project/241970/ ?

These versions don't match the archives at https://languagetool.org/download/

I already added these patterns to the version filter. `6.3-branch` could also be changed to `6.3`.

**Comment by Zlopez** [comment]
I removed the two incorrect versions, unfortunately we can't rename the retrieved version, just remove prefix.
