### ISSUE TITLE
Fedora login doesn't work

### ISSUE THREAD

**Issue by razzeee** [fedora-infra/anitya#1791]
It seems like the endpoint gives a 503

https://release-monitoring.org/login/fedora/ just shows a text on white background `Error: There was an error during authentication 'OpenID discovery error: HTTP Response status from identity URL host is not 200. Got status 503', please check the provided url.`

**Comment by nirik** [comment]
There was an outage of our auth infrastructure right around this time. 

Can you try again now and confirm it's working?

**Comment by razzeee** [comment]
It seems to work, but had a timeout before and login seems very slow in general.
