### ISSUE TITLE
Release information for haproxy is outdated

### ISSUE THREAD

**Issue by cbiere-marcant** [fedora-infra/anitya#1804]
The newest stable release of haproxy is version 3.0.3

https://www.haproxy.org/
https://git.haproxy.org/?p=haproxy-3.0.git
https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/h/

release-information.org still reports haproxy 3.0.0 as newest stable release.

**Comment by Zlopez** [comment]
I fixed the project to point to https://git.haproxy.org/?p=haproxy-3.0.git and changed the regex to reflect that. The latest version is now 3.0.3.
