### ISSUE TITLE
[release-monitoring.org support] Merge duplicate buildx projects

### ISSUE THREAD

**Issue by gotmax23** [fedora-infra/anitya#1809]
https://release-monitoring.org/project/325723/ and https://release-monitoring.org/project/369144/ have the same upstream. Can they be merged into one project?

**Comment by Zlopez** [comment]
I moved distribution mappings from https://release-monitoring.org/project/369144/ to https://release-monitoring.org/project/325723/. And deleted https://release-monitoring.org/project/369144/.
