### ISSUE TITLE
should utilities live here too?

### ISSUE THREAD

**Issue by bbenson-redhat** [fedora-infra/anitya#1815]
Suppose I created a utility that locally examines one package type and examines another targeted package type (locally or in https://release-monitoring.org/) to create a mapping of broad equivalence between them.  Would that utility want to live in this repo?  Sorry if such a utility already exists somewhere.  Thanks!

**Comment by bbenson-redhat** [comment]
Refining that a bit:
I've worked on a small script that's able to somewhat match what Fedora packages do the job of a list of debian packages. Would this be something the project is interested in/could leverage?

**Comment by Zlopez** [comment]
Thanks for working on something like that, but I don't think Anitya has any use for such utility. It just maps the projects to respective packages based on the edits made by users. It's not doing anything automatically in that regard, so the tool will not be a good match for this repository.

But feel free to create your own repository I assume there will be people who would find use for your tool :-)

**Comment by bbenson-redhat** [comment]
Thanks so much for the response.  Grateful for the work on the site.  This issue can close.
