### ISSUE TITLE
Specify major version?

### ISSUE THREAD

**Issue by siwinski** [fedora-infra/anitya#182]
Is there a way to specify a major version to watch for a package?  For example, I have two packages for the same project... one for the latest major version (3.x) [1] and one for the first major version (1.x) [2] because several packages still require the 1.x version.  The only "problem" I have is that the 1.x package is showing its' latest version as the latest 3.x version instead of the latest 1.x version and results in the-new-hotness creating tickets for 3.x for the 1.x package [3].

[1] php-Pimple (3.x): https://release-monitoring.org/project/3615/
[2] php-pimple1 (1.x): https://release-monitoring.org/project/6457/
[3] https://bugzilla.redhat.com/show_bug.cgi?id=1224779

**Comment by pypingou** [comment]
The only way to do this currently is to teak the regex :-/

**Comment by pypingou** [comment]
I adjusted the regex so that php-pimple1 only match versions starting with v1 (hopefully upstream won't change how they tag).

**Comment by siwinski** [comment]
Sorry, I should have thought to do that.  Thanks @pypingou
