### ISSUE TITLE
heimdall (1308) needs "[Stage*]" mapping removed

### ISSUE THREAD

**Issue by luk1337** [fedora-infra/anitya#1820]
We are using https://release-monitoring.org/project/374738/ on Fedora, but I didn't see a way to remove mapping, so I just changed Fedora=>heimdall to [Stage*]=>heimdall-dead at https://release-monitoring.org/project/1308/, I suppose it should be removed entirely.

**Comment by Zlopez** [comment]
I deleted the mapping and archived the project. Thanks for letting me know.
