### ISSUE TITLE
aom: latest version is out of sync

### ISSUE THREAD

**Issue by kleisauke** [fedora-infra/anitya#1826]
libaom v3.10.0 was released some time ago (https://aomedia.googlesource.com/aom/+/refs/tags/v3.10.0), but it looks like https://release-monitoring.org/ still shows 3.9.1 as latest version: https://release-monitoring.org/project/17628/.

Perhaps the version regex checks for `\d\.\d\.\d` instead of `\d+\.\d+\.\d+`?

**Comment by Zlopez** [comment]
@kleisauke Yes, you were right. It was the missing `+`. I added it and retrieved the missing versions. Thanks for reporting this.
