### ISSUE TITLE
Shorter tags are considered to have a lower value than other

### ISSUE THREAD

**Issue by LouisSchul** [fedora-infra/anitya#1828]
As the title says, shorter tag ( `[digits].[digits]`) are considered to have a lower value even when their first digit is higher.

Example: `v1.1` will be lower than `v1.0.0`

Concrete example:
![anitya_error](https://github.com/user-attachments/assets/6b18c2ee-0549-42c0-bea2-9a7254411542)

Expected result:
`v1.1` should be higher than `v1.0.0`.

Note: This is partly my fault for for not being consistent with my naming convention (I will fix that on my end) but the way this type of tag is handled is still an error in my opinion.

**Comment by Zlopez** [comment]
The reason for that is the wrong version scheme chosen for the project, the semantic expect X.X.X and recognizes X.X as invalid version, which is the reason that it is considered lower (invalid < valid). I changed version scheme to RPM which is much less strict in the format of version and the versions are now sorted correctly.
