### ISSUE TITLE
Empty notification mail from flagging

### ISSUE THREAD

**Issue by scop** [fedora-infra/anitya#183]
When flagging something, I get an empty notification mail. Well, not completely empty but it contains only the project URL and the footer, and no subject. For example I just received this after flagging a project:

<pre>
https://release-monitoring.org/project/4211/

--
You received this message due to your preference settings at
https://apps.fedoraproject.org/notifications/[...]
</pre>

**Comment by pypingou** [comment]
Sounds like something is up with either FMN or fedmsg_meta.

\cc @ralphbean

**Comment by ralphbean** [comment]
Must be fedmsg meta.

**Comment by ralphbean** [comment]
Yeah.  See [this message](https://apps.fedoraproject.org/datagrepper/id?id=2015-7b2fca29-7409-43f2-949f-c688437ba5d4&is_raw=true&size=extra-large) for example.  We never wrote a fedmsg.meta processor for that new message type.

**Comment by pypingou** [comment]
ok, thanks, I'll see to this tomorrow then
