### ISSUE TITLE
Search for multiple projects

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/anitya#1843]
I'd like to read short descriptions for this list.

```
action-docs             decasify                icu4c@74                libmsquic               node@22                 surfer                  vipsdisp
azqr                    dipc                    icu4c@76                libtatsu                onnx                    tcl-tk@8                wasi-runtimes
boring                  fcft                    kanata                  markdown-oxide          pytest                  toml2json               wasm-component-ld
comtrya                 foot                    langgraph-cli           mkdocs-material         rip2                    typos-lsp               zizmor
```

Not sure if https://release-monitoring.org is the right place to do so, but multi package search might be a feature.

**Comment by Zlopez** [comment]
How do you expect this to work?

**Comment by abitrolly** [comment]
Submit the block through search bar and in return page get table with links to package and short description.

|    |      |
|--- | --- |
| [`boring`](https://formulae.brew.sh/formula/boring) | SSH tunnel manager |
| `fcft` | -- not found-- |

**Comment by Zlopez** [comment]
I don't think we even have field for project description. I'm not sure how the submitting of the block would look, as it isn't clear when it should look for more packages and when it should look for one package with that is closer to submitted string.

**Comment by abitrolly** [comment]
If search string contains no space, it is single package name that would need fuzzy matching. If the search string contains spaces, it would be multi-package matching.

For descriptions, it would be better to design some "fat protocol" for information exchange about packages, so that instead of pulling data from each other's API (like from Repology and something like https://github.com/teaxyz/chai), the relevant tables can be synchronized in incremental blocks.
