### ISSUE TITLE
Strict version prefix handling

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/anitya#1847]
https://github.com/golang/tools is unfortunately a repo that releases multiple subprojects at a time, as well as itself. As a Go project, it follows the convention that overall tag is `vX.Y.Z`, and subproject tags are `subproject/vX.Y.Z`. The latest overall tag is v0.27.0, and the latest `gopls` subproject tag is `v0.16.2` (`v0.17.0-pre.2` if counting pre-releases).

There exists monitoring for this project in https://release-monitoring.org/project/9382/ It currently has all tags, but all the main tags sort above and this is working fine.

We recently split `gopls` into a separate package in Fedora in order to update it independently as necessary. So I then added a [second monitoring project](https://release-monitoring.org/project/375524/) with a version prefix of `gopls/v`. However, it appears that even with this setting, anitya _also_ applies its default prefix check of `v*`. This means that it thinks that v0.17.0 through v0.27.0 are part of the tags, and the latest version is now 0.27.0 instead of 0.16.2/0.17.0-pre.2.

I don't think I can do anything with the version filters either, as the main ones are just 'v', which appears in the subprojects tags too.

**Comment by Zlopez** [comment]
The `v` prefix is always checked. I'm not sure what to do in this case. The best option here is to find a place where the projects are released separately like pypi or some project homepage. Or use GitHub releases instead of tags.

**Comment by QuLogic** [comment]
No other places, unfortunately, as Go is decentralized. However, luckily, it does look like they use releases for _only_ `gopls`, so I can try that. Do we need to clear the existing versions after switching?

**Comment by QuLogic** [comment]
Oh, actually I've found https://pkg.go.dev/golang.org/x/tools/gopls?tab=versions which could be used as well with the right regex, probably.

**Comment by Zlopez** [comment]
Let me know when you do the changes, I will re-retrieve the versions from scratch.

**Comment by QuLogic** [comment]
I switched it to use releases, which will hopefully work.

**Comment by QuLogic** [comment]
PS, while I have your attention, could you please clear the tags on https://release-monitoring.org/project/78055/; 23.1 doesn't exist and it's been blocking notification of tags for a year.

**Comment by Zlopez** [comment]
Done, the version is removed.

**Comment by QuLogic** [comment]
I think you may have fixed the PS note, but not the original: https://release-monitoring.org/project/375524/

**Comment by Zlopez** [comment]
Which versions are wrong on the project? I only noticed the 23.1 as it was completely different.

**Comment by QuLogic** [comment]
That was the PS; the original problem was for `gopls`'s 0.17-0.27.

**Comment by QuLogic** [comment]
It all looks good now, thank you.
