### ISSUE TITLE
sha256sum: /var/tmp/thn-lC_H9n/100.0%: No such file or directory

### ISSUE THREAD

**Issue by jmlich** [fedora-infra/anitya#185]
The upstream monitoring tool failed during kickoff scratch build. See https://bugzilla.redhat.com/show_bug.cgi?id=1246479 Local mock build passed without problems.  Koji build also passed. See http://koji.fedoraproject.org/koji/taskinfo?taskID=10464231

**Comment by pypingou** [comment]
@ralphbean this has been fixed in the-new-hotness hasn't it?
(I seem to remember it was due to the change in output of spectool or so)

**Comment by ralphbean** [comment]
Yeah, this was fixed recently by fedora-infra/the-new-hotness#63.  Thanks all!
