### ISSUE TITLE
show version in search page

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#186]
would be cool if project search added extra column to show latest version found:

https://release-monitoring.org/projects/search/?pattern=trac

**Comment by pypingou** [comment]
Agreed :)

**Comment by vivekanand1101** [comment]
Just one question, is the version url [here](https://github.com/vivekanand1101/anitya/blob/master/anitya/lib/model.py#L303)for the latest version [here](https://github.com/vivekanand1101/anitya/blob/master/anitya/lib/model.py#L307) ?

**Comment by pypingou** [comment]
The version_url is used when looking for new versions

**Comment by vivekanand1101** [comment]
so, the only thing we have to add for this issue is `{{ project.latest_version }}` inside a `td` attribute after [here](https://github.com/vivekanand1101/anitya/blob/master/anitya/templates/search.html#L74)  without providing any link for the latest version ?

**Comment by pypingou** [comment]
Sounds about right :)
