### ISSUE TITLE
release-monitoring.org lacks a distro mapping link for Guix

### ISSUE THREAD

**Issue by mavit** [fedora-infra/anitya#1861]
A webpage for a Guix package can be found at `https://packages.guix.gnu.org/packages/%s`, where `%s` is the name of the Guix package.

**Comment by romulasry** [comment]
See:
https://release-monitoring.org/project/348503/
https://packages.guix.gnu.org/packages/shepherd/ for example

**Comment by Zlopez** [comment]
Feel free to add PR for this [file](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/release-monitoring/templates/anitya.toml#_115) to add the link.

**Comment by romulasry** [comment]
@Zlopez Done: https://pagure.io/fedora-infra/ansible/pull-request/2409

**Comment by Zlopez** [comment]
Merged and deployed
