### ISSUE TITLE
Bad version detected for bind

### ISSUE THREAD

**Issue by thozza** [fedora-infra/anitya#188]
Hi.

Today I got bug in RH Bugzilla for bind project with really wrong version. I didn't change anything recently and I'm not sure what went wrong.

https://bugzilla.redhat.com/show_bug.cgi?id=1248210
https://release-monitoring.org/project/187/

**Comment by pypingou** [comment]
They released a new version of couple of days ago which introduced a change in the tarball name (the -P3 added).

I deleted the odd version (1999), adjusted the regex and we should be back to normal.
