### ISSUE TITLE
New version of Ruby is not detected

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#190]
Ruby 2.2.3 was release a few days ago [1] but it is still not detected by Anitya [2]. Not sure what is the reason, since no logs of Anitya are available :/ I remember, that in original URM, we used to use custom RegEx, but there is no RegEx for Ruby anymore, has it disappeared somewhere or the default should be enough?

[1] http://ftp.ruby-lang.org/pub/ruby/stable/
[2] https://release-monitoring.org/project/4223/

**Comment by voxik** [comment]
Interesting, I triggered the update somehow, but don't think it appeared immediately I pressed "Check now" button. Moreover, I don't understand under what circumstances this button appears ...

**Comment by pypingou** [comment]
the button appears until you have a regex working or when you change it (change the backend or the regex)

**Comment by voxik** [comment]
This time it looks like rubygem-rails is not detected, while most of the other packages from the Ruby on Rails group were detected. Would it be possible to show the timestamp of the last check at least. This would help me understand if I am just impatient or something else is failing.


[1] https://release-monitoring.org/project/4305/

**Comment by pypingou** [comment]
The last run failed in a weird way, the next one should run fine

But I like the idea to show the date of the last check, will look into this

**Comment by pypingou** [comment]
Ok I've modified the footer to look like:

![anitya_footer1](https://cloud.githubusercontent.com/assets/1240038/10483531/43c8a790-7280-11e5-82b5-21e6519ec62d.png)

**Comment by voxik** [comment]
I am not sure this will be understood by users, e.g.

1. They may not know what the cron is (Windows?)
2. What the cron job actually does?

**Comment by pypingou** [comment]
It's the cron that checks for updates, do you have a better wording?

**Comment by pypingou** [comment]
What about: 

![anitya_footer2](https://cloud.githubusercontent.com/assets/1240038/10484164/ce793b9a-7283-11e5-89b3-d6f777c8a150.png)

**Comment by voxik** [comment]
That is definitely better .... What about "Last update" ... or "Last check"

**Comment by pypingou** [comment]
Let's go with ``Last check {started,ended} at...``

**Comment by voxik** [comment]
:+1:

**Comment by voxik** [comment]
So, the Ruby version is still not properly detected for some reasons.

The "stable" link on FTP was updated at 2016-01-05 09:44:00, the last check was 2016-01-07 00:10:02, but the 2.3 version is not detected.

**Comment by pypingou** [comment]
Ok, this was due to a bug in one of the backend (namely the pagure one) that was making the cron crash at python-libpagure.

This has been fixed in https://github.com/fedora-infra/anitya/pull/244 and hotfixed in prod (new cron running to check the fix)
