### ISSUE TITLE
please remove erroneous version from holland project

### ISSUE THREAD

**Issue by carlgeorge** [fedora-infra/anitya#192]
I was setting up monitoring for the holland pacakge on https://www.release-monitoring.org.  My initial thought was to use GitHub tags.  However, the upstream uses a weird tag scheme that resulted in anitya parsing the latest version as `v1.1.0a2`.  The correct latest stable version is `1.0.10`.  I have reconfigured the project to use the custom module and a regex search on the [upstream releases page](http://hollandbackup.org/releases/stable/1.0/), which was able to detect the correct version.  However, the incorrect tag version from before is still listed as the latest.  There is also this error message.

> Something strange occured, we found that this project has released a version "1.0.10" while we had the latest version at "v1.1.0a2" 

Please delete "v1.1.0a2" from the detected versions for this project.

**Comment by pypingou** [comment]
Done :)
