### ISSUE TITLE
Armadillo "preview" releases being improperly reported by the-new-hotness

### ISSUE THREAD

**Issue by rcurtin** [fedora-infra/anitya#194]
Hello there,

I hope I have found the right place to submit this.  (If not, let me know, and I'll try again elsewhere.)

The Armadillo linear algebra package often releases "preview" releases, which are not yet stable and should not yet be packaged for Fedora.  However, the-new-hotness (which, to my rudimentary understanding, uses anitya) picks these up regardless and files bugs on Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1253862

In the example I've linked to, the-new-hotness has filed a bug today for Armadillo 5.500.1, but that is a "preview" version:

http://arma.sourceforge.net/download.html
http://sourceforge.net/projects/arma/files/

Is there some way to disable the-new-hotness filing bugs for preview versions of Armadillo?  Note that I have no knowledge of anitya or the-new-hotness, nor did I set any of this up, so I am not useful for debugging here, just reporting.  I only know that I started receiving CCs on bugs one day.

**Comment by pypingou** [comment]
Looking at the version ``5.500.1``, how do you know it is a pre-release and not an official release?

Using this number, I can't think of a way to make anitya find it if this is a new version or not.

**Comment by rcurtin** [comment]
It's in a `preview/` directory on Sourceforge:
http://sourceforge.net/projects/arma/files/
And the Armadillo download page notes that it's a preview version:
http://arma.sourceforge.net/download.html

Whether or not anitya does or even should be able to detect this, I'm completely indifferent to, but if your decision is that the support shouldn't be there, my opinion is that the package should be removed from anitya to stop the Bugzilla bugs.

**Comment by pypingou** [comment]
The link between anitya and bugzilla is done via pkgdb, anitya is not specific to Fedora although we are its heaviest contributor.

That being said, if it is in the ``preview/`` directory, the regex could be tweak to ignore this directory (note: for sourceforge we rely on the rss feed of the project).

**Comment by pypingou** [comment]
Ok I have adjusted the regex to exclude the ``preview/`` folder

**Comment by rcurtin** [comment]
Thanks!  Much appreciated. :)
