### ISSUE TITLE
Duplicate info submitted

### ISSUE THREAD

**Issue by cicku** [fedora-infra/anitya#196]
Hi,

Not sure why I submitted something successfully! Now there are 2 URLs for the same project, while one is deprecated:

https://release-monitoring.org/projects/search/?pattern=ranger

Please drop the one using savannah.

Thanks!

**Comment by pypingou** [comment]
> Not sure why I submitted something successfully! 

Because the homepage is one of the key to figuring out if two projects are the same or not, in these case they would appear to be different projects.

ranger on savannah dropped.

**Comment by cicku** [comment]
Thanks. Further check should be added before adding different URLs to existing projects.
