### ISSUE TITLE
duplicate packages

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#197]
tried irc, but no response. so trying ticket

```

19:30:07  glen> hey. there's duplicate vim package definition
19:30:12  glen> in anytya
19:30:14  glen> https://release-monitoring.org/project/5092/
19:30:19  glen> https://release-monitoring.org/project/7257/
19:30:26  glen> how to handle this?
19:30:48  glen> i fixed 7257, but 5092 has other distros
```

**Comment by pypingou** [comment]
Let's drop 7257 and adjust 5092 to work

**Comment by pypingou** [comment]
7257 dropped and mapping added for FZUG

**Comment by glensc** [comment]
seems you forgot to adjust 5092 to work, as i said i fixed 7257 to work, but rules from it are not transferred to 5092, as it still says just 7.4, not full version.

**Comment by glensc** [comment]
please put config from 7257 to 5092!
