### ISSUE TITLE
Querying for projects with an empty homepage shouldn't return all projects

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/anitya#198]
As mentioned in fedora-infra/the-new-hotness#46, when you query the anitya API for the list of projects with ``homepage=''``, it currently returns all projects (I'm assuming the homepage filter is just ignored since ``bool(homepage) == False``).

Instead, it should return only the projects with *no* homepage **or** it should return some kind of 400 error, indicating a bad request.

**Comment by pypingou** [comment]
Looking at the code, this makes me curious: https://github.com/fedora-infra/anitya/blob/master/anitya/api.py#L174

**Comment by Akasurde** [comment]
We can close this issue as PR is merged.

**Comment by pypingou** [comment]
Indeed :)
