### ISSUE TITLE
Remove Fedora mappings for a number of retired perl packages

### ISSUE THREAD

**Issue by contyk** [fedora-infra/anitya#199]
The following packages are now retired in Fedora. Please, remove the respective distribution mappings from Anitya.

- perl-B-Hooks-OP-Check-EntersubForCV
- perl-Data-Dump-Streamer
- perl-Devel-BeginLift
- perl-Devel-FindRef
- perl-Method-Signatures
- perl-POE-API-Peek

Thanks.

**Comment by pypingou** [comment]
I don't think it's worth removing them, it shouldn't do any harm (and if it does it's a bug we should fix :))

**Comment by ralphbean** [comment]
@pypingou are you going to close this bug, or leave it open?

@contyk is it causing issues anywhere else to keep those mappings in place?

**Comment by pypingou** [comment]
I wanted to hear from @contyk if he agrees with me first (or if he sees a potential issue I could have missed)

**Comment by contyk** [comment]
Ah, sorry for the delay -- I didn't get any notifications for some reason.

I don't know -- why keep useless mappings around?  And why can't people remove them in the first place? What happens if there's a new release of a retired package which still has the monitoring flag set in Fedora PkgDB? Will the-new-hotness file a ":please update" bug? I hope not. If not, it's (probably) just an additional check you need to perform ("is it retired?").

Removing the mapping seems simple and logical to me.

**Comment by pypingou** [comment]
So we made sure that the-new-hotness won't be opening bug reports on retired packages: https://github.com/fedora-infra/the-new-hotness/commit/d24ad0ef47e383ad92970c3c2ceed8ac0d89955b

**Comment by pypingou** [comment]
I think we can close this issue now, it won't behave in a way we do not want and it keeps a little cross-distro infos in anitya which I like.

Feel free to re-open if you fee like this wasn't satisfying :)
