### ISSUE TITLE
[rfe] add a marker for dead projects to stop anitya opening their URL

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/anitya#204]
Example: Vidalia ( https://release-monitoring.org/project/5088/ ) is dead, see https://lists.torproject.org/pipermail/tor-talk/2015-February/036833.html

So we need a marker to make anitya stop loading its URL. And it would be useful for downstream to tell them "this package is retired".

**Comment by pypingou** [comment]
What if the project starts again? Maybe by someone else? Does it do any harm?

**Comment by pypingou** [comment]
In this case, we could just drop the project since all the pages are gone

**Comment by pypingou** [comment]
I'm going to close this ticket as this specific case is fixed and I am not sure to be behind the general idea :)

Thanks for the report!
