### ISSUE TITLE
cpan module check issue

### ISSUE THREAD

**Issue by dfateyev** [fedora-infra/anitya#206]
Unable to check and determine new/current version for https://release-monitoring.org/project/7637/

Throws an error:
```
perl-Array-Unique: no upstream version found.
 - http://search.cpan.org/dist/perl-Array-Unique/
 - perl-Array-Unique(?:[-_]?(?:minsrc|src|source))?[-_]([^-/_\s]+?)(?i)(?:[-_](?:minsrc|src|source|asc))?\.(?:tar|t[bglx]z|tbz2|zip)
```

**Comment by vivekanand1101** [comment]
It was probably because it should be "Array-Unique" and not "perl-Array-Unique". The page [here](http://search.cpan.org/dist/perl-Array-Unique/) says "The distribution 'perl-Array-Unique' cannot be found, did you mean one of these"

**Comment by pypingou** [comment]
@vivekanand1101 's analysis sounds good :)

**Comment by dfateyev** [comment]
Yes, probably my fault. It should be 'Array-Unique', @vivekanand1101 thanks for pointing this out.
