### ISSUE TITLE
Failed login can't be retried

### ISSUE THREAD

**Issue by jamesjer** [fedora-infra/anitya#207]
I attempted to login with Fedora.  After several minutes, ipsilon reported an internal server error and asked me to try again.  So I went back to the main release-monitoring.org page and selected "Login -> Fedora" again.  I immediately got the message: "Error during login: The OpenID was invalid."  I have reloaded the page, closed the tab and visited release-monitoring.org in a new tab, and I still get this same error.  There doesn't seem to be any way to clear it so I can try logging in again.

**Comment by nirik** [comment]
This was likely during the scheduled maint that the fedoraproject was doing. 

Does the problem persist now? or is it working again?

**Comment by jamesjer** [comment]
Ah, okay.  Well, I can log in now, but I figured that was transient.  My concern was that I couldn't find a way to try logging in again, rather than not being able to log in in the first place.

**Comment by pypingou** [comment]
Let's close this ticket for now and re-open it if it happens again
