### ISSUE TITLE
"Flag" actions notification

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#209]
A while back I flagged a project with message (from log):

>2015-10-01 07:36:56 	vondruch@redhat.com flagged the project: minitest with reason: I don't think that this project should exist. The rubygem-minitest4 is just older version of rubygem-minitest. rubygem-minitest4 will not be ever updated. Please delete this project. 

Nevertheless, I am not sure if/how/when this was processed, since I did not received any subsequent notification.

Am I missing some FNM settings or there is no notification at all? If there is non, could you please add some notification? And it should be enabled by default IMO.

**Comment by pypingou** [comment]
I just pushed a new version of anitya in which we include the project when emitting a fedmsg message about a flag. That project can be linked to a package and with this we should be able to notify users of changes of flag in anitya about a project related to their packages.

Not sure we can do much more w/o conflicting with #205 which will already be kinda hard to fix anyway.

**Comment by pypingou** [comment]
I'm gonna close the ticket with the resolution: ``Hopefully fixed`` :)
