### ISSUE TITLE
/project/<ID>/edit should better help with regex format

### ISSUE THREAD

**Issue by praiskup** [fedora-infra/anitya#211]
ssia

**Comment by praiskup** [comment]
I've already found the "about" page, sorry.  Could we consider linking the
"edit-project"-page with the '/about' page?

**Comment by praiskup** [comment]
By this I mean some clear link with title "how to edit/examples".

**Comment by vivekanand1101** [comment]
@praiskup some work is going on for putting the default regex in the edit/add project page itself. Would that help?

**Comment by praiskup** [comment]
@vivekanand1101 wrote:
> @praiskup some work is going on for putting the default regex in the
> edit/add project page itself. Would that help?

Yes :)

**Comment by praiskup** [comment]
However, its hard to test that the regex actually works (via web-ui).  The 
`/about` page is still more helpful.  Maybe the regex-testing feature could be
automatized in web-ui?

**Comment by praiskup** [comment]
(ohh, I see -- about#test-your-regex, thanks - that would be enough)

**Comment by praiskup** [comment]
more info in: fedora-infra/anitya/pull/210
