### ISSUE TITLE
Order backends

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/anitya#212]
It seems the backends aren't ordered alphabetically, we should change this :)

**Comment by farhaanbukhsh** [comment]
I would like to work on this issue :)
@pypingou

**Comment by farhaanbukhsh** [comment]
Hints required :)

**Comment by pypingou** [comment]
@farhaanbukhsh I've seen you work so I'd like to ask you to take a look at the sources and try to find the solution by yourself :)

That being said, if you are not sure, feel free to ping me, here on or IRC and we can do it together, but I'd like it if you could try yourself first :)

**Comment by farhaanbukhsh** [comment]
@pypingou okay i will try it although I don't know what are backends but let me look into the code base :). I will ping you
