### ISSUE TITLE
If upstream changes versioning scheme, there is no way to invalidate the old versions

### ISSUE THREAD

**Issue by michel-slm** [fedora-infra/anitya#215]
For example, with Zeal:

https://release-monitoring.org/project/7839/

Upstream switched from YYYYMMDD to the more standard vX.Y.Z tags for their releases. The standard GitHub preset determined the latest version to be 20141123; I then switched the version check to custom and used my own regex, which strictly searched for vX.Y.Z ones -- but this does not clear the old versions, now the log says

    Something strange occured, we found that this project has released a version "0.1.1" while we had the latest version at "20141123"

**Comment by michel-slm** [comment]
Having a preview when changing the upstream source declaration that would list the matched versions, to which the user can then either confirm or request changes, might be a nice feature?

**Comment by pypingou** [comment]
I just removed the old version, keeps things simple :)

Thanks for the report
