### ISSUE TITLE
Add support for (SourceForge) git tags

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/anitya#223]
Some projects use git tags in public git repositories to mark releases. Support for those would be helpful.

**Comment by pypingou** [comment]
Do you have an example?

Note: Anitya doesn't download anything but a web-page, and I'm not sure I would want anitya to clone a git repo to extract its tags, if that what you are suggesting.

**Comment by genodeftest** [comment]
Example: http://sourceforge.net/p/eclipse-cs/git/ci/master/tree/ (ok, bad one because it should work with the sourceforge module)
https://release-monitoring.org/project/654/

**Comment by pypingou** [comment]
Edited the title of the issue.

I think the easiest solution for this would be to make a ``SourceForget (git)`` backend that would retrieve the tags from http://sourceforge.net/p/<project>/git/ref/master/tags/

for example: http://sourceforge.net/p/eclipse-cs/git/ref/master/tags/

**Comment by jeremycline** [comment]
If there's an API I'm all for that, but I don't want to clone repositories or anything

**Comment by yarons** [comment]
@jeremycline I'm not sure how to query this API but I'm guess this is what you're after:
https://sourceforge.net/p/forge/documentation/Using%20the%20Release%20API/

**Comment by Zlopez** [comment]
@yarons According to the documentation you sent, this API is only for creation of tags.

**Comment by yarons** [comment]
@Zlopez that sucks, sorry for that.
