### ISSUE TITLE
edit project corrupts Backend value

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#227]
Seems if i go edit some Github type project
the Edit view set Backend dropdown to Bitbucket
and if you don't notice this, you will save wrong backend type there!

for example:
https://release-monitoring.org/project/5346/
Backend: Github

![view](https://cloud.githubusercontent.com/assets/199095/10920901/53b0f35a-827b-11e5-8f08-e4be227a4e66.png)

https://release-monitoring.org/project/5346/edit

![edit](https://cloud.githubusercontent.com/assets/199095/10920908/5936b9c2-827b-11e5-95c3-c660e575adec.png)

**Comment by pypingou** [comment]
That's because the case for the github backend changed from Github to GitHub.
If you re-set the backend to GitHub and try editing, then it works

**Comment by pypingou** [comment]
I directly fixed all the projects in the DB, so we should be set for this.
