### ISSUE TITLE
unable to remove mapping

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#228]
there was [net_SDL2](https://release-monitoring.org/project/4783/) package, which had mapping for pld-linux `SDL_net` package.

however, i created [net_SDL](https://release-monitoring.org/project/7983/) package for the 1.x series.

but adding distro mapping was impossible because it was mapped as `SDL_net` in `net_SDL2` package, removing  the mapping is impossible, so i renamed it to [SDL_net___FAKE](https://release-monitoring.org/project/4783/map/5531)

ps: during package create and immediately filling distro mapped, i got 500 error page, when i hit reload it said package already exists. so it created package but failed to add distro mapping and gave 500 instead

**Comment by pypingou** [comment]
Mapping deleted

**Comment by glensc** [comment]
no explanation how to behave next time this happens?

**Comment by glensc** [comment]
no response about 500 error?

**Comment by pypingou** [comment]
Regular users cannot delete items, so if you need something deleted, either open a ticket here or flag the project and ask for what you need.

For the 500, I have not seen them, let's open a different ticket if that happens again

**Comment by glensc** [comment]
i explained why it likely happened, check your server logs. and you can reproduce it according to my description.

**Comment by glensc** [comment]
here's two more to delete (with `__bogus` suffix):

https://release-monitoring.org/project/1705/

**Comment by glensc** [comment]
what i think would be more useful, is to be able to move "distro package name name" to different "anitya package", as that is really what this is about. distro package name is mapped to wrong anitya project.

**Comment by Germano0** [comment]
Hi, I need to remove the "mirall" mapping for https://release-monitoring.org/project/1987/
