### ISSUE TITLE
can't edit debconf project or configure a new debconf project 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/anitya#230]
Project name 	debconf_2
Homepage 	https://tracker.debian.org/pkg/debconf
Backend 	Debian project 
Version prefix 	debconf

Distro (optional) 		Fedora
Package (optional) 	        debconf

sent this form and I got error http 500

**Comment by sergiomb2** [comment]
sorry , something happens in infrastructure , not it is running well
but I can't delete the duplicated projects , I renamed to "please delete me"
https://release-monitoring.org/projects/search/?pattern=please
and yes please delete those projects 
Thanks,

**Comment by pypingou** [comment]
Why do you want to delete projects?

**Comment by pypingou** [comment]
I deleted them, but you should be able to fix the project rather than creating new ones.

**Comment by sergiomb2** [comment]
Yes, Thanks.
