### ISSUE TITLE
New version of wget didn't trigger a bug report in RH Bugzilla

### ISSUE THREAD

**Issue by thozza** [fedora-infra/anitya#231]
Hi. I'm not sure where to file this issue, thus adding it here. The last version of wget 1.17 didn't create the bug in RH Bugzilla. On the project site (https://release-monitoring.org/project/5124/) I can see that the version was detected. I'm not sure where may be the problem.

Thanks

**Comment by thozza** [comment]
The version 1.17 was released on 2015-11-15

**Comment by pypingou** [comment]
We had a problem with the-new-hotness for a little while, let me try to trigger it quickly

**Comment by pypingou** [comment]
Seems to be fixed now https://bugzilla.redhat.com/show_bug.cgi?id=1286008 :-)

**Comment by thozza** [comment]
Great! thanks :)
