### ISSUE TITLE
github driver

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#242]
would be nice if github driver is able to exclude "pre-releases".

https://github.com/toggl/toggldesktop/releases

this particular one has one full page of pre-releases, the full-release is not even visible, and thus anitya manages to crawl that version is some bogus "123".

![screenshot-1](https://cloud.githubusercontent.com/assets/199095/11843096/49c66dbe-a410-11e5-9076-00475acb8fff.png)

https://release-monitoring.org/project/5417/

**Comment by pypingou** [comment]
That could be a good feature but note that the github backend relies on the tags not the releases feature of github: https://github.com/toggl/toggldesktop/tags

**Comment by Zlopez** [comment]
There is now a newer issue trying to solve this #1499
