### ISSUE TITLE
http status codes for failed form submissions?

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/anitya#246]
currently if you submit a form with some bogus data, it will return you to the same form with some helpful error messages about what you messed up.

However, the status code on the http response is '200' which is misleading for scripts.  I think we can make that code '400' and still return the form to the user.

**Comment by pypingou** [comment]
:+1: for me, just not sure how to do this (or if it's doable).

**Comment by puiterwijk** [comment]
That would be something like:

return render_template('form.html'), 400

**Comment by puiterwijk** [comment]
or, if you return the form on one place, you can do a status = 200, and then at the point where you find the validation didn't pass, set status=400, and do "return render_template('form.html'), status"

**Comment by chaiku** [comment]
Trying to understand this. Please correct me if I am wrong: The issue here is when trying to submit a new project form, we get http status 200 which is incorrect  and should be 400.
```127.0.0.1 - - [03/Jun/2016 20:02:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Jun/2016 20:06:32] "GET /project/new HTTP/1.1" 200 -
127.0.0.1 - - [03/Jun/2016 20:06:41] "GET /api/projects?pattern=koqoqjdoq HTTP/1.1" 200 -
127.0.0.1 - - [03/Jun/2016 20:06:42] "GET /api/projects?homepage=wdpoqjdjq HTTP/1.1" 200 -
WARNING:fedmsg.crypto.x509:Crypto disabled ImportError('No module named M2Crypto',)
127.0.0.1 - - [03/Jun/2016 20:06:54] "POST /project/new HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2016 20:06:54] "POST /project/new HTTP/1.1" 302 -
127.0.0.1 - - [03/Jun/2016 20:06:54] "GET /project/4/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2016 20:06:54] "GET /project/4/ HTTP/1.1" 200 -
127.0.0.1 - - [03/Jun/2016 20:06:54] "GET /static/img/spinner.gif HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Jun/2016 20:06:54] "GET /static/img/spinner.gif HTTP/1.1" 200 -
```
This is what we are talking about in here, right?

**Comment by pypingou** [comment]
Yes it's the idea, return an error code (400) but still display the correct html to the users

**Comment by chaiku** [comment]
Ok. I have another question though: While submitting the form, it just 'submits' the form and the 200 code is an indication of a successful submission. When the "Test Check" or the "Full Check" button is pressed then we get an error message (with an http code 400) saying that the said project form has incorrect data. Is this our problem here?

**Comment by pypingou** [comment]
No I think the issue here is really to return a 400 if the form submitted is invalid/has errors

While at it, we could see how the API behaves but I think the original intent is very much about the UI

**Comment by chaiku** [comment]
I guess then the api.py has to be changed in order to automatically check if the submitted form contains valid data or not when submitting the form for the first time.

**Comment by pypingou** [comment]
Probably more than just ``api.py``

**Comment by chaiku** [comment]
Thanks pypingou :) I'll try to work on a solution
