### ISSUE TITLE
ui not usable with keyboard

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#249]
hi

pages not usable with keyboard only,
take for example add mapping page:
https://release-monitoring.org/project/8736/map

  - the default input (on this page "distribution") is not focused, i have to tab 11 times to reach the field
  - i type "pld" there, a popup appears,
  - now if i press enter, it will try to submit the form saying "package name" field is required insead of autocompleting
  - if i press tab, it just jumps to next field, aborting autocomplete

**Comment by lokendra9009** [comment]
Hi, I would like to work on this issue, Currently trying to understand it completely

**Comment by lokendra9009** [comment]
Do we really need to fix the third bullet ? 

> now if i press enter, it will try to submit the form saying "package name" field is required insead of autocompleting

As per me this functionality is working fine, As a Tab should navigate to the next Web element not auto complete the package name, (Think of a scenario where the popup shows multiple suggestions like typing 'fed') Hence I think I won't be good to implement an auto complete using TAB

currently pressing the down arrow button would select the correct desired package name for you and hence completing the text box for you.

For the first point yes that can be worked upon

**Comment by glensc** [comment]
i'm ok to omit the third one
