### ISSUE TITLE
[rfe] Please add support for KDE projects

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/anitya#250]
As with GNOME projects it would be nice to have a template to auto-fetch version numbers of KDE applications.

**Comment by pypingou** [comment]
And where can these be found? :)

**Comment by genodeftest** [comment]
There are different places where software can be found depending on wheter it belongs to plasma, frameworks, etc.

KDE Plasma:
* Announcements on https://www.kde.org/announcements/ titled "Plasma [Version]"
* https://www.kde.org/info/plasma-[Version].php
* http://download.kde.org/stable/plasma/ (probably the best)

KDE Frameworks:
* Announcements on https://www.kde.org/announcements/ titled "KDE Frameworks [Version] released"
* https://www.kde.org/announcements/kde-frameworks-[Version].php
* http://download.kde.org/stable/frameworks/ (probably the best)

KDE Applications:
* Announcements on https://www.kde.org/announcements/ titled "KDE Applications [Version] released"
* https://www.kde.org/announcements/announce-applications-[Version].php
* http://download.kde.org/stable/applications/ (probably the best)

And some more applications, which can be found below http://download.kde.org/stable/

This is the most structured data I could find so far.

**Comment by pypingou** [comment]
Can a software be in several of these location ?

Otherwise, it seems that the folder backend with a '*' in the URL might be able to work (the GNOME backend exists because they provide the version in a non-standard way/place)

**Comment by genodeftest** [comment]
Ok, you are right. I've added (and keep adding) projects and packages:
[KDE Frameworks](https://release-monitoring.org/project/8762/)
[KDE Plasma Desktop](https://release-monitoring.org/project/8761/)
[KDE Applications](https://release-monitoring.org/project/8763/)

**Comment by pypingou** [comment]
You can use that approach but I was more thinking of 1 project per project (as expected) and use in version_url something like: http://download.kde.org/stable/applications/*/ which should work

**Comment by genodeftest** [comment]
As far as I know "KDE Frameworks" and "KDE Plasma" are considered a single project each. Is that not so?

**Comment by pypingou** [comment]
If that's how the community sees it, it's fine for me :)
