### ISSUE TITLE
Problem with detecting version of log4cplus on sourceforge.net

### ISSUE THREAD

**Issue by thozza** [fedora-infra/anitya#251]
Hi.

Based on the project page in release-monitoring.org https://release-monitoring.org/project/1835/ the latest version of log4cplus is 1.1.3. However I can see that upstream has latest version of 1.2.0 http://sourceforge.net/projects/log4cplus/files/log4cplus-stable/

I'm not sure where might be the problem.

**Comment by pypingou** [comment]
anitya uses the rss feed from sourceforge to get new versions: http://sourceforge.net/projects/log4cplus/rss?path=/

Looking at it, it seems there only was a 1.2.0-rc6, I guess anitya waits for the 1.2.0.tar.gz

**Comment by thozza** [comment]
What is strange is, that there is also only RC version of 1.1.3-rc6.

**Comment by pypingou** [comment]
And anitya doesn't find it, it seems the last release it found was 1.1.2 which apparently had a 'log4cplu-1.1.2.tar.gz' : http://sourceforge.net/projects/log4cplus/files/log4cplus-stable/1.1.2/

**Comment by pypingou** [comment]
Might be worth signaling to upstream, it seems the project is also on github: https://github.com/log4cplus/log4cplus

**Comment by thozza** [comment]
Will do. Thanks for your time!

**Comment by pypingou** [comment]
Let me know if you managed to fix the problem, otherwise we can always tweak the regex to ignore the -rc part, but then you'll be aware  of the new release at the first release candidate.

**Comment by wilx** [comment]
Just FYI, I have released version 1.2.0 of log4cplus.

**Comment by pypingou** [comment]
And anitya found it, thanks!

So we can close this now, thanks again everyone
