### ISSUE TITLE
ui improvement for not found packages

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#252]
so you search package that does not exist.
would be nice if besides saying "Oups this is embarrassing, it seems that no projects are being monitored currently." it could link directly to adding package page having package name pre-filled.
also the text is kind of misleading like there are NO projects at all monitored, but it intended to say probably NO projects BY THAT NAME.

so,

https://release-monitoring.org/projects/search/?pattern=example-project-not-found

Oups this is embarrassing, it seems that no projects by that name are being monitored currently.
[Try adding it](https://release-monitoring.org/project/new?name=example-project-not-found)

ps: as you can see, the `name` parameter support is already there, should be simple as just changing html

**Comment by pypingou** [comment]
Fixed in #256
