### ISSUE TITLE
Method for more complicated version parsing

### ISSUE THREAD

**Issue by swt2c** [fedora-infra/anitya#253]
It would be great if there was a way to specify a more complicated version parsing.  For example, poco[1] uses poco-<version>-release, so we need to remove both a prefix and a postfix.

[1] https://github.com/pocoproject/poco/releases

**Comment by pypingou** [comment]
You could use the custom backend instead of the github one and use your own regular expression

**Comment by swt2c** [comment]
Ah, my bad.  I didn't realize that was a possibility.  I'll do that, thanks!
