### ISSUE TITLE
Check for pre-release

### ISSUE THREAD

**Issue by rapgro** [fedora-infra/anitya#258]
If there's a package tagged as a pre-release in the repo, anitya should report a bug anyways cause pre-releases are mostly built from a snapshot. Currently anitya does not encounter such a case cause the upstream version does not differ from the package version, but there's the pre-release, normaly as "0.x" in the Release tag of spec file.

**Comment by pypingou** [comment]
Anitya doesn't report any bugs, did you mean the-new-hotness?

**Comment by rapgro** [comment]
Yes, I mean the-new-hotness. Not sure where to file this RFE.

**Comment by pypingou** [comment]
There: https://github.com/fedora-infra/the-new-hotness/ :)

**Comment by rapgro** [comment]
Moved over, thanks.

**Comment by pypingou** [comment]
Thank you :)
