### ISSUE TITLE
Explicitly mention python version used, in the documentation

### ISSUE THREAD

**Issue by sudheesh001** [fedora-infra/anitya#262]
I've been trying to set this up and it breaks with python3 and virtualenv which is python3
It works fine with python2.7

In the setup documentation, I think it'd be a great idea to mention that python3 isn't supported (yet).

If this is fine, I'd like to make a patch for this.

**Comment by pypingou** [comment]
It's kinda there but not explicit indeed: https://github.com/fedora-infra/anitya#virtualenv refers to the classic way of making virtual environments which is still py2 by default.

But sure :+1: to make it explicit somewhere.
