### ISSUE TITLE
Add project: homepage field passes even if the text in it isn't a link

### ISSUE THREAD

**Issue by sudheesh001** [fedora-infra/anitya#265]
I believe the homepage field should be stricter and should only approve links to the homepage.
Typing in information which doesn't pass as a link into the homepage field should not be allowed.

We can do this in 2 ways
1. a regex in javascript on the field homepage
2. regex in python and give the required error message as a flash

**Comment by pypingou** [comment]
There is a third way: html5 :)

**Comment by sudheesh001** [comment]
@pypingou Ah ! True that, that makes this easier :wink:
