### ISSUE TITLE
timezoneless dates

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#268]
`Last check ended at 2016-02-22 12:26:13`

it's not clear what the time is if you do not include timezone in it. the specific example was taken from page footer, but i guess there are more places where datetime is presented (logs handler for example)

**Comment by glensc** [comment]
![image](https://cloud.githubusercontent.com/assets/199095/13231899/0b83c116-d9b5-11e5-82bf-31a2b728b7d9.png)

the `logs` handler needs some css fix too, the columns are too close each other

**Comment by pypingou** [comment]
All the dates are (or should be) UTC.

**Comment by glensc** [comment]
it should be written in output so too, not having to guess or submit bugreport

**Comment by pypingou** [comment]
agreed that it should be shown

**Comment by arush0311** [comment]
Can I work on this?

**Comment by pypingou** [comment]
Yes, of course :)

**Comment by glensc** [comment]
and What about the CSS fix?

**Comment by glensc** [comment]
and it only fixes LOGS view, there are more places with timestamps! please read the [initial bugreport](https://github.com/fedora-infra/anitya/issues/268#issue-135536087)!

**Comment by glensc** [comment]
please reopen!
