### ISSUE TITLE
Strings following dots (".") in URLs are ignored, at least for PyPI packages

### ISSUE THREAD

**Issue by TC01** [fedora-infra/anitya#271]
At least, I *think* this is what's going on...

I maintain python-pdfminer in Fedora. For Fedora 24+, I moved pdfminer to be the [pdfminer-six](https://pypi.python.org/pypi/pdfminer.six/) fork.

When attempting to enable release monitoring, however, anitya told me the latest version was "20140328"... which was the last release of [pdfminer](https://pypi.python.org/pypi/pdfminer), and more notably never actually a release of pdfminer.

I changed the URL to something nonsensical, e.g. "https://pypi.python.org/pypi/pdfminer.seven/", and still, 20140328 was the last release.

My only conclusion is that for whatever reason, all the text following the "." is being stripped?

**Comment by pypingou** [comment]
That's simply because on the PyPI backend, all anitya needs is the project name, so the homepage isn't used anywhere.

If the homepage was used, then you would have a problem since https://pypi.python.org/pypi/pdfminer.seven/ returns a 404

**Comment by pypingou** [comment]
So basically anitya kept on checking https://pypi.python.org/pypi/pdfminer and retrieved the correct version from this project.

**Comment by TC01** [comment]
Oh, I see. Nevermind then! Sorry for the erroneous bug report.

**Comment by pypingou** [comment]
I didn't quite understand what you were trying to do, so maybe we could improve things compared to what is happening now :)

**Comment by TC01** [comment]
I guess I was just confused that it was "Project Name" and not "Homepage" that (at least the PyPI backend) used to actually do its thing, though on reflection it makes sense-- a package hosted on PyPI doesn't have to have its homepage be on PyPI.  The reason I got confused, I think, is that under "Examples", some PyPI URLs are listed, which made me think it was the URL that mattered and the project name was a human readable descriptor.

What I was trying to do: "pdfminer" in Fedora originally pointed to the "pdfminer" package on PyPI, but now I've changed it to point to the "pdfminer.six" fork of the package on PyPI. I wanted to set up release monitoring such that the Fedora package for (python-)pdfminer got alerts when pdfminer.six on PyPI changed.

This was my first time actually using anitya, incidentally-- it's a nice service! :)

**Comment by pypingou** [comment]
> under "Examples", some PyPI URLs are listed, which made me think it was the URL that mattered and the project name was a human readable descriptor.

Indeed the examples list project on pypi but the idea is more to indicate why pypi is, but I can see the confusion with if/how the url is used. Maybe that would be something worth adding to the doc.

> I wanted to set up release monitoring such that the Fedora package for (python-)pdfminer got alerts when pdfminer.six on PyPI changed.

I see you managed to do the changes you wanted, cool :)

> This was my first time actually using anitya, incidentally-- it's a nice service! :)

Thanks, with @ralphbean 's work on the-new-hotness it becomes quite a nice combo :)
