### ISSUE TITLE
reopen #268

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#273]
reopen #268, it is not fixed:
https://github.com/fedora-infra/anitya/issues/268#issuecomment-192308066
https://github.com/fedora-infra/anitya/issues/268#issuecomment-192308361

**Comment by pypingou** [comment]
It's easier to track things if there are in different tickets (for example the CSS fix in the ticket about timezone).

So rather than re-opening #268 I opened #276 and #277.

I hope this satisfies you :)

**Comment by glensc** [comment]
thank you!
