### ISSUE TITLE
improve searching projects

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#275]
to avoid such mistakes again #274,
please improve searching, so that if no exact matches are found, fall back to substring match

1. search for [`sodium`](https://release-monitoring.org/projects/search/?pattern=sodium)
2. it gives no exact matches, so retry search with [`sodium*`](https://release-monitoring.org/projects/search/?pattern=sodium*)
3. and if still no matches, retry with [`*sodium*`](https://release-monitoring.org/projects/search/?pattern=*sodium*)

of course could just change default pattern to be `*sodium*`

**Comment by akien-mga** [comment]
This does not seem to work as it should, compare e.g. https://release-monitoring.org/projects/search/?pattern=wcwidth and https://release-monitoring.org/projects/search/?pattern=*wcwidth

**Comment by akien-mga** [comment]
Also, the code snippet modified in c8e9eea could be simplified a bit:
```
    if not pattern.startswith('*'):
        pattern = '*' + pattern
    if not pattern.endswith('*'):
        pattern += '*'
```

**Comment by akien-mga** [comment]
> This does not seem to work as it should, compare e.g. https://release-monitoring.org/projects/search/?pattern=wcwidth and https://release-monitoring.org/projects/search/?pattern=*wcwidth

I just saw that release-monitoring.org uses 0.9.1 which was released before the fix, so that explains it. I'll just do a small PR for my code simplification above.
