### ISSUE TITLE
Give some space to the columns in the log view

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/anitya#277]
Currently the columns in the log view are very closed to each other.

It would be good to give them some space.

Originally reported by @glensc in #268

**Comment by pypingou** [comment]
Note that this doesn't seem to happen to everyone, here is a screenshot for me:

![screenshot from 2016-03-19 14-06-06](https://cloud.githubusercontent.com/assets/1240038/13898745/115646f0-eddc-11e5-9c6a-63f07276b894.png)

**Comment by souravbadami** [comment]
@pypingou -- How will it be, if we add borders to the table ?
![screenshot from 2016-05-10 00 51 48](https://cloud.githubusercontent.com/assets/11073943/15125270/84985e6a-1649-11e6-9cc6-b5fea846f2c2.png)

**Comment by pypingou** [comment]
Looks good to me! :)
