### ISSUE TITLE
It tried cloning anaconda-docker-addon from fedoraproject instead of github

### ISSUE THREAD

**Issue by bcl** [fedora-infra/anitya#278]
Not sure why, it's setup as a github project.

https://bugzilla.redhat.com/show_bug.cgi?id=1323854#c1

**Comment by ralphbean** [comment]
It should've tried to clone this url:  http://pkgs.fedoraproject.org/cgit/rpms/docker-anaconda-addon.git

But instead it tried to clone this url:  http://pkgs.fedoraproject.org/cgit/docker-anaconda-addon.git

I just applied this fix to our prod config which should address it:  https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=e629f7a821129f2409601e183b5b797c651826d7

**Comment by ralphbean** [comment]
Please let us know if you see something like this again.  Thanks for reporting!
