### ISSUE TITLE
The distribution mapping cannot be removed

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#280]
The new hotness mistakenly assigned cucumber-core to cucumber-rails project [1]. Unfortunately, I can't remove the mapping now. This prevents me from fixing the situation.

[1] https://release-monitoring.org/project/4317/

**Comment by voxik** [comment]
This related to #279

**Comment by pypingou** [comment]
Let me fix this

**Comment by pypingou** [comment]
Done :)

**Comment by voxik** [comment]
Thx.

Should I understand it that this is admin only feature and won't be publicly accessible?

**Comment by pypingou** [comment]
Yes, there is the `flag` button to signal/make such request though.
