### ISSUE TITLE
Switch to updates.drupal.org for Drupal backend

### ISSUE THREAD

**Issue by daveol** [fedora-infra/anitya#281]
Drupal uses urls like:
https://updates.drupal.org/release-history/wysiwyg/6.x
to check for updates. The urls are formatted like:
```https://updates.drupal.org/release-history/<project>/<api version>```
and return an xml response with the release history, this will also solve all the [failed updates](https://release-monitoring.org/projects/updates/failed) that are related to drupal6 (I think).

**Comment by pypingou** [comment]
Sounds nice, thanks!
