### ISSUE TITLE
stackage backend broken

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/anitya#283]
@juhp it seems that the stackage backend is broken: https://release-monitoring.org/projects/updates/failed?name=&log=stackage want to look at it?

**Comment by pypingou** [comment]
@juhp I think I got it :) (cf the PR above, #284)

**Comment by juhp** [comment]
Thank you for noticing and fixing it!

Sorry I suspect it was probably me who broke it unknowingly on the Stackage side.
Do you want me to test it?

**Comment by pypingou** [comment]
@juhp if you could test the PR that would be awesome, but at least the unit-tests seem happy :)

**Comment by juhp** [comment]
I tested it locally and it seems to work fine: I am not sure that multiple regex's are really needed though. Maybe enough just to update the regex to the new html?

**Comment by pypingou** [comment]
I was wondering if all the pages changed or only some, since I didn't know I made it this way

**Comment by juhp** [comment]
Okay sure thanks - you're very quick. :)

They all changed: see fpco/stackage-server@07e6121.

**Comment by pypingou** [comment]
this got fixed :)

**Comment by pypingou** [comment]
hm, there is something odd, the stackage page is being inconsistent, one time the version number for LTS is linked, one time it isn't.

It's as if there are 2 servers running 2 different versions of the application

**Comment by pypingou** [comment]
Reported upstream at https://github.com/fpco/stackage-server/issues/182

**Comment by juhp** [comment]
It is possible that one of the server is out of sync yes - let me ask upstream about that...

We could also track Stackage via the Hackage pages though it would be less flexible since it only shows the latest LTS version but maybe it is good enough: the Stackage page still seems to be seeing some changes regularly... sorry for the trouble.

**Comment by pypingou** [comment]
It got apparently fixed upstream :)
