### ISSUE TITLE
Rebase helper failed.

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#292]
The ruby "new version available" ticket [1] contains following errors:

> Rebase helper failed.
> See logs and attachments in this bugzilla 'NoneType' object has no attribute 'get_rebasehelper_data'

and:

> Failed to kick off scratch build.
> 
> list index out of range

@phracek you probably want to take a look ....

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1330538

**Comment by jeremycline** [comment]
Hey @voxik, thanks for the report.

I believe this is a problem with https://github.com/fedora-infra/the-new-hotness and it looks like there's an issue open (https://github.com/fedora-infra/the-new-hotness/issues/119) so I'm going to close this. Feel free to open it back up if you think it's a problem on the Anitya side!
