### ISSUE TITLE
release-monitoring stops to work 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/anitya#303]
Hi, yesterday I found that anitya doesn't notify me on gammu , today , I have one confirmation with package debbuild  https://release-monitoring.org/project/10733/ , 9 day ago should notify version 16.5.0  , 2 days ago we got version 16.5.1 , and yesterday we got 16.5.2 ... 

https://admin.fedoraproject.org/pkgdb/package/rpms/debbuild/ is correctly configured , 
and https://bugzilla.redhat.com/buglist.cgi?component=debbuild&list_id=5182178&product=Fedora is empty .

**Comment by pypingou** [comment]
Well, closing this one since it seems it is a issue in the-new-hotness :)
