### ISSUE TITLE
the-new-hotness saw an update for python-selenium, but no rawhide version of the package could be found yet

### ISSUE THREAD

**Issue by mrunge** [fedora-infra/anitya#306]
not sure how to fix this, but rawhide clearly has this:

```
koji latest-build rawhide python-selenium
Build                                     Tag                   Built by
----------------------------------------  --------------------  ----------------
python-selenium-2.53.5-1.fc25             f25                   mrunge
```

**Comment by kavol** [comment]
FTR, I have the same problem with horai-ume-fonts

    $ koji latest-build rawhide horai-ume-fonts
    Build                                     Tag                   Built by
    ----------------------------------------  --------------------  ----------------
    horai-ume-fonts-641-1.fc25                f25                   kvolny

**Comment by jeremycline** [comment]
I think this is an issue on the [the-new-hotness](https://github.com/fedora-infra/the-new-hotness/) side of things so I'm going to close this. I'm trying to sort through the issues on both projects right now, but maybe this is https://github.com/fedora-infra/the-new-hotness/issues/84? If not, please open an issue over on the-new-hotness.
