### ISSUE TITLE
Version cleanup request

### ISSUE THREAD

**Issue by siwinski** [fedora-infra/anitya#311]
Please remove all 3.* versions from https://release-monitoring.org/project/3559/ -- that pkg is version 2 while https://release-monitoring.org/project/10811/ is version 3.

**Comment by pypingou** [comment]
Has the regex been adjusted for ignore 3+ versions?

**Comment by siwinski** [comment]
Yes

**Comment by pypingou** [comment]
Note that the regex isn't working at all but all the 3.+ versions have been removed

**Comment by siwinski** [comment]
> Note that the regex isn't working

That's just because there is not currently a 2.* version on the first page of the versions URL
