### ISSUE TITLE
"pkgdb says the maintainers are not interested in bugs being filed" despite monitoring activated

### ISSUE THREAD

**Issue by kavol** [fedora-infra/anitya#316]
Hi.
I've just received notification about new qmmp version, but another email says:

```
the-new-hotness saw an update for qmmp, but pkgdb says the maintainers are not interested in bugs being filed
    https://release-monitoring.org/project/4129/
```

despite at https://admin.fedoraproject.org/pkgdb/package/rpms/qmmp/ I see Monitoring: Bugs & builds checked, and I was getting bugs filed in the past.

**Comment by jeremycline** [comment]
Hmm, interesting. Can you re-open this against [the-new-hotness](https://github.com/fedora-infra/the-new-hotness/) if you're still seeing it? That's the component responsible for actually filing the issues.
