### ISSUE TITLE
prefix strips suffix also

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-infra/anitya#319]
https://release-monitoring.org/project/7254/

having `Prefix: v` removes `v` from suffix as well.

**Comment by pypingou** [comment]
Already fixed in https://github.com/chaiku/anitya/commit/ddbe8857b4ed789a3fc4a1dd3a71b6f5591d8c1b

Thanks for the report though :)

**Comment by ignatenkobrain** [comment]
@pypingou that's not correct fix.

If you have `2.1.0-dev` and you do `Prefix: v` you will end up with `2.1.0-de`

```python
if project.version_prefix and up_version.startswith(project.version_prefix):
    up_version = up_version[len(project.version_prefix):]
```

This is proper fix, I will send PR

**Comment by ignatenkobrain** [comment]
See https://github.com/ignatenkobrain/rpm-gitoverlay/blob/bec0f4ea77fbfcf000f4d6b3d076eb4d70a21a3b/rgo/utils.py#L117-L127

**Comment by akien-mga** [comment]
Confirmed in the currently deployed instance. Don't forget your PR @ignatenkobrain ;)

**Comment by pypingou** [comment]
Got a different one, simply using ``lstrip()`` :)
