### ISSUE TITLE
Suggestion: Use pip-tools to help keep dev environments consistent

### ISSUE THREAD

**Issue by ncoghlan** [fedora-infra/anitya#323]
[pip-tools](https://github.com/nvie/pip-tools) augments the standard requirements.txt model with a couple of new capabilities:

- a separate pip-compile step to convert broad requirements (suitable for setup.py) to pinned dependencies for exact versions (making upgrades to new versions of dependencies a conscious choice that goes through normal code review processes)
- a pip-sync command to make a virtual environment precisely match a given set of requirement files (including uninstalling or downgrading components if necessary)

If you're amenable to the idea, I'll submit a PR to set it up :)

**Comment by pypingou** [comment]
This would require a little more thought and discussion that I can give it right now, but my first reaction is that I don't really like pinning down version in requirements files. It seems to me to be the wrong way of fixing improper development practices/behaviors and as far as I remember we do not have any really bad upstream (breaking API, backward compat...) in our requirement list. Do you have one in mind?

**Comment by ncoghlan** [comment]
I think I filed this when I was still having trouble getting tox working - now that I found a workaround for the problems I was seeing there, I think tox (which I've configured to create a fresh virtualenv for each test run) is a better solution.

**Comment by ncoghlan** [comment]
Yeah, I like tox for local testing, as it also tests the sdist build process and the dependency declarations, in addition to make it easy to test Py2 compatibility even if I'm working primarily in Python 3 myself.

For the Jenkins setup, have you looked at enabling the GitHub integration plugin so it reports the status of the CI testing back to the PR?

**Comment by pypingou** [comment]
> For the Jenkins setup, have you looked at enabling the GitHub integration plugin so it reports the status of the CI testing back to the PR?

I believe it needs plugins on the jenkins side and I got a little too lazy to install and configure them
