### ISSUE TITLE
Backends `Drupal6` and `Drupal7` should not track `*-dev` releases

### ISSUE THREAD

**Issue by siwinski** [fedora-infra/anitya#325]
Backends `Drupal6` and `Drupal7` should not track `*-dev` releases.

See the following bugzilla bugs that were opened (that I will close out after I verify there really is no newer release or modify with a non-dev version if there is a newer release available):
- [drupal7-boxes-2.x-dev is available](https://bugzilla.redhat.com/show_bug.cgi?id=1327688)
- [drupal7-libraries-3.x-dev is available](https://bugzilla.redhat.com/show_bug.cgi?id=1327693)
- [drupal7-markdown-2.x-dev is available](https://bugzilla.redhat.com/show_bug.cgi?id=1327694)
- [drupal7-votingapi-3.x-dev is available](https://bugzilla.redhat.com/show_bug.cgi?id=1327695)
- [drupal7-workbench_moderation-3.x-dev is available](https://bugzilla.redhat.com/show_bug.cgi?id=1327696)

**Comment by Zlopez** [comment]
This is now possible to filter by using version filter. See https://anitya.readthedocs.io/en/stable/user-guide.html#version-filter
