### ISSUE TITLE
RFE: Check versions immediately after new project is added

### ISSUE THREAD

**Issue by bkabrda** [fedora-infra/anitya#333]
Hi, I'd like to be able to add projects programatically and then immediately query them for latest versions by the `by_ecosystem` endpoint. IIUC, right now I'd need to:
- create the project
- query it by the `by_ecosystem` endpoint to get its ID
- use the `/api/version/get` to trigger getting newest versions and get it

I'd like to be able to get version info from the `by_ecosystem` endpoint right after I add the project, so this would mean adding `check_release` to the UI endpoint that adds the new project. Does this make sense? I can send a PR if you think it's worth implementing.

**Comment by pypingou** [comment]
I'd be ok with a checkbox to `Check version right now` on the project creation page, but most often I think people do a few trials with the `test check` button before doing the actual check to ensure the regex/data returned is correct.

**Comment by bkabrda** [comment]
Cool, thanks. I'll send a PR sometime soon.
