### ISSUE TITLE
increase session length

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#340]
please increase session length on https://release-monitoring.org/ at least 8 hours, preferably 24 hours

this would avoid need for (slow) login procedure several times a day.

my typical rm.o usage is:
- check for package 1 updates
- update package 1
- check for package 2 update
- update package 2

between the steps there could have several hours passed, depending how difficult package update is.

**Comment by kentfredric** [comment]
+1, I've only been using this website casually for 3 days now and I'm already grossly irritated by "oh, great, I'm logged out again".

I personally don't see the need for *any* expiry time, and most websites that I use that require login don't constantly log me out "just because"

The only place that happens is the bank, and well, that's understandable.

**Comment by glensc** [comment]
indeed. i log in to github only after i've not used laptop for some weeks

**Comment by pypingou** [comment]
I've updated it to 24h: https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=b6ee08fac2a8502fd57e8f3c97c3fd1984b95f5b and deployed

**Comment by glensc** [comment]
Seems this has been reverted or new maintainers (admins) resetting to low defaults again?

The 24hour session was convenient, now I'm logged out after just a few hours. This is annoying (and chance the issue in the first place).

**Comment by Zlopez** [comment]
I didn't reverted it, so I'm not sure what happened.

**Comment by Zlopez** [comment]
It's set to 1 hour for last 2 years https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/release-monitoring/templates/anitya.toml#_11

**Comment by glensc** [comment]
Seems to me this is what happened:

1. @pypingou committed on 28 Oct 2016: https://github.com/henrysher/fedora-infra-ansible/commit/b6ee08fac2a8502fd57e8f3c97c3fd1984b95f5b
2. @jeremycline committed on 5 Dec 2017: https://github.com/henrysher/fedora-infra-ansible/commit/fce04f8ecefafd7e00b9848800f1e2b85ba084e3

The first commit set to 24h, the second commit sets to 1h, the second commit seems to override first commit setting (both files probably in place). there's no info where the 3600 came from @jeremycline changeset.

**Comment by Zlopez** [comment]
This was changed before I even started to work on Anitya and from this time there was no change. You can look at the ansible repo history of anitya.toml [here](https://pagure.io/fedora-infra/ansible/history/roles/openshift-apps/release-monitoring/templates/anitya.toml?identifier=main)

**Comment by jeremycline** [comment]
It should likely be changed back, my guess is when I was moving it to openshift I started with the defaults for some reason.

**Comment by glensc** [comment]
> EDIT: I can't find how to create a permalink for pagure.io, if I use commit in the url it just doesn't work.

@Zlopez:

1. navigate to commit, open last commit of file history: https://pagure.io/fedora-infra/ansible/c/086ec5dabc74152b9729e1a76746bc63efdfc3cf?branch=main
2. find "view as of commit" (it's an icon): https://pagure.io/fedora-infra/ansible/blob/086ec5dabc74152b9729e1a76746bc63efdfc3cf/f/roles/openshift-apps/release-monitoring/templates/anitya.toml
3. voila: https://pagure.io/fedora-infra/ansible/blob/086ec5dabc74152b9729e1a76746bc63efdfc3cf/f/roles/openshift-apps/release-monitoring/templates/anitya.toml#_11

indeed it's dumb that pagure has a custom url format or view file on a commit:

- history/roles/openshift-apps/release-monitoring/templates/anitya.toml?identifier=main
- blob/086ec5dabc74152b9729e1a76746bc63efdfc3cf/f/roles/openshift-apps/release-monitoring/templates/anitya.toml#_11

**Comment by Zlopez** [comment]
@glensc Thanks, I want's able to figure it out.

@jeremycline I will update the configuration to 24 hours again.

**Comment by Zlopez** [comment]
The session lifetime was changed to 24 hours on https://release-monitoring.org.

**Comment by glensc** [comment]
@Zlopez for posterity, perhaps share the commit(s) link(s) here. Previous commit links proved to be useful.

**Comment by Zlopez** [comment]
> @Zlopez for posterity, perhaps share the commit(s) link(s) here. Previous commit links proved to be useful.

https://pagure.io/fedora-infra/ansible/c/0e509bde1760f8f151497e5c130809567fdd4624?branch=main
