### ISSUE TITLE
delete rpm-spec-mode project

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#346]
i noticed someone has marked project to be deleted:

- "rpm-spec-mode" (https://github.com/bjorlykke/rpm-spec-mode/): https://release-monitoring.org/project/688/
- "rpm-spec-mode-DELETE-ME" (https://github.com/bjorlykke/rpm-spec-mode): https://release-monitoring.org/project/6172/

**Comment by pypingou** [comment]
Thanks, fixed :)
