### ISSUE TITLE
add project mapping improvement

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#347]
when you add project mapping, i.e
https://release-monitoring.org/project/1671/map

it's quite  common that the package name matches project name

please make the second text input it pre-filled with project name

![image](https://cloud.githubusercontent.com/assets/199095/18425116/4c7d945e-78bf-11e6-8fcf-9ed28cef8539.png)

**Comment by kentfredric** [comment]
Fwiw, when I find something that I need to add fresh that doesn't have an existing entry, I have a bookmarklet that does all the work for me:
```
javascript:(function($){$("#homepage").val("http://search.cpan.org/dist/"%20+%20$("#name").val()+"/");$("#backend").val("CPAN%20(perl)").trigger("change");$("#distro").val("Gentoo");$("#package_name").val("dev-perl/"%20+%20$("#name").val());}(jQuery))
```

Its obviously customised for Gentoo though.

But you might find yourself needing other vendor-specific defaults, and so a bookmarklet might be more appropriate than an integrated feature.

**Comment by glensc** [comment]
the feature i ask, makes easier nevertheless. it's easier to clear whole field (ctrl+a; backspace) than  copy text from page and paste it (mouse movement to find text on page, mouse_button_1_down, mouse drag; mouse_button_1_release; ctrl+c)
