### ISSUE TITLE
Sourceforge backend does not work with MP3Gain

### ISSUE THREAD

**Issue by kavol** [fedora-infra/anitya#350]
SSIA ... I've tried to add MP3Gain to monitoring (https://release-monitoring.org/project/12077/), but I am unable to make it work - all I'm getting is this:

Version found: src

Going to 'About' page, I do not see any thorough instructions how to use the Sourceforge backend, and I can't find any other help elsewhere on the monitoring site.

**Comment by pypingou** [comment]
I fixed the project using the custom backend and tweaking the regex a little :)

**Comment by kavol** [comment]
Thanks a lot, but I'd prefer fix in the backend - there is nothing special about MP3Gain download page, IMHO ... or am I mistaken?

**Comment by pypingou** [comment]
> I'd prefer fix in the backend - there is nothing special about MP3Gain download page, IMHO ... or am I mistaken?

You are welcome to look into it if you have the time, I'll be happy to review and test your changes :)
