### ISSUE TITLE
Epoch support for lower-number newer versions?

### ISSUE THREAD

**Issue by akien-mga** [fedora-infra/anitya#352]
I noticed that the [glew](https://release-monitoring.org/project/7878/) page listed development snapshots (like 20160708) as latest versions instead of the recent 2.0.0 (and before that 1.13.0) releases, due to them being mixed up in SourceForge: https://sourceforge.net/projects/glew/files/glew/

I therefore switched the backend to GitHub which has only the stable releases: https://github.com/nigels-com/glew/releases

But anitya will obviously still see 20160708 > 2.0.0: https://release-monitoring.org/project/7878/
and the logs show:
> Something strange occured, we found that this project has released a version "2.0.0" while we had the latest version at "20160708" 

Is there already a solution around this, and if not, should there be one? (e.g. an "Epoch" system to allow overriding the direct version number comparison).

**Comment by pypingou** [comment]
I removed the old versions so this should be good now, thanks for the report! :)

**Comment by akien-mga** [comment]
Thanks, so it has to stay a manual process on the sysadmin end for now I guess?

**Comment by pypingou** [comment]
There is a feature in the UI for admins to do it nicely, but yes, removing invalid versions can only be done by admins, you can contact them either with a ticket here or using the `flag` button in anitya.
