### ISSUE TITLE
BitBucket backend non-functional since platform behaviour change

### ISSUE THREAD

**Issue by akien-mga** [fedora-infra/anitya#354]
*Edit:* Looks actually more a bug due to a BitBucket change than a missing feature, see comments below.

----

The current BitBucket backend seems to just parse the download page (e.g. https://bitbucket.org/libtcod/libtcod/downloads) to try to infer the latest tarball upstream my have put there.

Like the GH backend, it should be able to parse tags (e.g. https://bitbucket.org/libtcod/libtcod/downloads?tab=tags) and use those for the latest release.

I haven't checked the backend plugin to see if it's actually supposed to be implemented and is a bug, or if it's a missing feature. But with the above example, anitya gives me:
```
Unable to retrieve the latest version from upstream!
ERROR: libtcod: no upstream version found. - https://bitbucket.org/libtcod/libtcod/downloads -  class="name">([^<]*[^tip])</td
```

**Comment by akien-mga** [comment]
Currently worked around on https://release-monitoring.org/project/12266/ with this custom regex on the tags page: `get\/([0-9]*\.[0-9]*\.*[0-9]*).tar.bz2`.

**Comment by jirutka** [comment]
This is quite bad regexp, better is `get\/([0-9]+(?:\.[0-9]+)+)\.tar\.bz2`.

**Comment by akien-mga** [comment]
Still, I can't get how the current BitBucket backend is supposed to work at all.

**Comment by pypingou** [comment]
it was working at the time bitbucket loaded the three tabs at the same time, when clicking on one was just selecting which one was shown and which were hidden.
They since changes that behavior which broke our plugin.

**Comment by pypingou** [comment]
Feel free to review the PR linked to above here :)
