### ISSUE TITLE
GitHub backend: Erroneous version check with prefix?

### ISSUE THREAD

**Issue by akien-mga** [fedora-infra/anitya#355]
I noticed a potential version comparison bug in the GitHub backend with a defined prefix: see https://release-monitoring.org/project/11731

The tags it parses are (IINM) all of the form `evdev-$version`: https://github.com/Tangent128/lua-evdev/tags

Still, with anitya using the GH backend and `evdev-` as prefix, it finds `1.0` as the current latest version, instead of `2.2.1`. (There is an occurrence of 2.2.1 in the version history because this entry used to use a custom regex to parse the version - probably due to the bug I'm describing here).

Once stripped of the prefix, I would expect that 2.2.1 > 1.0.

**Comment by pypingou** [comment]
Trying to replicate this one locally to see if the new code fixes it or if I can track it down.

**Comment by pypingou** [comment]
Ok this was fixed in git, when we move stripping the prefix earlier in the process.

I'm going to close this one for now, let's re-open after the next release is deployed.

**Comment by pypingou** [comment]
0.10 is released and deployed and this bug is indeed fixed :)
