### ISSUE TITLE
INTERAL SERVER ERROR via /project/new

### ISSUE THREAD

**Issue by kentfredric** [fedora-infra/anitya#367]
Visiting /project/new  gives the standard Apache 500 

Curiously, the /logs  path shows no log entries like it typically does when I'm logged in, but the presence of the "log out" button indicates it considers me logged in.

I suspect there's some auth/cookie/session desynchronization happening here where it considers me logged in, but the data about _who_ is logged in is somehow expired.

**Comment by akien-mga** [comment]
Same error on /project/$id/edit.

**Comment by pypingou** [comment]
Thanks for the reports, I fixed the /new and /edit pages, the logs are showing fine for me though :s

**Comment by akien-mga** [comment]
The logs are empty for me too (I had never tried the feature so far though, so I don't know how it should be normally :p)

**Comment by pypingou** [comment]
Ah I know, we changed the logging to be relying on the user's openid instead of the user's email as some people were concerned about the leak of emails in fedmsg.
So we should adjust the logs to show for both the user's openid and the user's email.

**Comment by jeremycline** [comment]
@pypingou did this get fixed? It looks like https://github.com/fedora-infra/anitya/commit/7664245a4a0138972faef3950334a917da36c56d maybe fixed it?

**Comment by pypingou** [comment]
@jeremycline yes, I think we fixed it

Let's close :) thanks for the heads-up
