### ISSUE TITLE
A bug was filed against mongoengine saying there was a newer version when there wasn't

### ISSUE THREAD

**Issue by bowlofeggs** [fedora-infra/anitya#375]
This bug got filed against python-mongoengine, saying there was a new upstream release of 0.10.6:

https://bugzilla.redhat.com/show_bug.cgi?id=1389902

0.10.6 came out in January, and Fedora 24, 25, and Rawhide already have it.

**Comment by pypingou** [comment]
That's more likely an issue in the-new-hotness as anitya doesn't do anything with bugzilla :)

**Comment by bowlofeggs** [comment]
Cool, I re-filed it as https://github.com/fedora-infra/the-new-hotness/issues/131

**Comment by pypingou** [comment]
Thanks :)
