### ISSUE TITLE
custom backend: please fix multiple groups support

### ISSUE THREAD

**Issue by yarda** [fedora-infra/anitya#382]
I.e. support to interpret:
3_0_1
by regex:
(\d*)_(\d*)_(\d*)
Which would result in e.g.:
[(u'3', u'0', u'1')]
Which in turn would be interpreted as:
3.0.1

I think this would allow more flexible matching. E.g. uhd upstream has some really strange version presentation, e.g.:
release_003_010_001_000

The following regex:
release_[0]?[0]?(\d+)_[0]?[0]?(\d+)_[0]?[0]?(\d+)_[0]?[0]?(\d+)
would turn it into nice:
3.10.1.0

Of course upstream could fix it, but in case they cannot/don't want, etc. such flexibility in anitya
would be great.

**Comment by yarda** [comment]
Hmm, it seems there is already support for it in the code:
https://github.com/fedora-infra/anitya/blob/master/anitya/lib/backends/__init__.py#L334-L336

Now investigating why it doesn't work for me.

**Comment by yarda** [comment]
Hmm, no idea what's wrong, it seems OK in the code, I created the following:
https://release-monitoring.org/project/12572/edit
By clicking on "test check" or "full check" nothing happens. Maybe there is different bug.

**Comment by yarda** [comment]
Also the following appeared in Fedora when I tried to enable the version check in pkgdb: hotness tried to map uhd to an upstream project, but failed:  "Could not determine backend for http://code.ettus.com/redmine/ettus/projects/uhd/wiki" http://code.ettus.com/redmine/ettus/projects/uhd/wiki    ( triggered by https://apps.fedoraproject.org/notifications/jskarvad.id.fedoraproject.org/irc/25141 )

**Comment by jeremycline** [comment]
@yarda Hey, thanks for reporting this. I think this might have been a bug that was in 0.10.0 and was fixed in 0.10.1. Right now I'm able to retrieve version "3.10.1.0" from https://release-monitoring.org/project/12572/ so I'm going to close this. Please re-open this issue if it's still a problem somewhere!
