### ISSUE TITLE
Debian project backend adds ".orig" to the version number

### ISSUE THREAD

**Issue by ktdreyer** [fedora-infra/anitya#398]
The Debian project backend should strip the ".orig" from the version numbers.

reprepro is an example of a package that is using the Debian backend: https://release-monitoring.org/project/12798/ . It currently shows the latest version number as `5.1.1.orig` rather than `5.1.1`

**Comment by jeremycline** [comment]
Thanks for reporting this!

Indeed, it appears that the [Debian tarballs](http://ftp.debian.org/debian/pool/main/r/reprepro/) are in the format ``<name>_<version>.orig.tar.gz`` (or at least, all the ones I looked at are in the format). This doesn't look like a recent change, either, so I'm wondering if this ever worked. It seems to be referenced throughout the [Debian packager guide](https://www.debian.org/doc/manuals/maint-guide/upload.en.html#option-sa). The fix should be a simple regex modification, I think.

**Comment by jeremycline** [comment]
I was very surprised to discover the unit tests [assert](https://github.com/fedora-infra/anitya/blob/0.10.1/tests/test_backend_debian.py#L85) that the ``orig`` portion is part of the version. @pypingou do you happen to know why this is the case? It seems wrong to me.

**Comment by pypingou** [comment]
@jeremycline most likely an oversight or left over from when we moved to cnucnu to anitya

**Comment by ktdreyer** [comment]
Thanks!
