### ISSUE TITLE
project search exclude

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#43]
wanted to search for "ruby" package (the ruby language), the pattern was modified to be "ruby*"
and they gave me 11 pages of rubygems, tried exclude with minus, that gave nothing:

https://release-monitoring.org/projects/search/?pattern=ruby*+-rubygems

please implement some advanced filtering or exact match

**Comment by pypingou** [comment]
Ok I have two approached possible for this ticket:

* https://github.com/fedora-infra/anitya/compare/exact_match
We remove doing ``pattern*`` search by default. This will work and do exact match by default but this also means we are changing the default behavior.

* https://github.com/fedora-infra/anitya/compare/rework_search
If the pattern starts with a `!`, then do an exact match search, keeping the current default behavior.

**Comment by ralphbean** [comment]
This might prove to be an interesting third option:  http://www.postgresql.org/docs/8.3/static/textsearch-intro.html#TEXTSEARCH-MATCHING

**Comment by pypingou** [comment]
Well, isn't the question here about being able to do exact match search rather than text search?

**Comment by ralphbean** [comment]
Yes.  But textsearch might be a more flexible method for specifying searches (and it might return results in a nicer order).

**Comment by pypingou** [comment]
Ever played with textsearch? In sqlalchemy?

There seems to be some support: http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#full-text-search

**Comment by pypingou** [comment]
So I guess there are two issues here:
* improve the search by using textsearch (``table.c.column.match(pattern)`` in sqlalchemy)
* allow perfect match search

**Comment by pypingou** [comment]
I just did some testing of using ``match`` vs ``ilike`` when doing the search:

````
- Packages.package_name.match('python')
- Project.name.match('python')
  -> 451 projects found

- Packages.package_name.ilike('python%')
- Project.name.ilike('python%')
  -> 454 projects found
  
- Packages.package_name.ilike('python')
- Project.name.ilike('python')
  -> 454 projects found
````

**Comment by ralphbean** [comment]
What is the first result?  is it 'python'?  :)

**Comment by pypingou** [comment]
In both case it's not (after removing the order_by constraint)

**Comment by ralphbean** [comment]
Bummer.  I was hoping textsearch would provide the "best" match first like xapian does.
