### ISSUE TITLE
List fedora-messaging topics in Anitya's own documentation

### ISSUE THREAD

**Issue by ncoghlan** [fedora-infra/anitya#453]
The list of Anitya fedmsg topics is currently only described in the Fedora infrastructure documentation: http://fedora-fedmsg.readthedocs.io/en/latest/topics.html

Since release-monitoring.org may technically cover multiple distros, it would be good to cover those in the Anitya documentation as well.

A possible starting point would be to just link to the relevant Fedora docs from the Anitya docs.

**Comment by ncoghlan** [comment]
An alternative would be to move the list of Anitya topics into the Anitya docs, and then cross-link that from the Fedora-Infrastructure docs - the advantage of that approach would be that any PRs that change the messages could change the documentation at the same time.

**Comment by abitrolly** [comment]
Or put the meta format to blockchain - a persistent alternative to `fedmsg`.

**Comment by Zlopez** [comment]
The Anitya is now using `Fedora messaging` instead of `fedmsg`, but we should still document the topics used.
