### ISSUE TITLE
Update the access token usage documentation for the v2 API

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/anitya#486]
The work in #401 added support for OpenID Connect, which is built on top of OAuth 2.0 (RFC 6749) and Bearer Token Usage (RFC 6750). While perusing the Bearer Token RFC, I noticed it states passing the access token SHOULD NOT be used unless it is impossible to transport the access token using the other two options (The ``Authorization`` header or the HTTP form-encoded body parameter).

I poked around in flask-oidc and it will search the request in the correct order (``Authorization``, form, then query parameter), but we only document the query parameter method.

Furthermore, if we do accept a query parameter, the RFC states that we SHOULD add a ``Cache-Control`` header with the ``private`` option, which I don't believe we do.

I think we should update the documentation to use the ``Authorization`` header approach, and we should push a patch upstream to flask-oidc to automatically attach the correct ``Cache-Control`` header if the token arrived via a query parameter.

**Comment by jeremycline** [comment]
I think it's still valid in that we should favor the header style in the documentation, although we have our own API tokens rather than using just Fedora's OIDC (since otherwise you'd *have* to have a Fedora account to use the API)

**Comment by Zlopez** [comment]
I'm closing this, because Anitya is no longer using `flask-oidc`, but instead we are using `flask-login` for token authentication.
