### ISSUE TITLE
[RFE] Please add a "preview" mode

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/anitya#491]
It would be nice to have a preview mode, which does the version checks, but does not send notifications.

**Comment by Zlopez** [comment]
This needs a new logic for project checking working with data that aren't saved in the database yet.

**Comment by Zlopez** [comment]
## Implementations details
To make this work we need to implement few things:

1. Add a new button on https://github.com/release-monitoring/anitya/blob/master/anitya/templates/project_new.html that will do the test check
2. Re-implement `check_project_release` (https://github.com/release-monitoring/anitya/blob/master/anitya/lib/utilities.py#L76) so we could call it with specific arguments and without access to database
3. Add a new UI method to https://github.com/release-monitoring/anitya/blob/master/anitya/ui.py that will read the form fields and call the above method
