### ISSUE TITLE
GNOME driver does not catch latest version

### ISSUE THREAD

**Issue by glensc** [fedora-infra/anitya#54]
current implementation of gnome driver finds only major version,
but not actual full release, which tarballs are in subdir

ex: https://release-monitoring.org/project/5390/
finds 3.14 from https://download.gnome.org/sources/gnome-power-manager/ dir
but 3.14 latest is 3.14.1 as of this writing: https://download.gnome.org/sources/gnome-power-manager/3.14/

there's cache.json in each project dir: https://download.gnome.org/sources/gnome-power-manager/cache.json

maybe parse that instead?

contains for example: 
```json
3.14: [
"LATEST-IS-3.14.1"
],
```

**Comment by ralphbean** [comment]
> If the cache.json is always present, that would make things much easier indeed.

Either way, we can look for the ``cache.json`` file first to see if it's there.  If it is, then use it.  If not, fall back to the way things are currently done.

**Comment by pypingou** [comment]
Implemented in https://github.com/fedora-infra/anitya/tree/gnome_cache but tbh I am not sure I like it, it seems to make the code more complex than anything.

**Comment by ralphbean** [comment]
Well, you could break out the part inside the ``try`` block into a function with a name to help consolidate it -- make it easier to read:

```python
try:
    use_gnome_cache_json()
except Exception as e:
    log.warning(e)  # Should almost certainly log something about the exception, even if its benign.
    use_gnome_regex()
```

**Comment by glensc** [comment]
(+1) to ralph suggestion
