### ISSUE TITLE
Link Fedora package_name to package info page

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/anitya#557]
![image](https://user-images.githubusercontent.com/8781107/40258660-860b8410-5b1c-11e8-9c1e-c0da79ae383b.png)

Would be good to go directly to package page for specified distribution.

**Comment by abitrolly** [comment]
1. * [ ] Extend https://github.com/release-monitoring/anitya/blob/52d01219b58ba6c945a07230920a9f8b01b4cd4b/anitya/db/models.py#L158 with `package_info_url = sa.Column(sa.String(200), nullable=True)`

2. * [ ] Create migration

3. * [ ] Update edit forms https://github.com/release-monitoring/anitya/blob/52d01219b58ba6c945a07230920a9f8b01b4cd4b/anitya/templates/distro_edit.html#L12 and https://github.com/release-monitoring/anitya/blob/52d01219b58ba6c945a07230920a9f8b01b4cd4b/anitya/templates/distro_add.html#L12

4. * [ ] Update project view list

**Comment by abitrolly** [comment]
`package_info_prefix` for Fedora - https://apps.fedoraproject.org/packages/ so https://apps.fedoraproject.org/packages/zeal is a full package name.

**Comment by jeremycline** [comment]
Indeed, this would be nice. Something to note, though, is that some distributions are made up of several repositories. Arch, for example, has core, extra, community, and more. Gentoo organizes its packages by categories which one could roughly map to repositories, I suppose. Debian has the main repository and then -backports and -backports-sloppy.

We could try to hack around the different repositories a bit with the current modeling, but perhaps it'd be better to adjust the database models so a Distribution is composed of one or more Repositories, which have zero or more Packages. The package index URL would live on the Repository object. Thoughts?

**Comment by abitrolly** [comment]
Thoughts are that repo subdivision is distro-specific. When people search for a package, they don't use repo or category. Better keep this simple and link to this human-oriented interface.
