### ISSUE TITLE
Prevent creation of duplicit projects

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-infra/anitya#584]
We seem to have 2 entries for "nest". Could one be removed please?
 
- https://release-monitoring.org/project/16702/
- https://release-monitoring.org/project/17682/ (Please remove this one, I added it again by mistake :disappointed: )

**Comment by Zlopez** [comment]
This is definitely a bug, we shouldn't allow creating projects with same name and same backend.

**Comment by pypingou** [comment]
The url are different, that's why it was allowed :)

**Comment by Zlopez** [comment]
I know, the homepage shouldn't be part of primary key.

**Comment by pypingou** [comment]
On Wed, Aug 22, 2018 at 01:44:37AM -0700, Zlopez wrote:
>    I know, the homepage shouldn't be part of primary key.

It is necessary considering how much projects have the same name while being
different (redis the database versus redis the python module, versus redis the
ruby module...).
(The backend may help here but it wasn't there originally)

**Comment by sanjayankur31** [comment]
Yeh, maybe a warning that says something on the lines of "We found similarly named projects already in our list: a, b, c. Is this one of them?" would be quite helpful. Thanks :)

**Comment by pypingou** [comment]
On Wed, Aug 22, 2018 at 02:20:14AM -0700, Zlopez wrote:
>    When I think about it, it's probably not a bug, but we should at least
>    show some warning, that there is project with the same name and same
>    backend.

:+1: :)

**Comment by Zlopez** [comment]
There is already notification about projects with same name, but it should be more strict.
Maybe asking again if you really want to submit project, when similar name is found.

**Comment by jeremycline** [comment]
One thing to help with this would be to modify the URL used as the ecosystem in a predictable way (without changing the version used as the homepage). Right now a lot of the dupes come from http vs https and a trailing slash (or not). If the ecosystem was always HTTPS and included a trailing slash that would catch a lot.

**Comment by Zlopez** [comment]
Yes, but this is not true for every ecosystem. Some backends aren't using any ecosystem, so the homepage is set as ecosystem.
And I'm not sure if it is good to presume, that every url will be HTTPS.

Maybe it will be better to do the validation for every backend.
Like using the repository_url (not homepage) as primary key and validate it by javascript on frontend.
Something like this:
gitlab - url must be validated as `https://gitlab.[hostname.]com/<owner>/<repo>`
github - url must be validated as `https://github.com/<owner>/<repo>`
Than if you already have this project, you will see it almost immediately and you could stop the user from creating duplicate project.

This will probably not work for custom backend, because it is less strict.

I need to check if this is possible for every other backend.

**Comment by jeremycline** [comment]
>Yes, but this is not true for every ecosystem. Some backends aren't using any ecosystem, so the homepage is set as ecosystem.
And I'm not sure if it is good to presume, that every url will be HTTPS.

Yes, the homepage should not be presumed to be HTTPS, but the URL-is-a-ecosystem is a hack to namespace generic projects that aren't part of a real ecosystem and allow for the uniqueness constraint on (ecosystem, name). The value assigned to the ecosystem is never used as a URL, so some normalization should be safe there.

**Comment by Zlopez** [comment]
As I understand it, we should use normalized homepage as ecosystem.
Convert every homepage without ecosystem to something like this:
`https://<hostname>/<path>/`

This means every http will be in ecosystem saved as https and every URL shall have trailing `/`.

I think this should be enough to have some kind of normalization.

But still the warning for same project name should be shown on submit to prevent addition of same project in different ecosystems. For example `Pypi` and `Github`.

**Comment by jeremycline** [comment]
Agreed, I think that will also help

**Comment by Zlopez** [comment]
## Implementation details
This issue needs few changes in various places:

1. Remove `name, homepage` key from `Project` model - https://github.com/release-monitoring/anitya/blob/master/anitya/db/models.py#L261. This isn't needed anymore.
2. Normalize homepage before saving it to ecosystem to `https://<hostname>/<path>/`. This could be done here - https://github.com/release-monitoring/anitya/blob/master/anitya/db/events.py
3. Add warning window or page when saving project and projects with similar name were found. Ideally clickable, so the user could open them and check if this is really the same project. There is `show_similar_projects` function in javascript in `project_new` template https://github.com/release-monitoring/anitya/blob/master/anitya/templates/project_new.html#L251
4. We should add guidelines to name project same as upstream name.

**Comment by glensc** [comment]
here's one now with same url:

- "proj" (https://proj.org): https://release-monitoring.org/project/21570/
- "PROJ" (https://proj.org): https://release-monitoring.org/project/9463/

**Comment by glensc** [comment]
duplication due older url (is redirected now)

Possible matches:
- "incremental" (https://github.com/twisted/incremental): https://release-monitoring.org/project/19663/
- "python-incremental" (https://github.com/hawkowl/incremental): https://release-monitoring.org/project/15162/

**Comment by Zlopez** [comment]
I got better idea for detecting duplicates in #1752
