### ISSUE TITLE
Allow removing more versions at once

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#623]
It will be easier for administrators if they could remove multiple project's versions at once.

This will allow much faster solving of flagged projects.

**Comment by cheese** [comment]
[OT] How to apply administratorship? I flagged multiple projects but none has been worked on.

**Comment by Zlopez** [comment]
@cheese I get through the flagged projects on friday, it depends what issue you had.
If you wanted to remove some versions, I can do this, but right now it doesn't matter. The check function is now retrieving every version.

I want to add some mechanic that will prevent this in the future, so the project will not retrieve versions that you don't want.

See https://github.com/release-monitoring/anitya/issues/753

**Comment by Zlopez** [comment]
If you want to be admin in Anitya, just give me your e-mail you are using in Anitya and I can give you administrator rights.

**Comment by cheese** [comment]
I use FAS to login. My FAS id is cheeselee. The email is cheeselee@fedoraproject.org or robinlee.sysu@gmail.com.

**Comment by Zlopez** [comment]
@cheese I gave you the admin rights on release-monitoring.org

If you have any question ask on #fedora-apps freenode channel or here.

**Comment by cheese** [comment]
OK. Thanks. I try to fix issues I flagged to get started.
