### ISSUE TITLE
GitHub repo is intollerant

### ISSUE THREAD

**Issue by yarons** [fedora-infra/anitya#645]
Let's say I have a GitHub project I want to add.

I'm typing yarons/MyApp as the GitHub repo.
Everything works fine.

If I'm adding / at the beginning or at the end I'm getting an error after trying to process the request by the server.

I was thinking: Maybe we can save some server resources if we won't pass such requests to the server, sanitizing the input and removing leading or trailing characters such as / and possibly other characters will save time and server resources.

Another option would be showing a message saying that there's a trailing or leading / while having the option to fix it automatically or pass it to the server as is if it should be like that.

So the options are:
/yarons/MyApp/
Automagically remove /.
Show a warning message with Autofix, Return to edit manually and Ignore options.

This possibly happens in other backends (Bitbucket/GitLab), I didn't check.

Thank you!

**Comment by Zlopez** [comment]
I already have issue created for this - https://github.com/release-monitoring/anitya/issues/620

**Comment by yarons** [comment]
So can we close this one?
