### ISSUE TITLE
https doesn't work (Terena CA) with "Check now" button

### ISSUE THREAD

**Issue by valtri** [fedora-infra/anitya#70]
There is not working fetch over SSL at release-monitoring.org. The URL is:
  https://code.soundsoftware.ac.uk/projects/qm-dsp/files

Some intermediate certificates in Terena CA has been changed recently, so maybe just upgrading ca-certificates could help?

**Comment by ralphbean** [comment]
> OK, it looks like this problem is only with the "Check now" button.

The "Check now" button works for me on qm-dsp.  Do you still see this issue @valtri?

**Comment by tomspur** [comment]
The failure of 'http://dl.hexchat.net/hexchat/' might be related to this:
```
  File "anitya.git/anitya/lib/backends/__init__.py", line 260, in call_url
    return requests.get(url, headers=headers)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 599, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 192, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'dl.hexchat.net' doesn't match either of 'ssl2000.cloudflare.com', 'cloudflare.com', '*.cloudflare.com'
```

**Comment by pypingou** [comment]
Most of the failure with https are related to invalid certificate(s)

**Comment by valtri** [comment]
The "Check now" button doesn't show there, but that's not critical (it may be feature - check is not needed when checked recently). The update check of qm-dsp looks OK. I would consider this part as solved. :-)

The hexchat: there is used http:// at https://release-monitoring.org/project/1313/. The certificate looks updated (it contains *.hexchat.net in altnames), maybe it could work now.

**Comment by pypingou** [comment]
> The hexchat: there is used http:// at https://release-monitoring.org/project/1313/. The certificate 
> looks updated (it contains *.hexchat.net in altnames), maybe it could work now.

Apparently this does not cover dl.hexchat.net:
``
requests.exceptions.SSLError: hostname 'dl.hexchat.net' doesn't match either of 'ssl2000.cloudflare.com', 'cloudflare.com', '*.cloudflare.com'
``

**Comment by tomspur** [comment]
It is strange, that `chromium` and `firefox` accept this certificate, but `curl` and `python-requests` don't...

**Comment by pypingou** [comment]
The pull-request mentioned above fixes this issue by allowing to make insecure http calls.
