### ISSUE TITLE
Remove fedmsg related things

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#737]
Go through dependencies, configuration, ansible and remove anything related to fedmsg.
After conversion to fedora messaging this is no longer needed.

**Comment by PureTryOut** [comment]
The fact that the documentation still points to `fedmsg` everywhere confused the hell out of me when I found out it was deprecated and `fedora-messaging` should be used instead.

**Comment by Zlopez** [comment]
I need to give higher priority to this ticket.
