### ISSUE TITLE
add project: some of the fields are hard to guess

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-infra/anitya#748]
Real examples would be very nice.

I.e. I have no idea what should I write into: project name, version url, version prefix, regex, Distro & Package.

**Comment by Zlopez** [comment]
@TomasTomecek In current version of Anitya in production is a [bug](https://github.com/release-monitoring/anitya/issues/714), this is already fixed on stg.release-monitoring.org. The name of the fields should change based on selected backend. 

But real life examples in documentation should be nice.
