### ISSUE TITLE
Separate stable releases from unstable ones

### ISSUE THREAD

**Issue by cheese1** [fedora-infra/anitya#753]
It would be great to be able to **exclude** specific patterns.
Sometime one does not want to get notified of alpha,beta,pre- and test-releases, release-candidates....

it worked in such a way with cnucnu and i always miss that feature.
i for my part almost never package unstable software and i think most packagers do so.

**Comment by Zlopez** [comment]
I actually thought about this feature recently. I just need to think how to implement this. Currently I have few ideas in the head:

1. Let this be handled by the version scheme - it should mark them as pre-release versions
2. Let this on user - add new field, where user could specify, which versions should be ignored, every version containing any string in this field will be ignored.
3. Combine the two options above, let something be handled by version scheme and rest by user.

Either case will help with false notifications about new versions and will made versions on the project more readable.

**Comment by cheese1** [comment]
i think a way to accomplish that would be:
* have a list of "stable" versions  (the full list minus alpha, beta,...)
* have a second list of all versions (we already have that)
* have a predefined regex to define the "minus"-list, it should be possible to redefine that regex

new tickets (for fedora) should be triggered for the "stable" list, in my opinion.
the output via api should have a new line version_stable and a new array versions_stable, eg:

{
  ...
            "updated_on": 1482495004.0,
            "version": "2.12-alpha",
            "version_stable": "2.10",
            "version_url": "zero-install",
            "versions": [
                "2.12-alpha",
                "2.11-beta",
                "2.10",
                "2.9.1",
                "2.9",
                "2.8",
                "2.7"
            ],
            "versions_stable": [
                "2.10",
                "2.9.1",
                "2.9",
                "2.8",
                "2.7"
            ]
        }

**Comment by Zlopez** [comment]
This sounds like a good idea. I will look at it more closely, when I start working on this issue.

**Comment by yarda** [comment]
I have the same problem with Tcl package in Fedora (https://bugzilla.redhat.com/show_bug.cgi?id=1488695). I just want bugzilla reports about stable releases, not alphas, but it seems:
* I cannot change the regex in anitya, becase there are already mappings for more downstreams and I don't want to break them (maybe they are interested in getting notifications about alphas)
* Adding new project like e.g. tcl-stable with different regex could help, but I consider it as a dirty hack which should be avoided

So at the moment there is Fedora bugzilla about development version of the package, but I am missing notifications about stable updates (this is what recently happened in (https://bugzilla.redhat.com/show_bug.cgi?id=1488695).

**Comment by Zlopez** [comment]
This needs to be added as a monitoring option for Anitya (something like "Monitoring - stable"). So we could only report versions that the maintainer is really interested in. This way we don't brake the already setup projects and it will affect only Fedora maintainers.

**Comment by Zlopez** [comment]
Thanks to #898, the user will be able specify filters that will be used on any retrieved versions. This will allow user to ignore some of the versions released by upstream.

I still need to look at the option of marking the versions as pre-release and sending the message containing separated stable versions.

**Comment by Zlopez** [comment]
Here is the list of changes that needs to be done to implement this ticket:
* Add pre-release flag to `ProjectVersion` object
* Add pre-release pattern field to `Project` (same as in https://github.com/fedora-infra/anitya/pull/944)
* Add property `stable_versions` to `project` to get versions without pre-release versions
* Add new field to project edit page (with tooltip), which allows you to set the pre-release pattern (same as in https://github.com/fedora-infra/anitya/pull/944)
* Add new field to `create_project` and `edit_project` in `utilities.py` (same as in https://github.com/fedora-infra/anitya/pull/944)
* Change `new_project` and `edit_project` UI methods (same as in https://github.com/fedora-infra/anitya/pull/944)
* Change `check_project_release` method in `utilities.py` to check whether the version is pre-release (this will be done either by version schema itself or by using the pre-release pattern)
* Add field `versions_stable` to `ProjectVersionUpdated` message
