### ISSUE TITLE
Coro is not monitored

### ISSUE THREAD

**Issue by eseyman** [fedora-infra/anitya#77]
The maintainer of Coro in Fedora is not notified when a new version of the perl module is released on CPAN. Version 6.42 was released last week and no bug was filed in bugzilla.redhat.com .

**Comment by pypingou** [comment]
That's to be expected as the-new-hotness is not in prod yet, so while anitya finds new releases they are not (yet) reported on bugzilla.

We have been talking with @ralphbean about moving the-new-hotness in prod, maybe later this week so hang tight, it's coming ;-)

**Comment by ralphbean** [comment]
It's in prod as of yesterday.

I'm going to close this bug, since as @pypingou said the scenario was expected.  If future releases of Coro are not reported to bugzilla, please open a new ticket.
