### ISSUE TITLE
Anitya should report every found version, not only latest

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#774]
Anitya is currently reporting only newest version. This should be changed to allow sending more than one version in the `anitya.project.version.update` topic. 

For this to work we need to do some changes:
1. Upstream version needs to be changed to array in `anitya.project.version.update` topic
2. There also needs to be change in the-new-hotness to be able to work with this

**Comment by voxik** [comment]
Just FTR, this would be useful for Fedora modularity, which allows to have supported multiple stable streams for package, e.g. Ruby 2.4, 2.5 and 2.6 at the same time.

**Comment by Zlopez** [comment]
@voxik It shouldn't be a problem to just add `Fedora Modules` distribution to Anitya, so we map packages to modules.
But to make this work properly in the-new-hotness could prove difficult. I will create a issue on the-new-hotness for it.
