### ISSUE TITLE
Monitor vagrant- packages

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#78]
I'd like to have automatically monitored all vagrant- packages. They are completely the same to rubygem- packages.

BTW it would be nice to have some generic way how to create/update the regexps for such generic packages.

**Comment by voxik** [comment]
Actually there are some backends, so may be I can create new one for vagrant.

**Comment by ralphbean** [comment]
> Actually there are some backends, so may be I can create new one for vagrant.

Let us know if that works for you!

**Comment by voxik** [comment]
Looking into the-new-hotness, which seems to be responsible for importing new packages into Anytia, this probably works just fine :clap:

https://release-monitoring.org/api/projects/?pattern=vagrant*

There are just missing few packages. A opened separate ticket to fix this:

https://fedorahosted.org/fedora-infrastructure/ticket/4674
