### ISSUE TITLE
Autosuggest distribution in project mapping

### ISSUE THREAD

**Issue by voxik** [fedora-infra/anitya#79]
It would be nice if distribution were autosuggested in project mapping page [1]. What actually happens if I make a typo?

[1] https://release-monitoring.org/project/5474/map

**Comment by pypingou** [comment]
Typos means: new distro added :)

But :+1: on the autocompletion

**Comment by glensc** [comment]
besides autosuggestion, would be nice if input field gets focus when page is loaded
