### ISSUE TITLE
Very hard to install due to documentation and bugs

### ISSUE THREAD

**Issue by stormi** [fedora-infra/anitya#798]
I've been trying to install anitya on my own server for several days (granted, not full-time) and without the help from the developers in IRC I wouldn't be anywhere. 2 years ago I had installed it and I remember I had to ask for help once or two, but not at every step.

So I'm documenting here my journey to help others maybe make it work faster and for issues to be identified in the documentation or the code.

Basically, what *should* work is if you apply exactly the [ansible configuration from Fedora](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/openshift-apps/release-monitoring). This is what is tested automatically. 

Now if you're trying to follow [the docs](https://anitya.readthedocs.io/en/stable/admin-guide.html#installation) first, like I did:
- `pip install anitya` (in a dedicated virtualenv, preferrably) is useful to pull all the dependencies, but then I couldn't find some important bits like `createdb.py`. So I downloaded the code from this repository and worked from that.
- the example configuration file is currently broken, fixed in https://github.com/release-monitoring/anitya/commit/52422335ac7c39d31fb92d8d476066da628c24cd
- `anitya.wsgi` that is mentioned several times in the docs doesn't exist anywhere. Copy it from https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/openshift-apps/release-monitoring/templates/anitya.wsgi or just create it, all it contains is `from anitya.wsgi import application`.
- the documentation does not tell how to run the wsgi exactly. Fedora uses apache so you can look at [their configuration](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/openshift-apps/release-monitoring/templates/httpd.conf). Or you can run it manually with flask (debugging only) by following [this part of the development guide](https://anitya.readthedocs.io/en/stable/contributing.html#python-virtualenv).
- `createdb.py` (which should be added to the installation doc) does not create the `social_auth*` tables, and they're not created a first run either. Thus login won't work. One solution is to use the postgresql database dump from https://infrastructure.fedoraproject.org/infra/db-dumps/anitya.dump.xz, and remove all data (but don't miss the constraints like I did or your `id` fields will not be autoincrements and you'll fall into a very special case where login fails **without ANY error in the logs**).

For future upgrades of anitya, fix the database path in alembic.ini, where it must have the same value as in `anitya.toml`.

Note: there's also the option to use vagrant to run a test instance, but I did not follow this route because I was aiming at a production instance.

**Comment by stormi** [comment]
Update: `createdb.py` + `alembic upgrade head` (the latter to add the missing tables) doesn't work: it tries to add a column that exists already and fails.

By the way it feels strange to run an upgrade command just after a database creation that should already have created all the tables, so there seems to be something to solve in the database creation step itself.

**Comment by stormi** [comment]
I have updated the description after finding out why the login query failed completely silently.

**Comment by Zlopez** [comment]
I'm glad that you finally find the root of this issue.

**Comment by dfateyev** [comment]
Using third-party dumps with manual cleanup is not a solution, in overall. The documentation should be clear on how to prepare a working DB instance.

**Comment by Zlopez** [comment]
This more looks like issue in `social_auth_flask` library, because they should create the tables on clean database.

**Comment by stormi** [comment]
From the look I took on the code, I think something is missing on anitya's side to trigger such a build. The dynamic construction of the model at https://github.com/release-monitoring/anitya/blob/master/anitya/app.py#L66 is a runtime things to load the models in memory, but it does not create the tables. Actually, it runs even if the tables exist (you can add debug traces to check that).

In my opinion, something is missing to make `createdb.py` take those tables into account and create them. It looks suspicious to me that they are not mentioned in https://github.com/release-monitoring/anitya/tree/master/anitya/db (except in one specific place that does not look sufficient to me: https://github.com/release-monitoring/anitya/blob/ff2dc367f94219aeee67627fb9c20be50ea4c05e/anitya/db/models.py#L792).

**Comment by Zlopez** [comment]
You could be right, but according to `social_auth` [documentation](https://python-social-auth-docs.readthedocs.io/en/latest/configuration/flask.html) this should be enough, but it's possible that the `social_init` should be part of `db_init` function.

**Comment by dfateyev** [comment]
@stormi actually, there is a simpler way to restore missing DB schema.
The command `"alembic history"` shows DB migration tree, and it looks like that `"feeaa70ead67"` is missing.
So bumping version to `"a52d2fe99d4f"`: `SQL> INSERT INTO alembic_version (version_num) VALUES ('a52d2fe99d4f');` (the previous version), and updating to `"feeaa70ead67"`: `"alembic upgrade feeaa70ead67"` solved the issue.

**Comment by dfateyev** [comment]
@Zlopez could you provide some documentation on integration Anitya with fedmsg or fedora-messaging (whatever works)? I cannot realize how to push notifications from an installed Anitya instance to some external service. Thanks.

**Comment by Zlopez** [comment]
We are now using fedora-messaging.

For the integration you could look at https://github.com/release-monitoring/anitya/blob/master/ansible/roles/anitya-dev/tasks/rabbitmq.yml, which is the ansible playbook used for setting up a rabbitmq server, which is working as a messaging bus and it's also used in Fedora Infrastructure.

When you open it's interface (it should run by default on 15672 and login and password is `guest`) you should see some queues that will be getting messages.

**Comment by dfateyev** [comment]
@Zlopez thanks, basically I see connections to local RabbitMQ server when a new release found, but there are no new queues are created.
```
2019-08-13 10:07:03.810 [info] <0.13926.0> accepting AMQP connection <0.13926.0> (127.0.0.1:42938 -> 127.0.0.1:5672)
2019-08-13 10:07:03.871 [info] <0.13926.0> connection <0.13926.0> (127.0.0.1:42938 -> 127.0.0.1:5672): user 'guest' authenticated and granted access to vhost '/'
2019-08-13 10:10:03.859 [error] <0.13926.0> closing AMQP connection <0.13926.0> (127.0.0.1:42938 -> 127.0.0.1:5672):
missed heartbeats from client, timeout: 60s
```
```
./rabbitmqadmin -f long -d 3 list queues
No items
```
There are no errors on Anitya side though. Maybe another misconfigured option?

**Comment by Zlopez** [comment]
Strange, you should see some exchanges in the web interface. I didn't configured the local instance of rabbitmq server myself, so I'm not sure what could be wrong.

I will try to look at it, if the same is happening in devel environment.

The error itself looks like some connection issue.

**Comment by Zlopez** [comment]
@dfateyev I tried to try it today, but I encountered this issue in devel environment https://github.com/release-monitoring/anitya/issues/804

So I need to fix this first

**Comment by Zlopez** [comment]
@dfateyev I was able to fix the issue above, so now I know why there isn't any queue. The Anitya is only publisher, so there is no queue bind required. It's just sending every message to `amq.topic` exchange.

**Comment by dfateyev** [comment]
@Zlopez as for AMQP integration, it's still cryptic due to lacks of documentation. I see` "amq.topic"` exchange with `'topic'` type, and some connections from Anitya to RabbitMQ, but don't know which routing key Anitya messages have. Which queue the consumer need to create to obtain messages from Anitya? Whether I need to create consumers and queues prior Anitya sends AMQP notifications? Could you provide a basic example on how to handle a message from Anitya?

**Comment by dfateyev** [comment]
@Zlopez maybe I missing something, but how to restrict editing Anitya project only to its owner and admins? Being logged in as an ordinary user, I can edit projects created by another (admin) user.

**Comment by Zlopez** [comment]
@dfateyev Editing is not restricted, only deleting is.

**Comment by dfateyev** [comment]
@Zlopez I think there are such restrictions on "release-monitoring.org", right? I don't think it's possible to edit any project of any user there. Whether it's possible to implement something similar on a separate Anitya instance?

**Comment by Zlopez** [comment]
@dfateyev You should be able to edit any project, if you are logged in. You could easily try it on stg.release-monitoring.org

**Comment by dfateyev** [comment]
@Zlopez thanks for the answer! Another question: is it possible to limit user registration by email, so only users with a specific email domain could login to Anitya via OAuth provider?

**Comment by Zlopez** [comment]
I don't think we have any feature like this in place. We allow multiple authentication mechanics, but no restriction for e-mail.
