### ISSUE TITLE
Github project addition issues

### ISSUE THREAD

**Issue by dfateyev** [fedora-infra/anitya#803]
Cannot add proper Github project monitoring:
```
[wsgi:error] [pid 10478] [anitya.config INFO] Loading Anitya configuration from /etc/anitya/anitya.toml
[wsgi:error] [pid 10479] [anitya.lib.utilities ERROR] AnityaError catched:
[wsgi:error] [pid 10479] Traceback (most recent call last):
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/anitya/lib/utilities.py", line 98, in check_project_release
[wsgi:error] [pid 10479]     versions_prefix = backend.get_versions(project)
[wsgi:error] [pid 10479]   File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/anitya/lib/backends/github.py", line 150, in get_versions
[wsgi:error] [pid 10479]     % (project.name, resp.status_code, resp.reason)
[wsgi:error] [pid 10479] anitya.lib.exceptions.AnityaPluginException: kubernetes: Server responded with status "401": "Unauthorized"
```

> Homepage: https://kubernetes.io/
> Backend: GitHub
> Ecosystem: https://kubernetes.io/
> Version scheme: Date
> Version check url: https://github.com/kubernetes/kubernetes/tags
> 
> Fail | 2019-08-09 11:25:42 (UTC) | kubernetes: Server responded with status "401": "Unauthorized"

What this issue related to? An appropriate Github project doesn't require any specific authorization.

**Comment by Zlopez** [comment]
Are you trying this on release-monitoring.org or is this some separate instance?

This looks like you missing the Github OAuth token in config.toml.

**Comment by dfateyev** [comment]
I'm trying on a separate instance, and BTW I have no idea how to configure `config.toml` (where it should be located at?)
As for the Github auth in general, does it require an user token? I'm checking a public repo, so e.g. https://github.com/kubernetes/kubernetes/tags doesn't require any auth.

**Comment by Zlopez** [comment]
The `config.toml` is usually located in `/etc/anitya/`.
I didn't get login using Github to work, but for Github backend you need github user token.

**Comment by Zlopez** [comment]
You could change location of `config.toml` by setting `ANITYA_WEB_CONFIG` environment variable. You could look at example [here](https://github.com/release-monitoring/anitya/blob/master/ansible/roles/anitya-dev/files/anitya.service), it is systemd unit used in development environment.

**Comment by dfateyev** [comment]
Indeed, adding a valid Github account token solved the issue.
I believe it's worth to add a note to documentation, along the permission scope needed for this token (I've set `public_repo, read:packages, read:public_key, read:user, repo:status, repo_deployment` just in case, but it's too broad I believe).

**Comment by Zlopez** [comment]
Yes, you are right, I should update the docs about this.
