### ISSUE TITLE
Can not login with FAS

### ISSUE THREAD

**Issue by williamjmorenor** [fedora-infra/anitya#82]
Hi

I got this error trying to login in the system with my FAS

Error during login: OpenID authentication failure. Mesage: No matching endpoint found after discovering http://williamjmorenor.id.fedoraproject.org/

**Comment by tyll** [comment]
Thank you for the report. This should be fixed now.

**Comment by williamjmorenor** [comment]
:(

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by tyll** [comment]
On Fri, Feb 20, 2015 at 04:04:06PM -0800, William Moreno wrote:
> :(
> 
> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This was probably just a coincidence when a server was restarted or do
you see it permanently?

**Comment by williamjmorenor** [comment]
It is working

**Comment by pypingou** [comment]
Let's close then, thanks for the report though!
