### ISSUE TITLE
Allow to check for new releases while still creating the project

### ISSUE THREAD

**Issue by tyll** [fedora-infra/anitya#84]
It would be nice to be able to check whether a project config works while already creating it, so it can be checked before it is added.

**Comment by robert-scheck** [comment]
I noticed that manually checking for new releases can be also triggered only once (if no version is known so far) but if it matches the wrong release etc. no futher check can be scheduled manually?

**Comment by pypingou** [comment]
You can only check the release manually until it finds something, afterward only admins can adjust.

This is not the first time it is mentioned so we will have to change this behavior

**Comment by rapgro** [comment]
:+1:
