### ISSUE TITLE
Logged out of interface much too quickly

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/anitya#847]
I was doing multiple things on release-monitoring.org today, but separated by some time as I was building and importing packages. However, I was logged out every time within a matter of hours. I'm not sure if it was less than 1, but it can't have been more than 3-4 hours. It would be preferable to be a day at least (or even a week maybe?).

**Comment by Zlopez** [comment]
I think this is not set explicitly anywhere in Anitya, so it's probably using some default value. Best solution here is to make this configurable.

**Comment by Zlopez** [comment]
I found out that this is already configurable in Anitya, default value is one hour.

**Comment by Zlopez** [comment]
I'm closing this in favor of https://github.com/fedora-infra/anitya/issues/952

**Comment by glensc** [comment]
@Zlopez point to code where it's already configured?

**Comment by Zlopez** [comment]
@glensc It's set to 1 hour for last 2 years https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/release-monitoring/templates/anitya.toml#_11
