### ISSUE TITLE
Searching for "mod_*" includes "mod*"

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/anitya#86]
When searching for `mod_*` I also get all results for `mod*` - this doesn't feel right to me.

**Comment by pypingou** [comment]
Apparently ``mod\_*`` works better but it also surprises me a little

**Comment by pypingou** [comment]
Amusingly ``mod_p*`` does work as expected...

**Comment by pypingou** [comment]
So it seems that underscore is a special character for LIKE queries [1] as we are using here, so this behavior makes sense and I am not sure we should change it

[1] http://www.postgresql.org/docs/8.3/static/functions-matching.html

**Comment by ralphbean** [comment]
It seems to me like we shouldn't make postgres' special characters matter to users at all.              
That's a database specific thing.  We shouldn't expect users to know database-specific things about our apps, so I'm :+1: on changing it.
