### ISSUE TITLE
I keep getting 504 Gateway Time-out when trying to edit

### ISSUE THREAD

**Issue by eclipseo** [fedora-infra/anitya#875]
I have a large set of projects to edit to fix the homepages but when submitting the change I keep getting this error:

```
504 Gateway Time-out
The server didn't respond in time. 
```

Is there anything that can be done to fix that?

Thank you.

**Comment by Zlopez** [comment]
I looked at the Anitya and everything is fine. This is probably issue in one of the proxies. Could you post here which Gateway is returning this?

P.S.: Fedora Infra is now on holidays leave, so I think this will not be solved till 6th January. See https://communityblog.fedoraproject.org/infrastructure-support-over-the-holidays/

**Comment by Zlopez** [comment]
I think it will be also good to file ticket [here](https://pagure.io/fedora-infrastructure/issues) on official fedora infra issue tracker.

**Comment by eclipseo** [comment]
Thanks. I'll report it to infra.

>Could you post here which Gateway is returning this?
How do I get this info?

**Comment by Zlopez** [comment]
I saw that Infra team did some changes regarding proxies, does this helped with your issue.

**Comment by eclipseo** [comment]
Don't know, I've managed to do all my edit between failures. I'll have to try again next time I have mass changes.
For now I will close this.
