### ISSUE TITLE
Allow mapping deletions

### ISSUE THREAD

**Issue by siwinski** [fedora-infra/anitya#88]
The "[Drupal 7](https://release-monitoring.org/project/627/)" Anitya project (note that it was originally named "drupal" but I changed it to "Drupal 7") was created during the migration from the wiki-based upstream monitoring but it incorrectly maps to Fedora packages `drupal6` **and** `drupal7`.  I created the "[Drupal 6](https://release-monitoring.org/project/5619/)" Anitya project but I cannot map it to the `drupal6` Fedora package because the package is already mapped to the "Drupal 7" Anitya project.

**Comment by pypingou** [comment]
Mapping for Drupal 7 deleted

**Comment by pypingou** [comment]
And adjusted for drupal6

Thanks!

**Comment by ppisar** [comment]
I cannot remove misspelled Fedorda mapping for CDDB project <https://release-monitoring.org/project/5867/>.

**Comment by pypingou** [comment]
I can :)

**Comment by pypingou** [comment]
Done ! :)
