### ISSUE TITLE
Allow removing mapping

### ISSUE THREAD

**Issue by tpetazzoni** [fedora-infra/anitya#890]
Anitya currently allows to add and edit distro mappings, but apparently not to remove them. For example https://release-monitoring.org/project/20876/ had a bogus mapping for the Buildroot distribution, under the name "python-inflection". But this project 20876 is not the Python "inflection" module but some unrelated Go package. I have created a separate project, https://release-monitoring.org/project/67637/, to track the Python inflection module, but I cannot remove the bogus Buildroot mapping on project 20876.

**Comment by Zlopez** [comment]
This is why there is flag button for each project, we don't want to allow random users to remove things from the anitya, so this is only possible to be done by admins.

**Comment by Zlopez** [comment]
The bogus mapping was removed.
