### ISSUE TITLE
Issue with selinux project indexing

### ISSUE THREAD

**Issue by tpetazzoni** [fedora-infra/anitya#897]
The selinux projects, such as https://release-monitoring.org/project/1717/ are badly indexed by Anitya. In the current list of versions, we have three different types:
- date based versions, which are sorted as the first ones
- semantic versions, with no prefix
- semantic versions, with prefixes some of them being invalid. It seems this was fixed by the addition of "libselinux-" as a prefix prefix since then.

Would it be possible to fix this project by dropping all versions except the semantic versions with no prefixes. The semantic versions are what are used to name the individual SELinux tarballs, and the version used by distributions such as Fedora to reference SELinux components versions.

**Comment by Zlopez** [comment]
I removed every version except the semantic versions without prefix.

I can't guarantee the versions will not show again, because the prefix field doesn't work as filter, it just removes the prefix from any retrieved tag.
