### ISSUE TITLE
Flush mii-diag versions

### ISSUE THREAD

**Issue by tpetazzoni** [fedora-infra/anitya#900]
The regexp used for the mii-diag project https://release-monitoring.org/project/21748/ was capturing the Debian-specific sub-version, i.e 2.11-3 instead of just using the "upstream" version 2.11. I have adjusted the regexp to address this and make sure we only capture the "upstream" version. Would it be possible to "flush" the bogus versions, so that 2.11 really appears as the latest ? Thanks!

**Comment by Zlopez** [comment]
Done, the bogus versions are removed.
