### ISSUE TITLE
anitya-schema to anitya-messages for consistency

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/anitya#926]
For some reason I would prefer https://pypi.org/project/anitya-schema/ to be named `anitya-messages` for consistency with https://github.com/fedora-infra/noggin-messages and general clarity. Because the package contains message descriptions, not DB schema or data exchange formats.

I remember this was discussed before, but could not find the reference.

**Comment by Zlopez** [comment]
I like how they moved it to separate repo. It's much easier for releasing.

**Comment by Zlopez** [comment]
I don't want to rename the package on pypi, because this will break the dependency for all projects who use it. But the messages were moved to separate repo, so I'm closing this as done.
