### ISSUE TITLE
Anitya shouldn't treat no new version retrieved as failed check

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#929]
With introduction of cursors in GitHub backend we created a bug that is considering no version found as failed check. This shouldn't happen, if no version is found it should still be a successful check.

**Comment by nqb** [comment]
Thanks for opening this bug, that's certainly the root cause of #922.

**Comment by Zlopez** [comment]
Already fixed by https://github.com/fedora-infra/anitya/issues/892
