### ISSUE TITLE
Add option to delete user to users management page

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#931]
# Description
We should allow admins to delete users from db when needed.

## Requirements
* Add delete button to users on user management page

## How this will make Anitya better
This will allow admins solve some authentication issues quickly without the need to have direct access to database.

**Comment by lightlace** [comment]
I'd like to work on this.

**Comment by Zlopez** [comment]
@lightlace Feel free to take the issue. :-)

**Comment by Freedisch** [comment]
@Zlopez I will take a look at it, if it's still a valid issue

**Comment by Zlopez** [comment]
@Freedisch Yes, this is still a feature we want to see implemented. Feel free to assign yourself to ticket or I can assign it to you.

**Comment by Freedisch** [comment]
Yes, please assign it

**Comment by Freedisch** [comment]
@Zlopez, I was wondering, How to access the user management page? Unless I missed it, I couldn't see the section referring to how to log in as an admin.

**Comment by Zlopez** [comment]
You need to add yourself to admins in anitya.toml configuration file. Only admins has access to user management.
