### ISSUE TITLE
Containerized workflow

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/anitya#936]
# Description
Because release-monitoring.org is running in OpenShift it will be nice to have similar environment for development. This means using containers instead of Vagrant.

## Requirements
* Create a containers for Anitya (web, libraries.io consumer, check_service)
* Create a container for RabbitMQ
* Create a container for Postgres DB
* Anitya containers should be able to connect to RabbitMQ and Postgres DB containers
* Update contribution guide
* (Optional) Use pytest-docker for integration testing, this means any tests that needs postgres to run

## How this will make Anitya better
This will make production env and dev env almost one to one and will allow us to reproduce issues we encounter in production much more easily.

**Comment by ozkanonur** [comment]
I can do this, If not currently being developed by anyone else @Zlopez

**Comment by Zlopez** [comment]
@ozkanonur You can take it, nobody is working on this now

**Comment by ozkanonur** [comment]
Are we going to do the same thing here that we did for the-new-hotness? I mean we do this only for the development environment?

**Comment by Zlopez** [comment]
Yes, this should work the same as in the-new-hotness.

**Comment by ozkanonur** [comment]
Do we need a container for "check_service"? If it's not an application and just checking things, it can be executed in web's or consumer's container. @Zlopez

**Comment by Zlopez** [comment]
It is in it's own container in OpenShift, because it's a service that could run independently. But yes, in this case it could run in web's container.
