### ISSUE TITLE
add possibility to check/recheck without editing a project

### ISSUE THREAD

**Issue by cheese1** [fedora-infra/anitya#943]
currently one needs to login, modify a project and than two buttons appear: test check and full check.
both should be available without the need for modifying the project. in fact it is enough to edit a project WITHOUT actually modifying something to get that buttons. weird and not very easy to understand.

**Comment by Zlopez** [comment]
This is on the roadmap for 1.0. See https://github.com/fedora-infra/anitya/issues/491.
