### ISSUE TITLE
Cannot find maintenance releases in older subdirectories

### ISSUE THREAD

**Issue by gotthardp** [fedora-infra/anitya#953]
Maintenance released of Linux are not detected. The https://release-monitoring.org/project/6501/ shows 4.14.111 as the last 4.14.x, despite the latest is 4.14.188. When a new long-term support version is released, no notification is sent. The version is not even listed as available.

This is because Linux stores it's releases in "v4.x", "v5.x" and "v6.x" subdirectories and only the latest is searched. I would expect the use of a glob URL `https://mirrors.edge.kernel.org/pub/linux/kernel/v*/` will find all versions, but it does not. The `expand_subdirs` seems to use the lexicographically latest subdir only, see https://github.com/fedora-infra/anitya/blob/master/anitya/lib/backends/__init__.py#L135. This means that no other v5.x release will be found once somebody creates the v6.x directory, because since then only the v6.x will be searched.

I suggest the system finds also new 4.x releases even when the 5.x or 6.x branch is started.

**Comment by Zlopez** [comment]
This is in plan for current milestone. See https://github.com/fedora-infra/anitya/issues/774
