### ISSUE TITLE
Mapping release-38-alpha2 in GitHub to 38.0_13.0_0_1~alpha2-1 in Fedora

### ISSUE THREAD

**Issue by fujiwarat** [fedora-infra/anitya#962]
I'm tracking CLDR project  in GitHub with Anitya.

https://release-monitoring.org/project/103642/
https://github.com/unicode-org/cldr/tags

Since I'm interested in emoji annotation files only in CLDR, I copy the subdirectory of common/annotation in CLDR to https://github.com/fujiwarat/cldr-emoji-annotation and integrate the package to Fedora.

E.g.
1. Anitya detects release-38-alpha1 in https://github.com/unicode-org/cldr/tags
2. I copy common/annotation in CLDR with release-38-alpha1 tag to https://github.com/fujiwarat/cldr-emoji-annotation
3. Release 38-alpha1.0_13.0_0_1 in https://github.com/fujiwarat/cldr-emoji-annotation
4. Release 38.0_13.0_0_1~alpha1-1.fc33 in Fedora https://koji.fedoraproject.org/koji/packageinfo?packageID=23853

The `38-alpha1.0_13.0_0_1` means CLDR version 38-alpha1, emoji version 13.0, CLDR micro version 0, local build version 1.
The `~alpha1` in `38.0_13.0_0_1~alpha1-1.fc33` is used to make 38 will be a greater number than 38~alpha1 in Fedora packaging.

Yesterday release-38-alpha2 was released in https://github.com/unicode-org/cldr/tags but Anitya failed to compare release-38-alpha2 and 38.0_13.0_0_1~alpha1-1.fc33

Do you have any ideas how to handle the version scheme and version prefix in my case?

**Comment by Zlopez** [comment]
I see in Anitya that the versions are sorted correctly. 

I suspect that by the comparison of release in Fedora and upstream, you mean the comparison done by [the-new-hotness](https://github.com/fedora-infra/the-new-hotness). Do you have link to bugzilla, so I could see what the-new-hotness sent?

**Comment by fujiwarat** [comment]
As you see https://release-monitoring.org/project/103642/ ,  it failed to get the version and output "cldr-github: No upstream version found." in that page and the-new-hotness does not send anything unfortunately.

**Comment by Zlopez** [comment]
This error is known and it doesn't actually mean that there is error, just there is no new version on the upstream. I already have a fix for that, but I'm waiting till staging will be up to test it first. The staging environment is currently being worked on after datacenter move.

If the-new-hotness didn't sent anything it probably considered the version older than the one currently available.

**Comment by fujiwarat** [comment]
> If the-new-hotness didn't sent anything it probably considered the version older than the one currently available.

This is the original question from mine.
Do you have any ideas how the-new-hotness can recognize  release-38-alpha2 > 38.0_13.0_0_1~alpha1-1.fc33 ?

**Comment by Zlopez** [comment]
Don't have any idea right now, but could you open an ticket on the-new-hotness for feature request?

**Comment by fujiwarat** [comment]
OK, I see. Thank you.
