### ISSUE TITLE
mapping with slash in package name cannot be deleted

### ISSUE THREAD

**Issue by luto** [fedora-infra/anitya#965]
# General

Some mappings might have a forward slash (`/`) their package name. Seems to be common or request in Gentoo at least.

For example: https://release-monitoring.org/project/1823/ (Gentoo, mapping ID 14111)

# Expected

When I try press the "Delete" button of such a mapping, the delete-confirm page should show up, allowing me to delete the mapping.

# Actual

Pressing "Delete" navigates to `/project/1823/delete/Gentoo/net-voip/linphone`, which 404s. Changing the URL to `/project/1823/delete/Gentoo/net-voip%2Flinphone` to escape the slash doesn't resolve the problem.

# Suggested Solution

Refer to mappings by the ID instead of their package name when deleting, e.g. `/project/1823/map/14111/delete`, following the scheme of `/project/1823/map/14111` for editing.

**Comment by Zlopez** [comment]
We have similar issue with version https://github.com/fedora-infra/anitya/issues/596

**Comment by luto** [comment]
https://release-monitoring.org/project/13746/ (Gentoo, mapping ID 19909)
