### ISSUE TITLE
Opt-in for Hacktoberfest

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/anitya#975]
https://hacktoberfest.digitalocean.com/details#maintainers - just adding a `hacktoberfest` tag to the repo should be fine.

**Comment by Zlopez** [comment]
Thanks for letting me know, I added the hacktoberfest label to some issues, but didn't know about the topic.

**Comment by abitrolly** [comment]
Hacktoberhest swag brings motivation to complete some long standing PRs. )

**Comment by Zlopez** [comment]
I noticed :-D
