### ISSUE TITLE
Error 400 when checking Poetry version

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/anitya#976]
https://release-monitoring.org/project/17793/ test check returns error `poetry: No upstream version found.` but URL with tags is right.

![image](https://user-images.githubusercontent.com/8781107/95574808-3e05a080-0a36-11eb-81fc-8d15b5a7e832.png)

Maybe it is possible to give a better error message?

**Comment by Zlopez** [comment]
This is hitting https://github.com/fedora-infra/anitya/issues/929 and it's fixed in current devel version.

**Comment by abitrolly** [comment]
@Zlopez maybe we could setup continuous integration to push fixes faster?

**Comment by Zlopez** [comment]
I already have something like this, but I want to test it on the staging first and the staging is still a work in progress after datacenter move.

**Comment by abitrolly** [comment]
I've seen https://apps.fedoraproject.org/packages/ is down, and it looks like it is down since September. What is the major problem that takes the process so long?

**Comment by Zlopez** [comment]
There are replacements for packages app that are being worked on. But if you are asking about staging, it took plenty of time till datacenter was moved and everything in prod was up and running. The staging is also being deployed with new account system Noggin, which is introducing plenty of new challenges on itself.

Once the staging will be up, I release a new version of the-new-hotness and Anitya. There are plenty of fixes and features ready.
