### ISSUE TITLE
libmodplug ghost distro mapping

### ISSUE THREAD

**Issue by scop** [fedora-infra/anitya#98]
I tried to add the libmodplug project, got an internal server error while adding it, and now I cannot add a distro mapping (Fedora, libmodplug) for it, the service tells me "Could not edit the mapping of libmodplug on Fedora, there is already a package libmodplug on Fedora" but the mapping is not actually shown in the project mappings view.

https://release-monitoring.org/project/5669/

**Comment by scop** [comment]
Oh, the reason seems to be that the mapping actually does exist, but it's in the modplug-xmms project which is wrong. So there are actually two bugs to fix here:

1) The service should say *where* an existing mapping exists. In this case it should have mentioned that the mapping is in the modplug-xmms project.
2) There doesn't seem to be any way to delete a mapping so I cannot fix the situation. The modplug-xmms project also contains a mapping for modplugtools which is equally wrong.

**Comment by pypingou** [comment]
The first point is fixed in the commit above, the second one is present but apparently only accessible to admins.

Question becomes: do we want to make this more open?
