### ISSUE TITLE
Clear ucx releases

### ISSUE THREAD

**Issue by opoplawski** [fedora-infra/anitya#981]
I think I have the ucx regex working now, but it shows a bunch of previous release checks that don't match the current test check.  Can those be cleared?  Thanks!

**Comment by Zlopez** [comment]
Hi, I think I deleted every bogus version. Just one question: Why didn't you use GitHub backend for this project?

**Comment by opoplawski** [comment]
They switched the style of tags at different points so it seemed like the version check got confused.  If you can get it to work with the GitHub backend, be my guest.  Thanks.
