### ISSUE TITLE
Staging server for the next release

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/anitya#985]
Anitya currently has 66 commits in master since [last release](https://github.com/fedora-infra/anitya/releases/tag/0.18.0) and development is stuck, because there is low motivation to work on new things when then [old keep reoccuring](https://github.com/fedora-infra/anitya/issues/976).

Anitya can not be deployed, because staging server for it is not ready. What the outstanding problems to bring this staging server online?

**Comment by Zlopez** [comment]
I wanted to have all the bits ready for 1.0 release, but I could probably release 0.19.0 before that. I'm working on other things beside Anitya, this is why the development is slow.

The staging Anitya is now deployed (I deployed it last week), the backend is running, but there is one [issue with certificate](https://pagure.io/fedora-infrastructure/issue/9454), which I see should be already solved.

**Comment by abitrolly** [comment]
https://stg.release-monitoring.org/ reports 0.18 at the bottom. It is possible to add source revision there on deployment? How does deployment work right now?

**Comment by Zlopez** [comment]
The staging is deployed the same way as it was before when the staging branch is changed. You can look at the current deployed version by checking the staging branch itself.

And the version deployed now is really 0.18.

**Comment by abitrolly** [comment]
The deployment process is still undocumented, and as such it is not clear where in the pipeline to add code revision line.

**Comment by Zlopez** [comment]
The deployment process is described in the [infrastructure SOP for Anitya](https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/anitya.html#releasing). I could also describe it in the Anitya documentation itself. As part of the 1.0 milestone I want to update it to up to date state anyway.

**Comment by abitrolly** [comment]
@Zlopez link to infra SOP should be sufficient as the SOP docs are an awesome piece on their own. :)

**Comment by abitrolly** [comment]
@Zlopez 

> To deploy staging instance of Anitya you need to push changes to staging branch on Anitya Github. GitHub webhook will then automatically deploy a new version of Anitya on staging.

Where is the source code for this webhook?

**Comment by Zlopez** [comment]
This is using the OpenShift webhook in fedora ansible repository. [Here](https://pagure.io/fedora-infra/ansible/blob/master/f/roles/openshift-apps/release-monitoring/templates/buildconfig.yml) is the buildconfig for Anitya.

**Comment by abitrolly** [comment]
Ansible repo that builds `Dockerfile` through Kubernetes style `.yaml`. If this is going to be referenced from the current https://github.com/fedora-infra/anitya/tree/master/ansible then the whole process including top level `Dockerfile` for development wll be too funny. :D
