### ISSUE TITLE
GET /v2/packages no results for some names

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/anitya#989]
https://stg.release-monitoring.org/api/v2/packages/?name=virtualenv gives empty list.

But https://stg.release-monitoring.org/project/6904/ and https://stg.release-monitoring.org/project/virtualenv/ are there,

**Comment by abitrolly** [comment]
I misspelled endpoint. Should have been `/projects` https://stg.release-monitoring.org/api/v2/projects/?name=virtualenv However, it is still unclear how these two are linked together through API. How to know which package corresponds to a given project?

**Comment by Zlopez** [comment]
The package is mapping to some distribution and the name is the name of the mapping, the project is project in Anitya.
