### ISSUE TITLE
RFE: friendly project URLs

### ISSUE THREAD

**Issue by scop** [fedora-infra/anitya#99]
Instead of a numeric ID in the project URL, it would be good to support the project name in place for it. So for example instead of/in addition to https://release-monitoring.org/project/5669/ Anitya should work with https://release-monitoring.org/project/libmodplug/ (the latter gives an internal server error ATM).

**Comment by ralphbean** [comment]
The problem, @scop, is that there are many upstreams that have the same name.. but are totally different projects.  Take, for example, the name 'mock'.  There's the Fedora build-in-a-chroot mock tool we all know and love.  There's also a widely used python testing library called 'mock' (python-mock in Fedora.. but everyone upstream just knows it as 'mock').

This is why we went with numeric IDs originally.

Unless someone can come up with a novel way around this, we're stuck with numeric IDs.  Please re-open if you come up with one.  :)

**Comment by scop** [comment]
I don't know how to reopen the bug, github does not seem to give me that option. Please do it for me.

I don't think many projects by the same name is a real problem. Just declare the project name unique in Anitya and make people come up with unique names for projects within it. It doesn't matter if it doesn't match exactly with the upstream name -- showing several projects by the same name isn't helpful either because people have to click through them and guess the one they're interested in anyway.

**Comment by scop** [comment]
If you don't want to make project names unique, friendly URLs could still be supported: if there are multiple projects by the requested name, show list of them, otherwise show the matching project (or redirect to its numeric id).

Now please reopen this issue so it won't be forgotten and I don't have to file another one for it :)

**Comment by ralphbean** [comment]
> if there are multiple projects by the requested name, show list of them, otherwise show the matching project (or redirect to its numeric id).

I like it!

**Comment by pypingou** [comment]
:-1: on making the name unique, that's why we show not only the name but also the homepage of the project when listing them, there are really way too many projects with the same name
