### ISSUE TITLE
release-monitoring.org redirects to HTTP when editing project

### ISSUE THREAD

**Issue by leoluk** [fedora-infra/anitya#990]
![image](https://user-images.githubusercontent.com/859697/102016885-8f4a4d00-3d63-11eb-8ce9-6a34155c1888.png)

**Comment by Zlopez** [comment]
Why are you using HTTP?

**Comment by leoluk** [comment]
Apologies, should've been more clear about this - the POST request to the server redirects me to HTTP:

![image](https://user-images.githubusercontent.com/859697/102020375-25d53900-3d79-11eb-83c4-3da8b1375113.png)

**Comment by Zlopez** [comment]
I tried it today in Firefox and didn't saw the issue and looking at the request, I don't see the HttpOnly in cookie anywhere.

**Comment by leoluk** [comment]
Did you try with Chrome/Chromium? I'm not doing anything special.

**Comment by Zlopez** [comment]
I don't use it and don't have it installed anywhere.

**Comment by leoluk** [comment]
All I can say is that, in a default Chrome installation, logging in to release-monitoring.org redirects me to HTTP on POST.

Feel free to close this issue if you believe this not to be an issue.

**Comment by Zlopez** [comment]
I will close this issue, because I don't know if there is anything the Anitya could do about it.
