### ISSUE TITLE
add sourcehut backend

### ISSUE THREAD

**Issue by geeseven** [fedora-infra/anitya#999]
Sourcehut is starting to gain some traction and I think is a good candidate for a dedicated backend.  There are already some packages in Fedora that use sourcehut.  Like Gitlab, users can choice between vendor hosted or selfhosting solutions.

For a project where anitya would be overkill, I came up with a script that does xml processing for git repositories and regex for mercurial repositories (no rss feeds yet).

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from re import findall
from sys import argv

from requests import get
from xmltodict import parse

url = argv[1]

r = get(url + "/refs/rss.xml")

if r.ok:
    rss = parse(r.text)
    versions = [item["title"] for item in rss["rss"]["channel"]["item"]]
else:
    html = get(url + "/tags").text
    # [1:] removes tip, I am sure there is better regex would make that unneeded
    versions = findall(r'archive\/(.*)\.tar.gz"', html)[1:]

print(*versions, sep=", ")
```

```console
$ ./sh-versions.py https://git.sr.ht/~sircmpwn/scdoc
1.11.1, 1.11.0, 1.10.1, 1.10.0, 1.9.7, 1.9.6, 1.9.5, 1.9.4, 1.9.3, 1.9.2, 1.9.1, 1.9.0, 1.8.1, 1.8.0, 1.6.1, 1.6.0, 1.5.2, 1.5.1, 1.5.0, 1.4.3

$ ./sh-versions.py https://hg.sr.ht/~scoopta/wofi
v1.2.3, v1.2.2, v1.2.1, v1.2, v1.1.2, v1.1.1, v1.1, v1.0
```

I currently do not have the bandwidth to create a pull request, but feel free to use this as a starting point.

**Comment by Zlopez** [comment]
This sounds like a nice feature for Anitya.
